Repository project-koku/koku, pull requests merged in 2018-11, with the labels that each got.

#442 API response for daily, time_scope_values queries returns correct number of days
  koku/api/report/queries.py
  koku/api/report/test/tests_queries.py
Labels: bug

#440 Preliminary OCP API work
  docs/source/specs/openapi.yml
  koku/api/report/aws/aws_query_handler.py
  koku/api/report/aws/view.py
  koku/api/report/ocp/__init__.py
  koku/api/report/ocp/ocp_query_handler.py
  koku/api/report/ocp/serializers.py
  koku/api/report/ocp/view.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/__init__.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler_base.py
  koku/api/report/test/ocp/tests_serializers.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/tests_queries.py
  koku/api/report/test/tests_views.py
  koku/api/urls.py
  koku/api/views.py
Labels: enhancement

#449 Adding in node capacity and pod labels to ocp report models
  koku/reporting/migrations/0013_auto_20181107_1956.py
  koku/reporting/provider/ocp/models.py
Labels: enhancement

#448 OCP Price List model additions
  koku/api/report/ocp/ocp_query_handler.py
  koku/api/report/queries.py
  koku/reporting/migrations/0014_auto_20181108_0207.py
  koku/reporting/provider/ocp/models.py
Labels: enhancement

#453 Add coalesce mechanism to account_alias to fallback to usage_account_id.
  koku/api/report/aws/aws_query_handler.py
Labels: ready to test

#452 This should allow for running tox with docker postgres
  scripts/create_test_db_user.sh
Labels: bug

#458 Handle others with matching rank.
  koku/api/report/aws/aws_query_handler.py
  koku/api/report/ocp/ocp_query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/tests_queries.py
Labels: ready to test

#460 Adding OCP total charge to memory and CPU end points
  koku/api/report/ocp/ocp_query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler_base.py
Labels: enhancement

#462 URL adjustments to align OCP and AWS end points
  docs/source/specs/openapi.yml
  docs/source/users.rst
  koku/api/report/aws/view.py
  koku/api/urls.py
  scripts/create_test_customer.py
Labels: enhancement

#467 create_test_customer.py adding OCP
  scripts/create_test_customer.py
  scripts/test_customer.yaml
Labels: enhancement

#464 Removing AWS-local directory check when adding provider
  koku/providers/aws_local/aws_local_provider.py
  koku/providers/test/aws_local/test_aws_local_provider.py
  openshift/init-app.sh
  openshift/koku-template.yaml
Labels: enhancement

#480 removing provider rates upon provider removal.
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
Labels: bug

#481 Limit schema update
  koku/api/report/queries.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/reporting/migrations/0017_auto_20181121_1444.py
  koku/reporting/provider/ocp/models.py
  koku/reporting_common/data/ocp_report_column_map.json
  koku/reporting_common/migrations/0005_auto_20181127_2046.py
Labels: bug

#495 Ocp units
  koku/api/report/ocp/ocp_query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/tests_views.py
Labels: bug
