Repository project-koku/koku, pull requests merged in 2018-10, with the labels that each got.

#397 Remove dependency on AWS organizations.
  docs/source/aws_provider.rst
  koku/api/report/test/tests_queries.py
  koku/providers/aws/aws_provider.py
  koku/providers/test/aws/tests_aws_provider.py
Labels: ready to test

#402 Allow case insensitive filtering on account_alias, service, region, avail_zone.
  koku/api/iam/test/iam_test_case.py
  koku/api/report/queries.py
  koku/api/report/test/tests_queries.py
  koku/koku/dev_middleware.py
  koku/koku/middleware.py
  koku/koku/tests_middleware.py
Labels: enhancement

#401 OCP schema updates
  koku/reporting/migrations/0004_auto_20181003_1633.py
  koku/reporting/models.py
  koku/reporting_common/data/ocp_report_column_map.json
Labels: enhancement

#406 Fix account_alias issue and pin pip to 18.0
  koku/api/report/queries.py
  koku/api/report/test/tests_queries.py
  openshift/s2i/bin/assemble
  tox.ini
Labels: ready to test

#411 Prevent pip upgrade
  Pipfile.lock
  openshift/koku-template.yaml
  openshift/s2i/bin/assemble
Labels: configuration

#420 Update tests to create tenant + schema only when necessary
  koku/api/iam/test/iam_test_case.py
  koku/api/iam/test/tests_user_preference_view.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_serializers.py
  koku/api/provider/test/tests_views.py
  koku/api/report/test/tests_queries.py
  koku/api/report/test/tests_views.py
  koku/providers/test/aws/tests_aws_provider.py
  koku/providers/test/aws_local/test_aws_local_provider.py
Labels: enhancement

#423 Bugfix aws bill uniqueness
  koku/api/migrations/0004_auto_20181012_1507.py
  koku/api/provider/models.py
  koku/api/provider/serializers.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_views.py
  koku/api/report/test/tests_queries.py
  koku/reporting/migrations/0008_auto_20181012_1724.py
  koku/reporting/models.py
Labels: bug

#427 Alter precision, scale on summary OCP tables
  koku/reporting/migrations/0010_auto_20181017_1659.py
  koku/reporting/models.py
Labels: bug

#430 Get the OCP summary tables aligned with API reqs
  koku/reporting/migrations/0011_auto_20181018_1811.py
  koku/reporting/models.py
Labels: enhancement

#436 Breaking up AWS API logic to prepare for code reuse with OCP
  koku/api/report/aws/__init__.py
  koku/api/report/aws/serializers.py
  koku/api/report/aws/view.py
  koku/api/report/queries.py
  koku/api/report/query_filter.py
  koku/api/report/serializers.py
  koku/api/report/test/tests_queries.py
  koku/api/report/test/tests_serializers.py
  koku/api/report/test/tests_views.py
  koku/api/report/view.py
  koku/api/views.py
Labels: enhancement
