Repository project-koku/koku, pull requests merged in 2019-11, with the labels that each got.

#1318 Azure account updates to ReadTheDocs
  docs/source/providers.rst
  docs/source/providers/azure.rst
Labels: Koku'(x), enhancement

#1319 Fetching Sources imported field for OCP cluster ID if available.
  koku/sources/kafka_listener.py
  koku/sources/test/test_kafka_listener.py
  scripts/create_sources.py
Labels: enhancement

#1323 Part 2 of Downloader bugfix for #1267
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/test/external/downloader/test_report_downloader_base.py
Labels: bug

#1351 Suspend provider operations while in misconfigured state
  koku/api/migrations/0034_provider_active.py
  koku/api/provider/models.py
  koku/api/provider/serializers.py
  koku/api/provider/test/tests_serializers.py
  koku/api/provider/test/tests_views.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/__init__.py
  koku/masu/test/external/accounts/db/test_cur_accounts_db.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/providers/aws/provider.py
  koku/providers/aws_local/provider.py
  koku/providers/ocp/provider.py
Labels: enhancement

#1355 Push cost management application status to platform on create/edit
  docs/source/specs/openapi.json
  koku/sources/kafka_listener.py
  koku/sources/koku_http_client.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_koku_http_client.py
Labels: enhancement

#1345 part 1 of downloader retry bugfix (#1267)
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/aws_local/aws_local_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure_local/azure_local_report_downloader.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/download.py
  koku/masu/processor/tasks.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/aws_local/test_aws_local_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/azure_local/test_azure_local_report_downloader.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/external/downloader/test_report_downloader_base.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting_common/migrations/0023_costusagereportmanifest_task.py
  koku/reporting_common/models.py
Labels: Koku'(x), bug

#1361 Catch all message processing and provider sync exceptions in sources client
  koku/sources/kafka_listener.py
Labels: enhancement

#1364 Sources Client handle kafka restarts
  koku/sources/kafka_listener.py
Labels: enhancement

#1363 IQE helper updates
  .gitignore
  Makefile
  testing/local_providers/aws_local_5/.gitkeep
  testing/run_test.sh
  testing/run_vortex_api_tests.sh
Labels: enhancement

#1380 Simply temporary file delete logic
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/processor/aws/aws_report_processor.py
  koku/masu/processor/azure/azure_report_processor.py
  koku/masu/processor/gcp/gcp_report_processor.py
  koku/masu/processor/ocp/ocp_report_processor.py
  koku/masu/processor/report_processor_base.py
  koku/masu/test/processor/aws/test_aws_report_processor.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/masu/test/processor/gcp/test_gcp_report_processor.py
  koku/masu/test/processor/ocp/test_ocp_report_processor.py
  koku/masu/util/common.py
Labels: bug

#1377 Use the correct column name for Azure filtering
  koku/masu/processor/report_processor_base.py
  koku/masu/test/processor/aws/test_aws_report_processor.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
Labels: azure, bug

#1381 compose update for testing
  docker-compose.yml
Labels: configuration

#1375 Updating source_status API to conform with Platform Sources application status API
  koku/providers/azure/provider.py
  koku/providers/provider_access.py
  koku/providers/test/tests_provider_access.py
  koku/sources/api/source_status.py
  koku/sources/test/api/test_source_status.py
Labels: enhancement

#1384 Minor groovy fix for v3 support (#1383)
  Jenkinsfile-smoke.groovy
Labels: stable

#1389 updating sources api error responses
  .gitignore
  koku/api/sources/authentication.py
  koku/api/sources/billing_source.py
  koku/api/sources/test/test_authentication.py
  koku/api/sources/test/test_billing_source.py
Labels: enhancement

#1386 Preliminary e2e deploy script
  scripts/e2e-deploy.sh
  scripts/e2e-secrets.yml
Labels: deployment

#1402 Use a single worker process
  koku/koku/settings.py
Labels: configuration

#1412 Delete stale manifest files (#1410)
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/aws_local/aws_local_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure_local/azure_local_report_downloader.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
Labels: release, stable

#1413 bugfix for db metrics (#1071)
  koku/koku/metrics.py
  koku/koku/tests_metrics.py
Labels: bug

#1430 Ensure there is a 1-1 relationship with sources and providers
  koku/api/migrations/0037_auto_20191120_1538.py
  koku/api/provider/models.py
  koku/api/provider/serializers.py
  koku/api/provider/test/tests_serializers.py
Labels: bug

#1432 Use sources UUID on provider UUID when creating new sources
  koku/api/migrations/0038_sources_source_uuid.py
  koku/api/provider/models.py
  koku/api/provider/serializers.py
  koku/sources/kafka_listener.py
  koku/sources/koku_http_client.py
  koku/sources/storage.py
  koku/sources/test/api/test_billing_source.py
  koku/sources/test/test_koku_http_client.py
  koku/sources/test/test_storage.py
Labels: enhancement

#1426 shift over to ubi7 image
  docs/source/openshift.rst
  openshift/celery-flower.yaml
  openshift/imagestream.yaml
  openshift/koku.yaml
  scripts/e2e-deploy.sh
Labels: production-ready

#1444 migrate rabbitmq to ubi7
  openshift/buildenv/rabbitmq/Dockerfile
  openshift/buildenv/rabbitmq/docker-entrypoint.sh
  openshift/rabbitmq.yaml
Labels: production-ready

#1448 UBI7/RHEL7 changes
  docs/source/openshift.rst
  docs/source/specs/openapi.json
  koku-manifest
  koku/api/metrics/data/cost_models_metric_map.json
  koku/api/metrics/models.py
  koku/api/migrations/0039_auto_20191121_2154.py
  koku/api/migrations/0040_auto_20191121_2154.py
  koku/api/provider/provider_manager.py
  koku/api/provider/test/tests_views.py
  koku/api/provider/view.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/test/aws/tests_queries.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/tests_views.py
  koku/gunicorn.py
  koku/masu/database/cost_model_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/ocp/ocp_report_charge_updater.py
  koku/masu/test/database/test_cost_model_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
  koku/reporting/migrations/0086_auto_20191120_1615.py
  koku/reporting/provider/ocp/costs/models.py
  koku/reporting/provider/ocp/models.py
  openshift/buildenv/rabbitmq/Dockerfile
  openshift/buildenv/rabbitmq/docker-entrypoint.sh
  openshift/celery-flower.yaml
  openshift/imagestream.yaml
  openshift/koku.yaml
  openshift/rabbitmq.yaml
  scripts/create_manifest.py
  scripts/e2e-deploy.sh
Labels: production-ready, stable
