Repository project-koku/koku, pull requests merged in 2019-12, with the labels that each got.

#1456 add docs and update smoke testing scripts
  docs/source/development.rst
  docs/source/testing.rst
  testing/conf/settings.local.yaml
  testing/run_smoke_tests.sh
  testing/run_test.sh
Labels: developer productivity, documentation

#1479 Fix infra map SQL for OCP on AWS
  koku/masu/database/sql/reporting_ocpinfrastructure_provider_map.sql
Labels: bug

#1494 adding celery timeout for when broker is unavailable
  koku/koku/celery.py
Labels: configuration

#1481 Consolidate Sources APIs and enable PATCH
  docs/source/specs/openapi.json
  koku/api/iam/test/iam_test_case.py
  koku/api/migrations/0041_sources_account_id.py
  koku/api/provider/models.py
  koku/api/sources/test/test_view.py
  koku/api/sources/view.py
  koku/api/urls.py
  koku/api/views.py
  koku/koku/middleware.py
  koku/sources/api/serializers.py
  koku/sources/api/source_status.py
  koku/sources/api/urls.py
  koku/sources/api/view.py
  koku/sources/api/views.py
  koku/sources/openapi.json
  koku/sources/storage.py
  koku/sources/test/api/test_serializers.py
  koku/sources/test/api/test_view.py
  koku/sources/test/test_storage.py
  scripts/create_sources.py
Labels: enhancement

#1529 Enqueue separate celery task for each month of data
  README.rst
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/_tasks/download.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/processor/test_tasks.py
Labels: enhancement

#1545 Support POST source-status endpoint for asynchronously pushing source status
  koku/sources/api/source_status.py
  koku/sources/api/view.py
  koku/sources/openapi.json
  koku/sources/test/api/test_source_status.py
  koku/sources/test/api/test_view.py
Labels: enhancement
