Repository project-koku/koku, pull requests merged in 2019-05, with the labels that each got.

#845 RBAC rate controls
  docker-compose.yml
  koku/api/common/permissions/rates_access.py
  koku/api/common/permissions/test/tests_rates_access.py
  koku/rates/test/tests_view.py
  koku/rates/view.py
Labels: enhancement

#846 Implement order-by tag, fixes #714
  koku/api/report/aws/serializers.py
  koku/api/report/ocp/serializers.py
  koku/api/report/ocp_aws/serializers.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/helpers.py
  koku/api/report/test/ocp_aws/tests_serializers.py
  koku/api/report/test/ocp_aws/tests_views.py
  koku/api/report/test/tests_serializers.py
  koku/api/report/view.py
Labels: enhancement

#862 OpenShift config changes to triage QE failures
  koku/gunicorn.py
  openshift/koku-template.yaml
Labels: configuration

#861 add ProviderStatus model
  Pipfile
  Pipfile.lock
  koku/api/migrations/0009_providerstatus.py
  koku/api/provider/models.py
Labels: enhancement

#879 querying all OpenShift label summary tables for report query by tags
  koku/api/report/view.py
Labels: bug
