Repository project-koku/koku, pull requests merged in 2019-09, with the labels that each got.

#1064 Fix report_data API with empty AWS provider
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/reporting_awscostentrylineitem_daily.sql
  koku/masu/database/sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/test/database/test_aws_report_db_accessor.py
  tox.ini
Labels: bug

#1066 Azure Local Download/Processing
  docker-compose.yml
  koku/api/provider/provider_manager.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure_local/__init__.py
  koku/masu/external/downloader/azure_local/azure_local_report_downloader.py
  koku/masu/external/report_downloader.py
  koku/masu/test/external/downloader/azure_local/__init__.py
  koku/masu/test/external/downloader/azure_local/test_azure_local_report_downloader.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/util/azure/common.py
Labels: azure, enhancement

#1075 Get scheduler working
  koku/api/apps.py
  openshift/celery-scheduler.yaml
Labels: bug, deployment

#1080 Add Azure serializers
  koku/api/report/azure/__init__.py
  koku/api/report/azure/serializers.py
  koku/api/report/test/azure/__init__.py
  koku/api/report/test/azure/tests_serializers.py
  koku/api/tags/azure/__init__.py
  koku/api/tags/test/azure/__init__.py
Labels: azure

#1087 add Azure query handler & data generator
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/azure/serializers.py
  koku/api/report/test/azure/helpers.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/api/report/test/azure/tests_serializers.py
Labels: azure

#1089 add Azure Tag Query Handler
  koku/api/report/azure/provider_map.py
  koku/api/report/test/azure/helpers.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/api/tags/azure/queries.py
  koku/api/tags/queries.py
  koku/api/tags/serializers.py
  koku/api/tags/test/azure/tests_azure_tag_query_handler.py
  koku/reporting/models.py
Labels: azure

#1093 Fix cost models check fields to exclude pagination params
  koku/cost_models/view.py
Labels: bug

#1109 Bugfix provider billing source empty string
  koku/api/migrations/0019_auto_20190912_1853.py
  koku/api/provider/models.py
  koku/api/provider/serializers.py
  koku/api/provider/test/tests_serializers.py
Labels: bug

#1099 Add azure views.
  docs/source/specs/openapi.json
  koku/api/common/permissions/azure_access.py
  koku/api/common/permissions/test/tests_azure_access.py
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/azure/serializers.py
  koku/api/report/azure/view.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/api/report/test/azure/tests_serializers.py
  koku/api/report/test/azure/tests_views.py
  koku/api/report/view.py
  koku/api/tags/azure/queries.py
  koku/api/tags/azure/view.py
  koku/api/tags/test/azure/tests_view.py
  koku/api/urls.py
  koku/api/views.py
Labels: azure

#1119 Allowing koku provider and platform-sources to run simultaneously
  koku/api/provider/provider_manager.py
  koku/api/provider/serializers.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_serializers.py
  koku/api/provider/view.py
  koku/sources/koku_http_client.py
  koku/sources/test/test_koku_http_client.py
Labels: enhancement

#1128 finish implementing RBAC for Azure.
  koku/api/common/permissions/azure_access.py
  koku/api/common/permissions/test/tests_azure_access.py
  koku/api/query_handler.py
  koku/api/report/access_utils.py
  koku/api/report/azure/query_handler.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/api/report/test/tests_access_utils.py
  koku/koku/rbac.py
  koku/koku/tests_rbac.py
Labels: azure

#1127 Platform-Sources Integration OpenShift template
  Makefile
  koku/sources/api/status.py
  koku/sources/api/urls.py
  koku/sources/config.py
  koku/sources/test/api/test_status.py
  openshift/configmap.yaml
  openshift/parameters/examples/configmap.env.example
  openshift/parameters/examples/sources.env.example
  openshift/sources.yaml
Labels: enhancement

#1121 document that masu can be triggered by /download endpoint
  docs/source/install.rst
Labels: documentation

#1130 Updated imagestream references
  openshift/imagestream.yaml
Labels: deployment

#1147 Azure Downloader: Support multiple exports in a subscription
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
Labels: azure, enhancement

#1159 Update README for pgAdmin
  README.rst
Labels: documentation

#1155 Adding plumbing for Azure Units
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/masu/database/sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/reporting/migrations/0069_auto_20190925_1327.py
  koku/reporting/provider/azure/models.py
  koku/reporting_common/data/azure_report_column_map.json
  koku/reporting_common/migrations/0018_auto_20190923_1838.py
Labels: azure, enhancement

#1166 auth_header to textfield for sources model
  koku/api/migrations/0024_auto_20190925_1914.py
  koku/api/provider/models.py
Labels: bug

#1171 sources integration debug
  koku/sources/api/status.py
  koku/sources/kafka_listener.py
  koku/sources/sources_http_client.py
  koku/sources/test/api/test_status.py
  koku/sources/test/test_sources_http_client.py
Labels: enhancement

#1173 looking up source type name based on id
  koku/sources/kafka_listener.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_sources_http_client.py
  scripts/create_sources.py
Labels: bug

#1163 catch missing parameters in Azure creds, fixes #1136
  koku/api/provider/serializers.py
  koku/api/provider/test/tests_serializers.py
Labels: azure

#1172 clean up ReportView hierarchy; set class parameters
  koku/api/report/aws/view.py
  koku/api/report/azure/view.py
  koku/api/report/ocp/view.py
  koku/api/report/ocp_aws/view.py
  koku/api/report/test/azure/tests_views.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/tests_views.py
  koku/api/report/view.py
  koku/api/tags/aws/view.py
  koku/api/tags/azure/view.py
  koku/api/tags/ocp/view.py
  koku/api/tags/ocp_aws/view.py
  koku/api/tags/view.py
  koku/api/views.py
  tox.ini
Labels: tech-debt

#1176 Sources azure auth store fix
  koku/sources/sources_http_client.py
  koku/sources/test/test_kafka_listener.py
  scripts/create_sources.py
Labels: bug

#1177 updating sources group id
  koku/sources/kafka_listener.py
Labels: configuration
