Repository project-koku/koku, pull requests merged in 2019-10, with the labels that each got.

#1190 Moving processing temp directories to be on PVC mount
  docker-compose.yml
  koku/masu/config.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/_tasks/download.py
  koku/masu/processor/ocp/ocp_report_processor.py
  koku/masu/test/api/test_expired_data.py
  koku/masu/test/api/test_status.py
  koku/masu/test/processor/aws/test_aws_report_processor.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/masu/test/processor/ocp/test_ocp_report_processor.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/util/common.py
Labels: bug

#1196 Handle Authentication.create messages from Platform Sources
  koku/api/migrations/0025_sources_endpoint_id.py
  koku/api/provider/models.py
  koku/sources/kafka_listener.py
  koku/sources/sources_http_client.py
  koku/sources/storage.py
  koku/sources/test/api/test_billing_source.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_sources_http_client.py
  koku/sources/test/test_storage.py
  scripts/create_sources.py
Labels: bug

#1202 Add conflict columns to Azure report processing to avoid double processing
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/azure/azure_report_processor.py
  koku/masu/test/data/azure/costreport_a243c6f2-199f-4074-9a2c-40e671cf1584.csv
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/reporting/migrations/0070_auto_20191002_1720.py
  koku/reporting/provider/azure/models.py
Labels: azure, bug

#1210 Support source_name on Sources Client Service
  koku/sources/api/authentication.py
  koku/sources/api/billing_source.py
  koku/sources/storage.py
  koku/sources/test/api/test_authentication.py
  koku/sources/test/api/test_billing_source.py
  koku/sources/test/test_storage.py
  scripts/create_sources.py
Labels: enhancement

#1229 handling EOFError in listener
  koku/masu/external/kafka_msg_handler.py
Labels: bug

#1236 Sources Client HTTP error message include only status code
  koku/sources/koku_http_client.py
Labels: bug

#1249 Scripts to help run QE tests with docker-compose deployments
  .gitignore
  Makefile
  README.rst
  docker-compose.yml
  koku/masu/config.py
  testing/conf/settings.local.yaml
  testing/local_providers/aws_local/.gitkeep
  testing/local_providers/aws_local_0/.gitkeep
  testing/local_providers/aws_local_1/.gitkeep
  testing/local_providers/aws_local_2/.gitkeep
  testing/local_providers/aws_local_3/.gitkeep
  testing/local_providers/aws_local_4/.gitkeep
  testing/local_providers/azure_local/.gitkeep
  testing/local_providers/insights_local/.gitkeep
  testing/pvc_dir/.gitkeep
  testing/run_api_tests.sh
  testing/run_smoke_tests.sh
  testing/run_test.sh
Labels: enhancement

#1251 Allow long AWS product names
  koku/reporting/migrations/0072_auto_20191011_1735.py
  koku/reporting/provider/aws/models.py
Labels: bug

#1248 Removing temp files only after initial ingest is complete
  koku/masu/processor/_tasks/process.py
  koku/masu/test/processor/test_tasks.py
Labels: bug

#1246 Fix rabbitmq buildConfigs
  openshift/buildenv/rabbitmq/Dockerfile
  openshift/buildenv/rabbitmq/rabbitmq.asc
  openshift/rabbitmq.yaml
Labels: configuration

#1234 QueryHandler initialization refactor
  koku/api/provider/view.py
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/api/report/access_utils.py
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/aws/view.py
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/azure/view.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/ocp/view.py
  koku/api/report/ocp_aws/provider_map.py
  koku/api/report/ocp_aws/query_handler.py
  koku/api/report/ocp_aws/view.py
  koku/api/report/queries.py
  koku/api/report/test/__init__.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/api/report/test/azure/tests_views.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/test_ocp_aws_query_handler.py
  koku/api/report/test/tests_access_utils.py
  koku/api/report/test/tests_queries.py
  koku/api/report/test/tests_views.py
  koku/api/report/view.py
  koku/api/tags/aws/queries.py
  koku/api/tags/aws/view.py
  koku/api/tags/azure/queries.py
  koku/api/tags/azure/view.py
  koku/api/tags/ocp/queries.py
  koku/api/tags/ocp/view.py
  koku/api/tags/ocp_aws/queries.py
  koku/api/tags/ocp_aws/view.py
  koku/api/tags/queries.py
  koku/api/tags/test/aws/test_aws_tag_query_handler.py
  koku/api/tags/test/azure/tests_azure_tag_query_handler.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
  koku/api/tags/test/ocp_aws/tests_queries.py
  koku/api/tests_query_params.py
Labels: tech-debt

#1280 No longer use conflict columns to upsert Azure data
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/processor/aws/aws_report_processor.py
  koku/masu/processor/azure/azure_report_processor.py
  koku/masu/processor/ocp/ocp_report_processor.py
  koku/masu/processor/report_processor_base.py
  koku/masu/test/processor/aws/test_aws_report_processor.py
  koku/reporting/migrations/0073_auto_20191017_1629.py
  koku/reporting/provider/azure/models.py
Labels: bug

#1298 Updating IQE helper configuration file with latest hccm-plugin changes
  testing/conf/settings.local.yaml
  testing/run_test.sh
Labels: configuration

#1304 Correcting the ProviderMap parameters for group_by/filter projects
  koku/api/report/ocp/query_handler.py
  koku/api/report/ocp_aws/query_handler.py
Labels: bug

#1308 set permissions on /var/lib/rabbitmq
  openshift/buildenv/rabbitmq/Dockerfile
Labels: configuration

#1331 Add conflict column for azure meter insert
  koku/masu/processor/azure/azure_report_processor.py
Labels: Koku'(x), azure, bug
