Repository project-koku/koku, pull requests merged in 2019-03, with the labels that each got.

#708 Support filter and group_by AWS product_family
  koku/api/report/aws/serializers.py
  koku/api/report/queries.py
Labels: enhancement

#718 Remove duplicate tag keys
  koku/api/report/test/ocp/tests_views.py
  koku/api/tags/queries.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
Labels: bug

#722 Update test data to go for 11 days for new -10 assumption in APIs
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/helpers.py
Labels: bug

#726 Partial revert of OpenShift charges PR
  koku/api/report/queries.py
  koku/api/report/test/ocp/tests_views.py
Labels: bug

#727 Get tests working for today, will break tomorrow.
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/helpers.py
  koku/api/report/test/ocp_aws/tests_views.py
Labels: bug

#744 Test fix rounding errors
  koku/api/report/queries.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/tests_views.py
  koku/api/report/test/tests_queries.py
  koku/reporting/migrations/0050_auto_20190315_1339.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/ocp_aws/models.py
Labels: tech-debt

#754 Adding infrastructure field to provider response
  docs/source/specs/openapi.json
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_views.py
  koku/api/provider/view.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/helpers.py
  koku/api/report/test/tests_queries.py
  koku/providers/aws/aws_provider.py
  koku/providers/aws_local/aws_local_provider.py
  koku/providers/ocp/ocp_provider.py
  koku/providers/ocp_local/ocp_local_provider.py
  koku/providers/provider_access.py
  koku/providers/provider_interface.py
  koku/providers/test/tests_provider_access.py
Labels: enhancement

#761 Re-apply PR 754 infrastructure field in provider response
  docs/source/specs/openapi.json
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_views.py
  koku/api/provider/view.py
  koku/api/report/test/ocp/helpers.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/helpers.py
  koku/api/report/test/tests_queries.py
  koku/providers/aws/aws_provider.py
  koku/providers/aws_local/aws_local_provider.py
  koku/providers/ocp/ocp_provider.py
  koku/providers/ocp_local/ocp_local_provider.py
  koku/providers/provider_access.py
  koku/providers/provider_interface.py
  koku/providers/test/tests_provider_access.py
Labels: enhancement

#763 cluster_alias annotation doesn't blow up when group by cluster
  koku/api/query_handler.py
  koku/api/report/test/ocp/tests_views.py
Labels: bug

#764 OpenShift report filter by infrastructures=aws
  docs/source/specs/openapi.json
  koku/api/provider/view.py
  koku/api/query_filter.py
  koku/api/report/ocp/serializers.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/tests_serializers.py
  koku/providers/aws/aws_provider.py
  koku/providers/ocp/ocp_provider.py
  koku/providers/provider_access.py
  koku/providers/provider_interface.py
  koku/providers/test/tests_provider_access.py
Labels: enhancement

#769 Use the month field, not hours for volume deltas
  koku/api/report/queries.py
Labels: bug
