Repository project-koku/koku, pull requests merged in 2019-04, with the labels that each got.

#785 Its the first of the month
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/ocp_aws/tests_views.py
Labels: bug

#784 Fixing OpenShift on AWS queries when filtering by project
  koku/api/report/ocp_aws/ocp_aws_query_handler.py
Labels: bug

#788 Display default filter parameters in API response
  koku/api/query_handler.py
  koku/api/report/test/tests_queries.py
Labels: enhancement

#792 docker-compose updates for rbac service
  docker-compose.yml
Labels: enhancement

#802 Select correct annotation for OCP cost so group_by and filter totals match
  Makefile
  koku/api/report/ocp/ocp_query_handler.py
  tox.ini
Labels: bug

#801 RBAC caching
  Pipfile
  Pipfile.lock
  docker-compose.yml
  koku/api/iam/test/iam_test_case.py
  koku/koku/middleware.py
  koku/koku/rbac.py
  koku/koku/settings.py
  koku/koku/tests_middleware.py
  openshift/koku-template.yaml
Labels: enhancement

#808 adding redis.conf for OpenShift
  openshift/koku-template.yaml
Labels: configuration

#810 adding product_family to ocp_aws filter and group mapper
  koku/api/report/queries.py
Labels: bug

#814 Converting OCP cost view to table
  koku/api/report/test/ocp/helpers.py
  koku/reporting/migrations/0053_auto_20190412_1529.py
  koku/reporting/migrations/0054_delete_ocpawscostlineitemdaily.py
  koku/reporting/provider/ocp/costs/models.py
Labels: configuration

#817 Update rates API response to be more user friendly
  docs/source/specs/openapi.json
  koku/rates/serializers.py
  koku/rates/test/tests_serializers.py
  koku/rates/test/tests_view.py
  koku/rates/view.py
Labels: enhancement

#829 Support OpenShift one-to-many rates to clusters
  docker-compose.yml
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/rates/migrations/0005_auto_20190422_1415.py
  koku/rates/models.py
  koku/rates/rate_manager.py
  koku/rates/serializers.py
  koku/rates/test/test_rate_manager.py
  koku/rates/test/tests_serializers.py
  koku/rates/test/tests_view.py
  koku/rates/view.py
Labels: enhancement

#842 Update ocp aws project summary model
  koku/api/report/queries.py
  koku/api/report/test/ocp_aws/helpers.py
  koku/reporting/migrations/0060_auto_20190430_1926.py
  koku/reporting/provider/ocp_aws/models.py
Labels: bug
