Repository project-koku/koku, pull requests merged in 2019-08, with the labels that each got.

#961 split ProviderMap away from QueryHandler; fixes #938
  koku/api/query_handler.py
  koku/api/report/aws/aws_query_handler.py
  koku/api/report/aws/provider_map.py
  koku/api/report/ocp/ocp_query_handler.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp_aws/ocp_aws_query_handler.py
  koku/api/report/ocp_aws/provider_map.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/test/ocp_aws/tests_views.py
  koku/api/report/test/tests_queries.py
  koku/api/tags/queries.py
  koku/masu/__init__.py
Labels: tech-debt-high

#978 Model changes required for Azure
  Makefile
  koku/api/migrations/0013_auto_20190812_1815.py
  koku/api/provider/models.py
  koku/api/provider/serializers.py
  koku/api/provider/test/tests_serializers.py
  koku/cost_models/migrations/0008_auto_20190812_1805.py
  koku/reporting_common/migrations/0012_auto_20190812_1805.py
Labels: azure

#995 Migrationless test runner
  koku/api/iam/test/iam_test_case.py
  koku/api/iam/test/tests_serializers.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_serializers.py
  koku/api/provider/test/tests_views.py
  koku/koku/koku_test_runner.py
  koku/koku/settings.py
  koku/koku/tests_middleware.py
Labels: tech-debt

#992 Pip pipenv fixes
  Pipfile
  Pipfile.lock
  README.rst
  koku/koku/metrics.py
  koku/koku/tests_metrics.py
  openshift/buildenv/koku/s2i/bin/assemble
  tox.ini
Labels: documentation, enhancement

#997 Forgot masu in container name
  openshift/masu.yaml
Labels: bug, deployment

#993 initial Azure Provider implementation.
  Pipfile
  Pipfile.lock
  docs/source/specs/openapi.json
  koku/api/migrations/0013_auto_20190812_1815.py
  koku/api/provider/models.py
  koku/api/provider/view.py
  koku/koku/koku_test_runner.py
  koku/koku/metrics.py
  koku/providers/azure/__init__.py
  koku/providers/azure/client.py
  koku/providers/azure/provider.py
  koku/providers/provider_access.py
  koku/providers/test/azure/__init__.py
  koku/providers/test/azure/tests_client.py
  koku/providers/test/azure/tests_provider.py
  scripts/create_test_customer.py
  scripts/test_customer.yaml
Labels: azure

#1008 Let's run tests in parallel
  .gitignore
  Makefile
  koku/koku/koku_test_runner.py
  tox.ini
Labels: enhancement, tech-debt

#1014 Azure Report Downloader
  Pipfile
  Pipfile.lock
  koku/api/provider/provider_manager.py
  koku/masu/external/__init__.py
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/external/downloader/azure/__init__.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/download.py
  koku/masu/processor/azure/__init__.py
  koku/masu/processor/azure/azure_report_charge_updater.py
  koku/masu/processor/azure/azure_report_db_cleaner.py
  koku/masu/processor/azure/azure_report_processor.py
  koku/masu/processor/azure/azure_report_summary_updater.py
  koku/masu/processor/expired_data_remover.py
  koku/masu/processor/report_charge_updater.py
  koku/masu/processor/report_processor.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/test/__init__.py
  koku/masu/test/external/accounts/db/test_cur_accounts_db.py
  koku/masu/test/external/downloader/azure/__init__.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
  koku/masu/test/external/test_accounts_accessor.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/test/processor/azure/__init__.py
  koku/masu/test/processor/azure/test_azure_report_charge_updater.py
  koku/masu/test/processor/azure/test_azure_report_db_cleaner.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/masu/test/processor/azure/test_azure_report_summary_updater.py
  koku/masu/test/processor/test_expired_data_remover.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/processor/test_report_charge_updater.py
  koku/masu/test/processor/test_report_processor.py
  koku/masu/test/processor/test_report_summary_updater.py
  koku/masu/util/azure/__init__.py
  koku/masu/util/azure/common.py
  koku/masu/util/common.py
  koku/providers/azure/client.py
  koku/providers/test/azure/tests_client.py
Labels: enhancement

#1016 Update to use an IMAGE variable for statefulsets
  Makefile
  openshift/celery-worker.yaml
  openshift/masu-listener.yaml
  openshift/parameters/examples/celery-worker.env.example
  openshift/parameters/examples/masu-listener.env.example
Labels: deployment, enhancement

#1022 Set primary tox mode to serial, add parallel opt
  tox.ini
Labels: bug

#1070 Mount the ssl cert on the scheduler
  openshift/celery-scheduler.yaml
Labels: bug, configuration

#1073 Azure product model rework
  koku/masu/database/__init__.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/processor/azure/azure_report_processor.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/processor/azure/test_azure_report_charge_updater.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/masu/test/processor/azure/test_azure_report_summary_updater.py
  koku/reporting/migrations/0064_auto_20190830_1353.py
  koku/reporting/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting_common/data/azure_report_column_map.json
  koku/reporting_common/migrations/0016_auto_20190829_2053.py
Labels: azure

#1074 adding instance_id information to summary
  koku/masu/database/sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/reporting/migrations/0065_auto_20190830_1606.py
  koku/reporting/provider/azure/models.py
Labels: azure
