Repository project-koku/koku, pull requests merged in 2020-03, with the labels that each got.

#1844 Some test fixes.
  koku/api/report/test/ocp/tests_views.py
  koku/masu/test/processor/aws/test_aws_report_summary_updater.py
  koku/masu/test/processor/azure/test_azure_report_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_summary_updater.py
Labels: bug

#1837 Updated grafana config db for smaller query intervals
  README.rst
  grafana/Dockerfile-grafana
  grafana/grafana.db
  grafana/grafana.db.sql
Labels: Database, developer productivity

#1826 AWS Query Performance (with a dash of Azure)
  Makefile
  koku/api/migrations/0014_reload_azure_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/tests_queries.py
  koku/api/report/test/azure/helpers.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpcosts_summary.sql
  koku/masu/database/sql/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/processor/report_processor_base.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_report_summary_updater.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting/migrations/0100_aws_azure_query_perforance.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/ocp/models.py
  koku/reporting/provider/ocp_aws/models.py
  koku/reporting_common/data/azure_report_column_map.json
  scripts/check_for_koku_server.sh
  scripts/load_test_customer_data.sh
Labels: Database, aws, azure

#1879 Optimize docker-compose build
  docker-compose.yml
Labels: developer productivity

#1882 specifying base image name in docker-compose
  docker-compose.yml
Labels: configuration

#1926 configure dbstats to use prometheus pushgateway
  .env.example
  docker-compose.yml
  koku/koku/metrics.py
  koku/koku/settings.py
  koku/koku/tests_metrics.py
  scripts/e2e-secrets.yml
Labels: bug, production-ready

#1979 add curl timeout to migration script
  scripts/run_migrations.sh
Labels: configuration
