Repository project-koku/koku, pull requests merged in 2020-10, with the labels that each got.

#2434 Rc 2020.10.05
  Pipfile.lock
  docs/rtd_requirements.txt
  koku-manifest
  koku/api/provider/provider_builder.py
  koku/koku/koku_test_runner.py
  koku/reporting/migrations/0141_auto_20201002_1925.py
  koku/reporting/migrations/0142_auto_20201002_1925.py
  koku/reporting/provider/ocp/models.py
  koku/sources/test/test_kafka_source_manager.py
  scripts/create_manifest.py
Labels: release, stable

#2452 Cost 584 migration check upgrade
  db_functions/app_needs_migrations_func.sql
  koku/koku/database.py
  koku/koku/test_check_migrations_dbfunc.py
Labels: Database, deployment

#2463 Fix migration check to handle newly init'd database
  db_functions/app_needs_migrations_func.sql
Labels: Database, deployment

#2454 PoC for schema cloning for new tenant creation
  db_functions/clone_schema.sql
  koku/api/iam/models.py
  koku/api/iam/test/test_clone_schema.py
  koku/api/migrations/0031_clone_schema.py
  koku/koku/database.py
  koku/koku/migration_sql_helpers.py
  koku/koku/test_check_migrations_dbfunc.py
Labels: Database, Performance, enhancement, help wanted

#2471 Fedora docker .kube/config mount in container
  testing/run_test.sh
Labels: developer productivity

#2478 COST-663: Data from original parent in group_by of moved org unit.
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/tests_queries.py
Labels: bug
