Repository project-koku/koku, pull requests merged in 2020-04, with the labels that each got.

#1967 Ocp daily summary lose pod level granularity
  koku/api/report/ocp/serializers.py
  koku/masu/database/sql/reporting_ocpcosts_summary.sql
  koku/masu/database/sql/reporting_ocpstoragelineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/reporting/migrations/0109_remove_ocpusagelineitemdailysummary_pod.py
  koku/reporting/provider/ocp/models.py
Labels: Database, Performance, ocp

#2022 adding OCP_CLUSTER_MONTH to cost model constants
  koku/api/metrics/constants.py
Labels: bug

#2026 Ocp markup fix
  koku/masu/processor/ocp/ocp_cloud_summary_updater.py
Labels: bug

#2039 catch network issues when pushing to the pushgateway
  koku/koku/metrics.py
  koku/koku/tests_metrics.py
Labels: bug

#2041 Drop hard-coded schema reference
  koku/reporting/migrations/0106_ocpawscostsummary.py
  koku/reporting/migrations/0107_ocpazurecomputesummary_ocpazurecostsummary_ocpazurecostsummarybyaccount_ocpazurecostsummarybylocatio.py
Labels: Database, bug

#2042 Rc 2020.04.08
  koku/koku/metrics.py
  koku/koku/tests_metrics.py
  koku/reporting/migrations/0106_ocpawscostsummary.py
  koku/reporting/migrations/0107_ocpazurecomputesummary_ocpazurecostsummary_ocpazurecostsummarybyaccount_ocpazurecostsummarybylocatio.py
Labels: release, stable

#2054 Rc 2020.04.14
  docker-compose.yml
  docs/source/specs/openapi.json
  koku/koku/middleware.py
  koku/sources/api/serializers.py
  koku/sources/api/source_status.py
  koku/sources/api/view.py
  koku/sources/kafka_listener.py
  koku/sources/management/commands/sources.py
  koku/sources/tasks.py
  koku/sources/test/api/test_serializers.py
  koku/sources/test/api/test_view.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/urls.py
  openshift/sources.yaml
  run_sources.sh
Labels: release, stable

#2063 Rc 2020.04.15
  koku/koku/settings.py
  koku/providers/provider_access.py
  koku/providers/test/tests_provider_access.py
  koku/sources/kafka_listener.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_sources_http_client.py
Labels: release, stable

#2050 Summary table index performance
  koku/api/report/all/openshift/provider_map.py
  koku/api/report/aws/provider_map.py
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/provider_map.py
  koku/api/report/ocp_aws/provider_map.py
  koku/reporting/migrations/0110_summary_indexes.py
  koku/reporting/provider/all/openshift/models.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/reporting/provider/ocp_aws/models.py
Labels: Database

#2067 Fix typo in cost model serializer to display label_measurement_unit
  koku/cost_models/serializers.py
Labels: bug, price list

#2076 Use icontains for filter on location
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
Labels: Testing, bug

#2069 Slice values for tags API endpoint
  koku/api/tags/queries.py
  koku/api/tags/test/aws/test_aws_tag_query_handler.py
Labels: Performance, bug

#2080 Use contains for tag matching
  koku/masu/database/sql/reporting_ocpcosts_summary.sql
Labels: bug

#2079 Rc 2020.04.17
  koku/api/migrations/0020_sources_out_of_order_delete.py
  koku/api/provider/models.py
  koku/api/report/all/openshift/provider_map.py
  koku/api/report/aws/provider_map.py
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/provider_map.py
  koku/api/report/ocp_aws/provider_map.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/tags/queries.py
  koku/api/tags/test/aws/test_aws_tag_query_handler.py
  koku/cost_models/serializers.py
  koku/masu/database/sql/reporting_ocpcosts_summary.sql
  koku/masu/database/sql/reporting_ocpstoragelineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/reporting/migrations/0110_summary_indexes.py
  koku/reporting/migrations/0111_drop_azure_service_not_null.py
  koku/reporting/provider/all/openshift/models.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/reporting/provider/ocp_aws/models.py
  koku/sources/kafka_listener.py
  koku/sources/storage.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_storage.py
  scripts/load_test_customer_data.sh
Labels: release, stable

#2082 Fixing race conditions between source create and destroy
  koku/providers/provider_access.py
  koku/sources/api/serializers.py
  koku/sources/kafka_listener.py
  koku/sources/tasks.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_tasks.py
Labels: bug

#2086 Use the materialized view for deltas when possible
  koku/api/report/queries.py
Labels: Performance

#2099 Adjustment to allow for manual connection of provider and source
  koku/sources/tasks.py
Labels: bug

#2093 Support local providers in Sources Client
  koku/sources/kafka_listener.py
  koku/sources/storage.py
  koku/sources/test/test_kafka_listener.py
  scripts/create_sources.py
  testing/conf/settings.local.yaml
Labels: enhancement

#2095 Sources status cleanup
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
  koku/providers/aws/provider.py
  koku/providers/aws_local/provider.py
  koku/providers/azure/provider.py
  koku/providers/azure_local/provider.py
  koku/providers/provider_access.py
  koku/providers/provider_errors.py
  koku/providers/test/tests_provider_access.py
  koku/sources/api/source_status.py
  koku/sources/sources_error_message.py
  koku/sources/sources_http_client.py
  koku/sources/tasks.py
  koku/sources/test/api/test_source_status.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_sources_error_message.py
  koku/sources/test/test_tasks.py
Labels: enhancement

#2114 Rc 2020.04.30
  Makefile
  Pipfile
  Pipfile.lock
  docker-compose.yml
  docs/rtd_requirements.txt
  koku-manifest
  koku/masu/config.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
  koku/masu/test/external/downloader/test_report_downloader_base.py
  koku/masu/test/external/test_report_downloader.py
  koku/providers/aws/provider.py
  koku/providers/test/aws/tests_aws_provider.py
  koku/sources/api/status.py
  koku/sources/kafka_listener.py
  koku/sources/storage.py
  koku/sources/tasks.py
  koku/sources/test/api/test_status.py
  koku/sources/test/test_kafka_listener.py
  scripts/create_sources.py
  scripts/create_test_customer.py
  scripts/e2e-secrets.yml
  testing/conf/settings.local.yaml
Labels: release, stable
