Repository project-koku/koku, pull requests merged in 2020-11, with the labels that each got.

#2486 COST-659: Update tag rate serializer to only allow one metric per cost type
  koku/cost_models/serializers.py
  koku/cost_models/test/tests_serializers.py
  scripts/openshift_on_prem_cost_model.json
Labels: bug

#2483 Presto log delete trigger
  db_functions/presto_delete_trigger_func.sql
  koku/api/migrations/0032_presto_delete_log_trigger_func.py
  koku/koku/test_presto_delete_wrapper_trigger.py
  koku/reporting/migrations/0148_presto_delete_log.py
Labels: Database

#2491 COST-392 implement forecasting for AWS
  Pipfile
  Pipfile.lock
  docs/rtd_requirements.txt
  docs/source/specs/openapi.json
  koku-manifest
  koku/api/forecast/test/tests_views.py
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
  koku/koku/settings.py
Labels: enhancement

#2497 COST-720: Change cost model for tag rates to handle json format from UI
  koku/cost_models/serializers.py
  koku/cost_models/test/tests_serializers.py
  scripts/openshift_on_prem_cost_model.json
Labels: UI LGTM

#2503 COST-392 - implement forecasting for Azure
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
Labels: enhancement

#2428 COST-440 ocp summary presto
  Makefile
  db_functions/clone_schema.sql
  koku/api/iam/test/iam_test_case.py
  koku/koku/presto_database.py
  koku/koku/test_presto_db_utils.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/presto_sql/reporting_ocp_lineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocp_usage_label_summary.sql
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_parquet_processor_base.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_summary_updater.py
  koku/masu/util/common.py
  koku/masu/util/ocp/common.py
  koku/reporting/migrations/0148_presto_delete_log.py
  koku/reporting/migrations/0150_presto_bulk_pk_delete.py
  koku/reporting/migrations/0151_ocp_summary_table_presto_interface.py
Labels: Database, Performance, enhancement

#2511 COST-392 - implement forecasting for OCP
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
Labels: enhancement
