Repository project-koku/koku, pull requests merged in 2020-01, with the labels that each got.

#1570 Create AWS local development tips
  docs/source/aws.rst
Labels: Koku'(x)

#1578 DRY up an if/else into an if-or
  koku/masu/external/accounts_accessor.py
Labels: tech-debt

#1606 Added provider make targets for local dev and fix docs.
  Makefile
  docs/source/aws.rst
Labels: enhancement

#1625 Update testing.rst
  docs/source/testing.rst
Labels: documentation

#1593 make ProviderManager use new lookup table (see: #1466)
  koku/api/provider/models.py
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_models.py
  koku/api/provider/view.py
  koku/api/report/test/azure/openshift/helpers.py
  koku/api/report/test/ocp_aws/helpers.py
Labels: enhancement

#1645 1617 aws compute api cost incorrect
  koku/reporting/migrations/0091_aws_compute_cost_correction.py
Labels: Database, aws, bug
