Repository project-koku/koku, pull requests merged in 2020-05, with the labels that each got.

#2115 Allowing for OCP single manifest, multiple payloads
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/aws/test_aws_report_summary_updater.py
  koku/masu/test/processor/test_report_summary_updater.py
  koku/masu/test/processor/test_tasks.py
Labels: bug, enhancement

#2070 Tag summary by billing period
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/reporting_awstags_summary.sql
  koku/masu/database/sql/reporting_azuretags_summary.sql
  koku/masu/database/sql/reporting_ocpstoragevolumelabel_summary.sql
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
  koku/masu/processor/aws/aws_report_summary_updater.py
  koku/masu/processor/azure/azure_report_summary_updater.py
  koku/masu/processor/ocp/ocp_report_summary_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: Database, Performance

#2097 add RBAC classes to Tags endpoint
  koku/api/iam/test/iam_test_case.py
  koku/api/tags/all/openshift/view.py
  koku/api/tags/aws/view.py
  koku/api/tags/azure/openshift/view.py
  koku/api/tags/azure/view.py
  koku/api/tags/ocp/view.py
  koku/api/tags/ocp_aws/view.py
  koku/api/tags/view.py
Labels: bug, enhancement

#2126 Generate org_admin authorization header for source status pushes.
  koku/sources/api/source_status.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_sources_http_client.py
Labels: bug

#2128 Added secrets for dev db monitor user
  scripts/e2e-secrets.yml
Labels: Database

#2113 enable custom identity header (see: #2107)
  .env.example
  CONTRIBUTING.rst
  docs/source/development.rst
  docs/source/devtools.rst
  koku/koku/dev_middleware.py
  koku/koku/middleware.py
  koku/koku/settings.py
  koku/koku/tests_middleware.py
Labels: enhancement

#2130 Bugfix processed files check
  koku/masu/external/report_downloader.py
  koku/masu/test/external/test_report_downloader.py
Labels: bug

#2127 Use a GROUP BY instead of CTE for node labels
  koku/masu/database/sql/reporting_ocpstoragelineitem_daily.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily.sql
Labels: Database, Performance

#2131 add RbacPermissions decorator
  koku/api/iam/test/iam_test_case.py
  koku/api/report/test/tests_views.py
  koku/koku/dev_middleware.py
Labels: Testing, enhancement

#2136 Fix the development identity in the .env.example
  .env.example
Labels: bug, configuration

#2138 update default identity
  koku/koku/settings.py
Labels: bug

#2142 add some defensive coding for issues found by Sentry
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
  koku/sources/sources_error_message.py
Labels: bug

#2145 add django-extensions, remove drf-nested-routers
  .github/scripts/check_manifest.sh
  Pipfile
  Pipfile.lock
  docs/rtd_requirements.txt
  koku-manifest
  koku/koku/settings.py
Labels: enhancement

#2121 Improve Masu AWS report ingest logging clarity
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/processor/worker_cache.py
Labels: aws

#2168 Fix bugs with moving account & ou and filtering for organization endpoint.
  koku/api/organizations/queries.py
  koku/api/organizations/test/aws/test_views.py
  koku/api/organizations/test/test_views.py
  scripts/aws_org_tree.yml
Labels: bug
