Repository project-koku/koku, pull requests merged in 2020-09, with the labels that each got.

#2377 Rc 2020.09.02.02
  koku/reporting/migrations/0133_auto_20200901_2245.py
  koku/reporting/migrations/0135_auto_20200902_1808.py
Labels: release, stable

#2391 Rc 2020.09.09
  Makefile
  Pipfile
  Pipfile.lock
  deploy/metastore/hive-config/hive-site.xml
  docker-compose.yml
  docs/rtd_requirements.txt
  koku-manifest
  koku/api/common/permissions/resource_type_access.py
  koku/api/common/permissions/test/tests_resource_types_access.py
  koku/api/iam/models.py
  koku/api/migrations/0026_provider_data_updated_timestamp.py
  koku/api/migrations/0027_customer_date_updated.py
  koku/api/provider/models.py
  koku/api/provider/provider_manager.py
  koku/api/provider/serializers.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/provider/test/tests_serializers.py
  koku/api/report/test/utils.py
  koku/api/resource_types/__init__.py
  koku/api/resource_types/test/__init__.py
  koku/api/resource_types/test/tests_views.py
  koku/api/resource_types/view.py
  koku/api/urls.py
  koku/api/views.py
  koku/cost_models/cost_model_manager.py
  koku/cost_models/test/test_cost_model_manager.py
  koku/koku/middleware.py
  koku/koku/settings.py
  koku/masu/api/update_cost_model_costs.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/external/accounts/hierarchy/aws/aws_org_unit_crawler.py
  koku/masu/management/commands/check_migrations.py
  koku/masu/processor/aws/aws_report_parquet_processor.py
  koku/masu/processor/azure/azure_report_parquet_processor.py
  koku/masu/processor/ocp/ocp_report_parquet_processor.py
  koku/masu/processor/report_parquet_processor_base.py
  koku/masu/processor/tasks.py
  koku/masu/test/data/parquet_input.csv
  koku/masu/test/database/test_provider_db_accessor.py
  koku/masu/test/external/accounts/hierarchy/aws/test_aws_org_unit_crawler.py
  koku/masu/test/processor/aws/test_aws_report_parquet_processor.py
  koku/masu/test/processor/azure/test_azure_report_parquet_processor.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_processor.py
  koku/masu/test/processor/test_report_parquet_processor_base.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/common.py
  koku/reporting/migrations/0136_auto_20200909_1400.py
  koku/reporting/provider/all/openshift/models.py
  koku/reporting/provider/aws/openshift/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/sources/management/commands/sources.py
  scripts/render_templated_sql.py
  scripts/run_migrations.sh
  scripts/status_probe.py
Labels: stable

#2402 Cost 522 empty csv multi group by
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/test_views.py
  testing/compose_files/docker-compose-multiworker-make.yml
Labels: bug

#2420 Rc 2020.09.25
  dashboards/grafana-dashboard-insights-hccm-postgresql.configmap.yaml
  dashboards/grafana-dashboard-insights-hccm-presto.configmap.yaml
  dashboards/grafana-dashboard-insights-hccm-redis.configmap.yaml
  docs/source/specs/openapi.json
  koku/api/report/serializers.py
  koku/api/report/test/tests_serializers.py
  koku/cost_models/serializers.py
  koku/cost_models/test/tests_serializers.py
  koku/masu/database/sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpawstags_summary.sql
  koku/masu/database/sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpazuretags_summary.sql
  koku/masu/database/sql/reporting_ocpstoragevolumelabel_summary.sql
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
  koku/masu/external/downloader/azure_local/azure_local_report_downloader.py
  koku/masu/processor/azure/azure_report_processor.py
  koku/masu/test/data/azure/azure_version_2.csv
  koku/masu/test/processor/azure/test_azure_report_processor.py
  koku/reporting/migrations/0139_auto_20200925_1432.py
  koku/reporting/migrations/0140_auto_20200925_1825.py
  koku/reporting/provider/aws/openshift/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/reporting/provider/ocp/models.py
  koku/reporting_common/__init__.py
  scripts/e2e-secrets.yml
Labels: release, stable
