Repository project-koku/koku, pull requests merged in 2021-03, with the labels that each got.

#2692 bugfix new param test cases. fix EOM issues.
  koku/api/organizations/test/test_serializers.py
  koku/api/report/test/tests_serializers.py
Labels: bug

#2685 COST-1046: add start_date, end_date params to Tags endpoint
  koku/api/report/test/tests_serializers.py
  koku/api/tags/queries.py
  koku/api/tags/serializers.py
  koku/api/tags/test/tests_serializers.py
Labels: enhancement

#2706 Cost 978 fix check migrations
  db_functions/app_needs_migrations_func.sql
  koku/api/migrations/0038_drop_app_needs_migrations_func.py
  koku/koku/database.py
  koku/koku/test_check_migrations_dbfunc.py
Labels: Database

#2701 Create hive metastore db
  .env.example
  .github/workflows/unittests.yml
  koku/api/migrations/0039_create_hive_db.py
Labels: Database, django

#2714 Use view instead of auth table
  koku/api/migrations/0039_create_hive_db.py
Labels: Database

#2733 Rc 2021.03.17
  docker-compose.yml
  koku/api/migrations/0039_create_hive_db.py
  koku/api/migrations/0040_auto_20210318_1514.py
  koku/api/report/aws/openshift/provider_map.py
  koku/api/settings/utils.py
  koku/cost_models/migrations/0002_auto_20210318_1514.py
  koku/koku/settings.py
  koku/masu/api/source_cleanup.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/database/sql/reporting_gcptags_summary.sql
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/gcp/gcp_report_processor.py
  koku/masu/test/api/test_source_cleanup.py
  koku/masu/test/processor/gcp/test_gcp_report_processor.py
  koku/reporting/migrations/0172_auto_20210318_1514.py
  koku/reporting/provider/gcp/models.py
Labels: release, stable

#2750 COST-1110: forecast should not include negative numbers
  .pre-commit-config.yaml
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
Labels: bug

#2749 Rc 2021.03.23
  Makefile
  Pipfile.lock
  deploy/presto/presto-catalog-config/hive.properties
  deploy/presto/presto-catalog-config/postgres.properties
  docker-compose.yml
  docs/rtd_requirements.txt
  koku-manifest
  koku/api/migrations/0039_create_hive_db.py
  koku/api/provider/provider_manager.py
  koku/api/report/test/utils.py
  koku/cost_models/cost_model_manager.py
  koku/cost_models/test/test_cost_model_manager.py
  koku/kafka_utils/utils.py
  koku/koku/settings.py
  koku/masu/api/report_data.py
  koku/masu/api/status.py
  koku/masu/celery/tasks.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/openapi.json
  koku/masu/processor/__init__.py
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/azure/azure_report_parquet_summary_updater.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_processor.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_report_data.py
  koku/masu/test/api/test_status.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
  koku/masu/test/processor/azure/test_azure_report_parquet_summary_updater.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/azure/common.py
  koku/masu/util/gcp/common.py
  koku/reporting/provider/aws/models.py
  koku/sources/api/source_status.py
  koku/sources/config.py
  koku/sources/kafka_listener.py
  koku/sources/storage.py
  koku/sources/tasks.py
  koku/sources/test/test_storage.py
  testing/compose_files/docker-compose-multilistener.yml
  testing/compose_files/docker-compose-multiworker-make.yml
  testing/compose_files/docker-compose-multiworker.yml
  testing/compose_files/docker-compose-multiworkerlistener.yml
  testing/conf/settings.local.yaml
  testing/run_local_hccm.sh
  testing/run_test.sh
Labels: release, stable

#2708 COST-1075: implement improvements to ranking logic.
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/aws/tests_queries.py
  koku/api/report/test/aws_static_data.yml
Labels: bug

#2765 Rc 2021.03.29
  .pre-commit-config.yaml
  deploy/presto/presto-coordinator-config/jvm.config
  docker-compose.yml
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/aws/tests_queries.py
  koku/api/report/test/aws_static_data.yml
  koku/api/report/test/tests_queries.py
  koku/api/report/test/utils.py
  koku/api/settings/tag_management.py
  koku/api/settings/test/tests_views.py
  koku/cost_models/cost_model_manager.py
  koku/cost_models/test/test_cost_model_manager.py
  koku/cost_models/test/tests_view.py
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
  koku/koku/rbac.py
  koku/koku/tests_rbac.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_orchestrator.py
  koku/reporting/migrations/0173_auto_20210325_1354.py
  scripts/run_migrations.sh
Labels: release, stable

#2772 Cost 1246 enabled tag update tuning
  db_functions/array_subtract_func.sql
  koku/api/migrations/0041_array_subtract_dbfunc.py
  koku/masu/database/sql/reporting_awscostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/sql/reporting_azurecostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_gcpcostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary_update_enabled_tags.sql
  koku/masu/test/database/test_array_subtract.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py
Labels: Database, Performance

#2768 COST-1228: bugfix row defaults
  koku/api/report/queries.py
Labels: bug

#2778 COST-1091: fix forecasting on last day of the month
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
Labels: bug

#2776 Ensure tenant create resets schema path to public
  db_functions/clone_schema.sql
  koku/api/iam/models.py
  koku/api/iam/test/test_clone_schema.py
  koku/api/migrations/0042_reapply_clone_func.py
Labels: Database, Performance, django
