Repository project-koku/koku, pull requests merged in 2021-07, with the labels that each got.

#2988 Fix syntax
  Dockerfile
Labels: pr-check-build

#2994 sources: fix applications/authentications queries
  koku/sources/kafka_message_processor.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_kafka_message_processor.py
  koku/sources/test/test_sources_http_client.py
Labels: pr-check-build

#2993 clowder: configurator updates
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  koku/koku/configurator.py
  koku/koku/settings.py
Labels: pr-check-build

#3005 Set constraints to immediate
  koku/koku/database.py
  koku/koku/test_delete_sql.py
Labels: Database

#3006 Rc 2021.07.09
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/api/resource_types/aws_accounts/view.py
  koku/api/resource_types/gcp_accounts/view.py
  koku/api/resource_types/gcp_projects/view.py
  koku/api/resource_types/gcp_services/view.py
  koku/api/resource_types/serializers.py
  koku/koku/celery.py
  koku/koku/configurator.py
  koku/koku/database.py
  koku/koku/settings.py
  koku/koku/test_delete_sql.py
Labels: release, stable

#3012 Keep django relations, but drop db foreign key constraints
  koku/api/provider/models.py
  koku/koku/database.py
  koku/koku/test_delete_sql.py
  koku/koku/test_get_model.py
  koku/reporting/migrations/0182_drop_constraints.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/ocp/models.py
  testing/run_test.sh
Labels: Database, django

#3017 Rc 2021.07.15
  Pipfile.lock
  deploy/clowdapp.yaml
  deploy/kustomize/patches/scheduler.yaml
  docs/rtd_requirements.txt
  koku-manifest
  koku/api/provider/models.py
  koku/api/resource_types/openshift_clusters/view.py
  koku/api/resource_types/serializers.py
  koku/forecast/forecast.py
  koku/koku/database.py
  koku/koku/test_delete_sql.py
  koku/koku/test_get_model.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazure_matched_tags.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpazure_matched_tags.sql
  koku/masu/database/sql/reporting_ocpazurecostentrylineitem_daily_summary_back_populate.sql
  koku/masu/database/sql/reporting_ocpstoragelineitem_daily_summary.sql
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/azure/azure_report_parquet_processor.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/processor/azure/test_azure_report_parquet_processor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/util/azure/common.py
  koku/masu/util/common.py
  koku/masu/util/ocp/common.py
  koku/reporting/migrations/0182_drop_constraints.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/ocp/models.py
  scripts/nise_ymls/ocp_on_azure/ocp_static_data.yml
  testing/run_test.sh
Labels: release, stable

#2977 COST-1447, COST-1448: Cluster to node distribution (cpu & memory).
  koku/api/metrics/constants.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/provider_map.py
  koku/api/report/test/ocp/tests_views.py
  koku/masu/database/cost_model_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py
  koku/reporting/migrations/0183_cost_distribution.py
  koku/reporting/provider/ocp/models.py
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_by_node_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_by_project_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_pod_summary_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_pod_summary_by_project_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_volume_summary_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_volume_summary_by_project_20210615.sql
  scripts/load_test_customer_data.sh
  scripts/nise_ymls/ocp/ocp_on_premise.yml
Labels: API, Database, ocp

#3019 Cost 1599 aws tag bugs2
  koku/api/query_handler.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/settings/test/tests_views.py
  koku/api/tags/aws/queries.py
  koku/api/tags/azure/queries.py
  koku/api/tags/gcp/queries.py
  koku/api/tags/ocp/queries.py
  koku/api/tags/queries.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
  koku/api/tags/test/ocp/tests_view.py
Labels: API

#3024 Rc 2021.07.21
  koku/api/common/permissions/aws_access.py
  koku/api/common/permissions/gcp_access.py
  koku/api/common/permissions/openshift_access.py
  koku/api/metrics/constants.py
  koku/api/query_handler.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/provider_map.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/resource_types/aws_accounts/view.py
  koku/api/resource_types/aws_org_unit/view.py
  koku/api/resource_types/aws_regions/view.py
  koku/api/resource_types/aws_services/view.py
  koku/api/resource_types/azure_regions/view.py
  koku/api/resource_types/azure_services/view.py
  koku/api/resource_types/azure_subscription_guid/view.py
  koku/api/resource_types/cost_models/view.py
  koku/api/resource_types/gcp_accounts/view.py
  koku/api/resource_types/gcp_projects/view.py
  koku/api/resource_types/gcp_regions/view.py
  koku/api/resource_types/gcp_services/view.py
  koku/api/resource_types/openshift_clusters/view.py
  koku/api/resource_types/openshift_nodes/view.py
  koku/api/resource_types/openshift_projects/view.py
  koku/api/resource_types/test/tests_views.py
  koku/api/settings/test/tests_views.py
  koku/api/tags/aws/queries.py
  koku/api/tags/azure/queries.py
  koku/api/tags/gcp/queries.py
  koku/api/tags/ocp/queries.py
  koku/api/tags/queries.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
  koku/api/tags/test/ocp/tests_view.py
  koku/koku/dev_middleware.py
  koku/masu/api/source_cleanup.py
  koku/masu/database/cost_model_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_processor.py
  koku/masu/test/api/test_source_cleanup.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/reporting/migrations/0183_cost_distribution.py
  koku/reporting/provider/ocp/models.py
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_by_node_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_by_project_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_pod_summary_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_pod_summary_by_project_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_volume_summary_20210615.sql
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_volume_summary_by_project_20210615.sql
  koku/sources/kafka_message_processor.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_kafka_message_processor.py
  scripts/load_test_customer_data.sh
  scripts/nise_ymls/ocp/ocp_on_premise.yml
Labels: release, stable

#3021 COST-1450: Monthly rate to project cost distribution.
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/reporting/provider/ocp/models.py
  koku/reporting/provider/ocp/sql/views/_20210615/reporting_ocp_cost_summary_by_project_20210615.sql
Labels: API, ocp

#2950 Cost 1037 expire partitions
  db_functions/clone_schema.sql
  db_functions/partitioned_manage_trigger.sql
  db_functions/partitioned_manager_trigger_function.sql
  docker-compose.yml
  koku/api/migrations/0048_new_partition_manager_func.py
  koku/koku/database.py
  koku/koku/pg_partition.py
  koku/koku/test_delete_sql.py
  koku/koku/test_pg_partition.py
  koku/masu/api/expired_data.py
  koku/masu/celery/tasks.py
  koku/masu/config.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/openapi.json
  koku/masu/processor/_tasks/remove_expired.py
  koku/masu/processor/aws/aws_report_db_cleaner.py
  koku/masu/processor/azure/azure_report_db_cleaner.py
  koku/masu/processor/expired_data_remover.py
  koku/masu/processor/gcp/gcp_report_db_cleaner.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_cloud_summary_updater.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_expired_data.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/aws/test_aws_report_db_cleaner.py
  koku/masu/test/processor/azure/test_azure_report_db_cleaner.py
  koku/masu/test/processor/gcp/test_gcp_report_db_cleaner.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
  koku/masu/test/processor/test_expired_data_remover.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting/migrations/0184_new_partition_manager_trigger.py
  koku/reporting/migrations/0185_partition_ocp_on_x_tables.py
  koku/reporting/migrations/0186_subpartition_cols.py
  koku/reporting/partition/models.py
  koku/reporting/provider/aws/openshift/models.py
  koku/reporting/provider/azure/openshift/models.py
Labels: API, Database, Performance, aws, azure, ocp

#3029 strip quotes from owner
  koku/koku/pg_partition.py
Labels: pr-check-build

#3034 reorder migrations for safe application
  koku/reporting/migrations/0185_subpartition_cols.py
  koku/reporting/migrations/0186_partition_ocp_on_x_tables.py
  koku/reporting/migrations/0187_project_distribution.py
Labels: API, Database

#3011 probe server
  .coveragerc
  deploy/clowdapp.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  koku/koku/celery.py
  koku/koku/probe_server.py
  koku/masu/management/commands/listener.py
  koku/sources/api/status.py
  koku/sources/management/commands/sources_listener.py
Labels: pr-check-build
