Repository project-koku/koku, pull requests merged in 2021-04, with the labels that each got.

#2788 Rc 2021.04.08
  Makefile
  db_functions/array_subtract_func.sql
  db_functions/clone_schema.sql
  deploy/metastore/hive-config/hive-site.xml
  deploy/metastore/hive-scripts/entrypoint.sh
  deploy/presto/presto-catalog-config/hive.properties
  docker-compose.yml
  koku/api/iam/models.py
  koku/api/iam/test/test_clone_schema.py
  koku/api/migrations/0041_array_subtract_dbfunc.py
  koku/api/migrations/0042_reapply_clone_func.py
  koku/api/provider/provider_builder.py
  koku/api/provider/serializers.py
  koku/api/provider/test/tests_serializers.py
  koku/api/report/queries.py
  koku/api/settings/utils.py
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
  koku/masu/api/download.py
  koku/masu/api/report_data.py
  koku/masu/api/update_cost_model_costs.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/sql/reporting_awscostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/sql/reporting_azurecostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_gcpcostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary_update_enabled_tags.sql
  koku/masu/external/date_accessor.py
  koku/masu/openapi.json
  koku/masu/processor/aws/aws_report_processor.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_download.py
  koku/masu/test/api/test_report_data.py
  koku/masu/test/api/test_update_cost_model_costs.py
  koku/masu/test/database/test_array_subtract.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/external/test_date_accessor.py
  koku/masu/test/processor/aws/test_aws_report_processor.py
  koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/util/azure/common.py
  koku/masu/util/ocp/common.py
  koku/reporting/provider/azure/models.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_sources_http_client.py
  testing/compose_files/docker-compose-presto.yml
  testing/compose_files/docker-compose-priority-ocp-normal-workers.yml
Labels: release, stable

#2784 COST-1252: bugfix ranked grouping
  koku/api/report/queries.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/masu/test/util/test_hash.py
  koku/masu/util/hash.py
Labels: bug

#2792 Cost 1151 update matviews simple
  koku/reporting/migrations/0174_update_ocpall_matviews.py
  koku/reporting/provider/all/openshift/sql/views/reporting_ocpallcostlineitem_daily_summary.sql
Labels: API, Database

#2807 Tenant create logging
  koku/api/iam/models.py
  koku/api/iam/test/test_clone_schema.py
Labels: API, Database

#2797 Pre process enabled tag keys
  koku/api/settings/tag_management.py
  koku/api/tags/aws/openshift/queries.py
  koku/api/tags/aws/queries.py
  koku/masu/database/presto_sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_awscostentrylineitem_daily_summary_insert.sql
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/common.py
  koku/reporting/migrations/0176_update_aws_enabled_keys.py
  koku/reporting/provider/aws/models.py
Labels: API, Database, aws

#2820 Rc 2021.04.22
  koku/api/common/pagination.py
  koku/api/iam/models.py
  koku/api/organizations/serializers.py
  koku/api/organizations/test/test_serializers.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/aws/openshift/tests_views.py
  koku/api/report/test/aws/test_views.py
  koku/api/report/test/aws/tests_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/tests_azure_query_handler.py
  koku/api/report/test/gcp/tests_gcp_query_handler.py
  koku/api/report/test/ocp/tests_views.py
  koku/api/report/test/tests_serializers.py
  koku/api/report/view.py
  koku/api/settings/tag_management.py
  koku/api/tags/aws/openshift/queries.py
  koku/api/tags/aws/queries.py
  koku/api/tags/serializers.py
  koku/api/tags/test/tests_serializers.py
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/gunicorn.conf.py
  koku/koku/middleware.py
  koku/koku/settings.py
  koku/koku/test_middleware.py
  koku/masu/database/presto_sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_awscostentrylineitem_daily_summary_insert.sql
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/common.py
  koku/reporting/migrations/0176_update_aws_enabled_keys.py
  koku/reporting/provider/aws/models.py
Labels: release, stable

#2828 remove patch; apply tuned-up clone func
  db_functions/clone_schema.sql
  koku/api/iam/models.py
  koku/api/iam/sql/tenant_create.sql
  koku/api/migrations/0043_apply_turbo_schema_clone_func.py
Labels: API, Database

#2827 Rc.2021.04.23
  db_functions/clone_schema.sql
  koku/api/iam/models.py
  koku/api/iam/test/test_clone_schema.py
  koku/api/migrations/0043_apply_turbo_schema_clone_func.py
  koku/api/organizations/queries.py
  koku/api/organizations/serializers.py
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/api/report/serializers.py
  koku/api/settings/tag_management.py
  koku/api/settings/utils.py
  koku/api/tags/queries.py
  koku/api/tags/serializers.py
  koku/api/tests_query_params.py
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/koku/settings.py
Labels: release, stable

#2830 add tags to group by
  koku/reporting/provider/all/openshift/sql/views/reporting_ocpallcostlineitem_daily_summary.sql
Labels: Database

#2831 Rc 2021.04.26
  koku/reporting/provider/all/openshift/sql/views/reporting_ocpallcostlineitem_daily_summary.sql
Labels: release, stable

#2832 remove with data to pass migration
  koku/reporting/provider/all/openshift/sql/views/reporting_ocpallcostlineitem_daily_summary.sql
Labels: Database

#2834 Rc 2021.04.26 2
  koku/reporting/provider/all/openshift/sql/views/reporting_ocpallcostlineitem_daily_summary.sql
Labels: release, stable

#2837 Rc 2021.04.26 3
  koku/reporting/migrations/0174_update_ocpall_matviews.py
Labels: release, stable

#2838 create tenant from file
  koku/api/iam/models.py
  koku/api/iam/sql/koku_tenant_create.sql
Labels: API

#2839 Rc 2021.04.26 4
  koku/api/iam/models.py
  koku/api/iam/sql/koku_tenant_create.sql
Labels: release, stable

#2841 Revert processing changes
  koku/masu/database/sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: Database, aws, azure, ocp
