Repository project-koku/koku, pull requests merged in 2021-02, with the labels that each got.

#2630 COST-908: bugfix for summary table lookup
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
Labels: bug

#2629 reapply application-side text field size check
  koku/api/model_utils.py
  koku/api/provider/models.py
  koku/api/provider/test/tests_models.py
Labels: ocp

#2636 COST-954: add AnyUserAccess; small refactor
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/koku/settings.py
Labels: enhancement

#2647 Rc 2021.02.09
  Pipfile.lock
  docs/rtd_requirements.txt
  docs/source/specs/openapi.json
  koku-manifest
  koku/api/model_utils.py
  koku/api/provider/models.py
  koku/api/provider/test/tests_models.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/gcp/view.py
  koku/api/report/test/gcp/tests_gcp_query_handler.py
  koku/api/report/test/gcp_static_data.yml
  koku/api/urls.py
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/api/views.py
  koku/forecast/forecast.py
  koku/forecast/test/tests_forecast.py
  koku/koku/settings.py
  koku/masu/util/gcp/common.py
  koku/providers/gcp/provider.py
  koku/providers/test/gcp/tests_provider.py
  koku/reporting/migrations/0166_gcp_storage_summary.py
  koku/reporting/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/gcp/sql/views/reporting_gcp_storage_summary.sql
  koku/reporting/provider/gcp/sql/views/reporting_gcp_storage_summary_by_account.sql
  koku/reporting/provider/gcp/sql/views/reporting_gcp_storage_summary_by_project.sql
  koku/reporting/provider/gcp/sql/views/reporting_gcp_storage_summary_by_region.sql
  koku/reporting/provider/gcp/sql/views/reporting_gcp_storage_summary_by_service.sql
  koku/sources/api/source_status.py
  koku/sources/kafka_listener.py
  koku/sources/sources_http_client.py
  koku/sources/sources_patch_handler.py
  koku/sources/sources_provider_coordinator.py
  koku/sources/storage.py
  koku/sources/test/api/test_source_status.py
  koku/sources/test/test_storage.py
  scripts/e2e-secrets.yml
  scripts/nise_ymls/gcp/gcp_static_data.yml
  scripts/show_test_graph.py
Labels: release, stable

#2660 Rc 2021.02.15
  Pipfile
  Pipfile.lock
  docs/rtd_requirements.txt
  koku-manifest
  koku/api/provider/provider_builder.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/gcp/query_handler.py
  koku/cost_models/view.py
  koku/koku/settings.py
  koku/masu/database/sql/reporting_gcpcostentrylineitem_daily.sql
  koku/reporting/migrations/0167_gcpdatabasesummary_gcpnetworksummary.py
  koku/reporting/migrations/0168_auto_20210211_2210.py
  koku/reporting/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/gcp/sql/views/reporting_gcp_database_summary.sql
  koku/reporting/provider/gcp/sql/views/reporting_gcp_network_summary.sql
  koku/reporting_common/__init__.py
  koku/sources/api/source_status.py
  koku/sources/api/view.py
  koku/sources/kafka_listener.py
  koku/sources/test/api/test_source_status.py
  koku/sources/test/api/test_view.py
  koku/sources/test/test_kafka_listener.py
Labels: release, stable

#2656 COST-1001: add start_date and end_date report query parameters
  docs/source/specs/openapi.json
  koku/api/query_handler.py
  koku/api/report/serializers.py
  koku/api/report/test/aws/tests_queries.py
  koku/api/report/test/tests_queries.py
  koku/api/report/test/tests_serializers.py
Labels: enhancement

#2633 process big deletes as a loop of smaller transactions
  koku/masu/database/koku_database_access.py
  koku/masu/processor/aws/aws_report_db_cleaner.py
  koku/masu/processor/azure/azure_report_db_cleaner.py
  koku/masu/processor/gcp/gcp_report_db_cleaner.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/processor/report_processor_base.py
  koku/masu/test/database/test_mini_transaction_delete.py
Labels: API, Database

#2638 reduce the potential of constraint violation
  koku/masu/database/koku_database_access.py
Labels: API

#2671 scripting updates - improve resilience, DRY up a few things
  Makefile
  scripts/create_test_customer.py
  scripts/load_test_customer_data.sh
Labels: bug, enhancement

#2675 Check a single and list of filters to apply contains
  koku/api/query_handler.py
  koku/api/report/test/all/openshift/test_query_handler.py
Labels: API

#2677 bugfix for create_test_customer
  scripts/create_test_customer.py
Labels: bug

#2682 Localdev db ssl
  .gitignore
  README.rst
  docker-compose.yml
  scripts/genssc
Labels: Database

#2678 Add ON CONFLICT DO NOTHING as this is looking like race conditiion issues
  koku/masu/database/sql/reporting_awscostentrylineitem_daily.sql
  koku/masu/database/sql/reporting_awsenabledtagkeys.sql
  koku/masu/database/sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/database/sql/reporting_azureenabledtagkeys.sql
  koku/masu/database/sql/reporting_gcpcostentrylineitem_daily.sql
  koku/masu/database/sql/reporting_gcpenabledtagkeys.sql
Labels: Database

#2673 add start_date and end_date parameters to org unit endpoint.
  koku/api/organizations/queries.py
  koku/api/organizations/serializers.py
  koku/api/organizations/test/test_serializers.py
Labels: enhancement
