Repository project-koku/koku, pull requests merged in 2022-08, with the labels that each got.

#3776 mock customer gets a schema_name
  koku/koku/dev_middleware.py
Labels: smokes-required

#3778 [COST-2621] - add additional ebs->org-id job params
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: smokes-required

#3779 [COST-2621] remove org-id populator job from clowdapp
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: hot-fix-smoke-tests, smokes-required

#3785 [COST-2846] download without summary param
  koku/masu/api/download.py
  koku/masu/openapi.json
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#3782 [Cost-2842] ocp on cloud masu endpoint
  koku/masu/api/update_openshift_on_cloud.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/openapi.json
  koku/masu/test/api/test_update_openshift_on_cloud.py
Labels: smokes-required

#3780 [COST-2841] masu report data skip ocp on cloud
  koku/masu/api/report_data.py
  koku/masu/openapi.json
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_report_data.py
Labels: smokes-required

#3783 Stubbing out remaining notification tasks
  koku/koku/notifications.py
  koku/koku/test_notifications.py
  koku/masu/api/notifications.py
  koku/masu/celery/tasks.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/test/api/test_notification.py
  koku/masu/test/celery/test_tasks.py
Labels: smokes-required

#3788 updating notifications for org_id support
  koku/koku/notifications.py
  koku/koku/test_notifications.py
  koku/masu/celery/tasks.py
  koku/masu/database/provider_db_accessor.py
Labels: smokes-required

#3789 COST-1380 - managed kafka config
  koku/koku/configurator.py
Labels: smoke-tests, smokes-required

#3719 [COST-2232] Discrepancies when using time_scope parameters
  koku/api/query_params.py
  koku/api/tags/serializers.py
Labels: smoke-tests, smokes-required

#3791 [COST-2855] trino masu api
  deploy/clowdapp.yaml
  deploy/kustomize/patches/masu.yaml
  docker-compose.yml
  koku/masu/api/trino.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/openapi.json
  koku/masu/test/api/test_trino.py
Labels: smokes-required

#3744 COST-2632 AWS Org Unit and Account filter are not creating an additive set for the API query
  koku/api/query_params.py
  koku/api/report/aws/query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/aws/test_queries.py
  koku/api/test_query_params.py
Labels: smoke-tests, smokes-required

#3794 Fixing notification to not fire on cloud sources
  koku/masu/celery/tasks.py
  koku/masu/test/celery/test_tasks.py
Labels: smokes-required

#3798 [COST-2829] - update kafka message handler
  docs/koku_setup_on_m1.rst
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#3799 Removing date override step
  koku/masu/processor/oci/oci_report_parquet_summary_updater.py
  koku/masu/test/processor/oci/test_oci_report_parquet_summary_updater.py
Labels: smokes-required

#3797 Update apiPath in ClowdApp and patches
  deploy/clowdapp.yaml
  deploy/kustomize/patches/koku.yaml
Labels: hot-fix-smoke-tests

#3742 Cost 2188: Upgrade base image to Python 3.9
  .github/workflows/unittests.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  dev/scripts/create_manifest.py
  docs/rosetta_on_m1.rst
  koku-manifest
  scripts/cji_scripts/adjust_ocp_ui_numerics.py
  scripts/cji_scripts/check_for_migration_app_name.py
  scripts/cji_scripts/copy_ocp_aws_azure_data.py
  scripts/cji_scripts/copy_static_perspective_data.py
  scripts/cji_scripts/migrate_trino.py
  scripts/cji_scripts/truncate_ocp_on_awsazure_base.py
  scripts/cji_scripts/truncate_old_tables.py
  scripts/run_migrations.sh
  tox.ini
Labels: smoke-tests, smokes-required

#3801 join the sources event loop
  koku/sources/kafka_listener.py
Labels: hot-fix-smoke-tests, smokes-required

#3800 sonarqube updates for Java 11
  .gitignore
  sonarqube.sh
  sonarqube_exec.sh
Labels: ok-to-skip-smokes

#3803 [COST-1380] - set api version
  koku/kafka_utils/utils.py
  koku/sources/kafka_listener.py
Labels: hot-fix-smoke-tests, smokes-required

#3805 [COST-1380] - disable api-verion-request
  koku/kafka_utils/utils.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/sources/kafka_listener.py
  koku/sources/test/test_kafka_listener.py
Labels: hot-fix-smoke-tests, smokes-required

#3781 Update GCP internal url to include metadata for invoice month & credits.
  koku/masu/api/gcp_invoice_monthly_cost.py
  koku/masu/test/api/test_gcp_invoice_monthly_cost.py
Labels: smokes-required

#3792 COST-2810: Remove self healing code after downloader transition.
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/processor/orchestrator.py
  koku/masu/util/aws/common.py
Labels: smokes-required

#3793 COST-2862: Don't summarize per manifest for GCP.
  koku/api/provider/models.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/test_tasks.py
Labels: smokes-required

#3808 Revert "COST-2862: Don't summarize per manifest for GCP."
  koku/api/provider/models.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/test_tasks.py
Labels: smokes-required

#3806 Cost 1380 api version
  koku/kafka_utils/utils.py
  koku/koku/configurator.py
  koku/masu/config.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/sources/config.py
  koku/sources/kafka_listener.py
  koku/sources/test/test_kafka_listener.py
Labels: hot-fix-smoke-tests, smokes-required

#3810 Setting default source_uuid to None
  koku/masu/api/source_cleanup.py
Labels: smokes-required

#3811 [COST-1380] - fix missing arg to get_producer
  koku/kafka_utils/utils.py
Labels: hot-fix-smoke-tests, smokes-required

#3802 [COST-2829] - commit messages that are not ours
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#3812 small fix on notifications celery task
  koku/masu/celery/tasks.py
Labels: smokes-required

#3809 COST-2682: Summarize by a list of manifests
  koku/api/provider/models.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#3804 [COST-2867] return if no report period for delete tag usage costs
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py
Labels: smoke-tests, smokes-required

#3813 COST-2881: Purge trino files internal endpoint.
  .unleash/flags.json
  koku/masu/api/purge_trino_files.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/celery/tasks.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/openapi.json
  koku/masu/processor/__init__.py
  koku/masu/test/api/test_purge_trino_files.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
Labels: smokes-required

#3814 enable hcs through `ENABLE_HCS_DEBUG`
  Makefile
  deploy/clowdapp.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  docker-compose.yml
  koku/hcs/tasks.py
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#3815 COST-2892: adding invoice month to GCP summary tasks
  koku/api/resource_types/test/gcp_accounts/test_views.py
  koku/api/resource_types/test/gcp_projects/test_views.py
  koku/api/resource_types/test/gcp_regions/test_views.py
  koku/api/resource_types/test/gcp_services/test_views.py
  koku/api/utils.py
  koku/masu/api/report_data.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/gcp/gcp_report_summary_updater.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_report_data.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/gcp/test_gcp_report_summary_updater.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/util/gcp/common.py
Labels: smoke-tests, smokes-required

#3816 COST-2895: Add invoice month to report_data endpoint.
  koku/masu/api/report_data.py
  koku/masu/openapi.json
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/test/api/test_report_data.py
Labels: smokes-required

#3817 prevent InterfaceError double alerting
  koku/masu/external/kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#3820 Speed up m1 refresher script.
  dev/scripts/m1_refresher.sh
Labels: ok-to-skip-smokes

#3818 COST-2896: GCP: extend date ranges for monthly views
  koku/api/query_handler.py
  koku/api/utils.py
Labels: full-run-smoke-tests, smokes-required

#3819 COST-2897: Rename gcp validation turnpike & add daily return
  koku/masu/api/bigquery_cost.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/openapi.json
  koku/masu/test/api/test_bigquery_cost.py
  koku/masu/test/api/test_gcp_invoice_monthly_cost.py
Labels: smokes-required

#3821 [COST-2898] - validate schema when provider-uuid is a param
  koku/masu/api/report_data.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/test/api/test_report_data.py
Labels: smoke-tests, smokes-required

#3824 passing ocp on cloud skip arg
  koku/masu/processor/tasks.py
Labels: smokes-required

#3823 Adding the ability to disable a specific schema from processing
  .unleash/flags.json
  koku/masu/processor/__init__.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smokes-required

#3822 COST-2863: Broken links to doc pages
  koku/api/settings/settings.py
  koku/api/settings/utils.py
Labels: smoke-tests

#3826 Add time range to the purge turnpike endpoint
  koku/api/test_utils.py
  koku/api/utils.py
  koku/masu/api/purge_trino_files.py
  koku/masu/celery/tasks.py
  koku/masu/test/api/test_purge_trino_files.py
Labels: smoke-tests, smokes-required

#3828 [COST-1840] - add redis health check interval
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#3825 [COST-2900] add date and source filtering to GCP HCS
  koku/hcs/database/sql/reporting_gcp-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_gcp_hcs_daily_summary.sql
Labels: smoke-tests, smokes-required

#3831 Disable ingest when marking provider setup_complete as false
  koku/api/provider/models.py
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/processor/__init__.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
Labels: smokes-required

#3833 GCP: Batch csv file creation during download
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/gcp_local/gcp_local_report_downloader.py
  koku/masu/test/data/gcp/2022-08-01_5.csv
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
Labels: smoke-tests, smokes-required

#3830 COST-2632 - fix access params for org units
  koku/api/iam/test/iam_test_case.py
  koku/api/query_params.py
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/test_queries.py
Labels: smoke-tests, smokes-required

#3834 [COST-1840] - enable retry on timeout
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#3839 Add an unleash flag to disable summary.
  .unleash/flags.json
  koku/masu/processor/__init__.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: smokes-required

#3841 [COST-1840] - set health check interval to 5 seconds
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#3843 [COST-2901] AWS/Azure only generate HCS reports for last 3 days on initial ingest
  koku/hcs/tasks.py
  koku/hcs/test/test_tasks.py
Labels: smoke-tests, smokes-required
