Repository project-koku/koku, pull requests merged in 2022-12, with the labels that each got.

#4036 Support wildcard tag filters
  koku/api/report/queries.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/oci/test_oci_query_handler.py
Labels: smoke-tests, smokes-required

#4034 [COST-3301] determine cost category id for Unallocated Capacity Costs
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpazurecostentrylineitem_daily_summary_back_populate.sql
Labels: smoke-tests, smokes-required

#4009 move annotation to the podspec
  deploy/clowdapp.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-listener.yaml
Labels: hot-fix-smoke-tests, smokes-required

#4040 COST-3199: Add ephemeral fallback for unleash negative filtering
  koku/api/query_params.py
Labels: smokes-required

#4030 COST-3121 update sql to populate new ocpaws columns
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_compute_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_by_account_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_by_region_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_by_service_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_database_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_network_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_storage_summary_p.sql
Labels: smoke-tests, smokes-required

#4038 [COST-3123] ocp on aws api cost type
  koku/api/forecast/serializers.py
  koku/api/query_params.py
  koku/api/report/aws/openshift/provider_map.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/openshift/serializers.py
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/openshift/test_serializers.py
  koku/api/report/test/aws/openshift/test_views.py
  koku/api/tags/aws/openshift/queries.py
  koku/forecast/forecast.py
Labels: smokes-required

#4039 [COST-3124] ocp savingsplan cost
  .unleash/flags.json
  koku/api/report/test/util/baker_recipes.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
  koku/masu/processor/__init__.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
Labels: smokes-required, unleash

#4045 Default savingsplan cost to true for dev
  koku/masu/processor/__init__.py
Labels: smokes-required

#4022 [COST-3200] numeric cost columns
  koku/reporting/migrations/0265_auto_20221114_1806.py
  koku/reporting/provider/ocp/models.py
Labels: migration, smokes-required

#4047 [COST-3313] - update GCP decimal precision
  koku/reporting/migrations/0266_ocpgcp_precision.py
  koku/reporting/provider/gcp/openshift/models.py
Labels: gcp-smoke-tests, smokes-required

#4050 validationError duplicate provider
  koku/sources/api/source_status.py
  koku/sources/test/api/test_source_status.py
Labels: smokes-required

#4046 [COST-3313] - distribute by resource usage (GCP)
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/tags/test/aws/openshift/test_queries.py
  koku/api/tags/test/aws/test_aws_tag_query_handler.py
  koku/api/tags/test/azure/test_azure_tag_query_handler.py
  koku/api/tags/test/gcp/test_queries.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcp_ocp_infrastructure_back_populate.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_compute_summary_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_account_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_gcp_project_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_region_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_service_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_cost_summary_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_database_summary_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_network_summary_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcptags_summary.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_gcp.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/providers/ocp/provider.py
Labels: gcp-smoke-tests, smokes-required

#4049 [COST-3311] - Match volume to node on namespace too
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: smokes-required

#4052 [COST-3331] rename unallocated projects and no-<something> to No-<something>
  koku/api/report/ocp/provider_map.py
  koku/api/report/queries.py
  koku/api/report/test/all/openshift/test_query_handler.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_views.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_p.sql
Labels: smoke-tests, smokes-required

#4056 set the KOKU_SENTRY_ENVIRONMENT in koku-worker
  .unleash/flags.json
  docker-compose.yml
Labels: ok-to-skip-smokes

#4058 [COST-3312] - distribution by resource usage for Azure
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/openshift/test_views.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_compute_summary_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_cost_summary_by_account_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_cost_summary_by_location_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_cost_summary_by_service_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_cost_summary_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_database_summary_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_network_summary_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_storage_summary_p.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_azure.sql
  koku/masu/database/sql/reporting_ocpazure_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpazuretags_summary.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/providers/ocp/provider.py
Labels: azure-smoke-tests, smokes-required

#4054 Log response time as a ms `int` not a string
  koku/koku/middleware.py
Labels: smoke-tests

#4032 remove local differentiation from HCS provider types
  koku/hcs/daily_report.py
  koku/hcs/database/report_db_accessor.py
  koku/hcs/database/sql/reporting_aws-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_azure-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_gcp-local_hcs_daily_summary.sql
  koku/hcs/test/test_daily_report.py
Labels: smoke-tests, smokes-required

#4029 [COST-3272] continue to next report if no manifest found for HCS processing
  koku/hcs/tasks.py
  koku/hcs/test/test_tasks.py
Labels: smoke-tests, smokes-required

#4048 COST-3317: missing cost_category for monthly cost-model derived rows
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/util/common.py
  koku/api/report/test/util/constants.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: ocp-smoke-tests, smokes-required

#4062 [COST-3349] - add handler for OCI RequesException
  koku/providers/oci/provider.py
  koku/providers/test/oci/test_oci_provider.py
Labels: smokes-required, oci-smoke-tests

#4059 COST-3316: Category filtering doesn't work with tags.
  koku/api/currency/view.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/test_queries.py
  koku/api/report/test/test_serializers.py
  koku/api/tags/ocp/serializers.py
  koku/api/tags/queries.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/default_infrastructure_tag_rates.sql
  koku/masu/database/sql/default_supplementary_tag_rates.sql
  koku/masu/database/sql/infrastructure_tag_rates.sql
  koku/masu/database/sql/supplementary_tag_rates.sql
Labels: ocp-smoke-tests, smokes-required

#4065 Fix get_exchange_rates
  koku/api/currency/view.py
Labels: smoke-tests, smokes-required

#4061 remove currency-url from docker compose
  docker-compose.yml
Labels: ok-to-skip-smokes
