Repository project-koku/koku, pull requests merged in 2022-02, with the labels that each got.

#3434 Add fallback to effective cost calc in Trino
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: smoke-tests, trino-smoke-tests

#3438 COST-2295: switch public to private ports
  deploy/clowdapp.yaml
  deploy/koku-cji.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/sources-client.yaml
  koku/gunicorn_conf.py
  koku/koku/probe_server.py
  scripts/entrypoint.sh
Labels: smoke-tests, trino-smoke-tests

#3445 [COST-2304] - cleanup trino migration script
  scripts/job_script.sh
  scripts/migrate_trino.py
Labels: pr-check-build

#3441 Uncomment partitioned tables for purge by partition drop
  koku/masu/processor/aws/aws_report_db_cleaner.py
  koku/masu/processor/azure/azure_report_db_cleaner.py
Labels: pr-check-build

#3449 Cost 2312 always log db pid
  koku/api/common/__init__.py
  koku/api/iam/test/iam_test_case.py
  koku/api/iam/test/test_clone_schema.py
  koku/api/status/test_status.py
  koku/koku/settings.py
  koku/koku/test_cache.py
  koku/koku/test_delete_sql.py
  koku/masu/test/api/test_status.py
  koku/masu/test/processor/aws/test_aws_report_parquet_processor.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
  koku/masu/test/processor/aws/test_aws_report_processor.py
  koku/masu/test/processor/azure/test_azure_report_parquet_summary_updater.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_processor.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_summary_updater.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/processor/test_report_parquet_processor_base.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/ocp/test_common.py
  koku/sources/test/api/test_source_status.py
  koku/sources/test/api/test_status.py
Labels: pr-check-build

#3450 create a 'dependencies' section
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: pr-check-build

#3462 change to use report_period_id; handle null labels
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary_update_enabled_tags.sql
  koku/masu/test/processor/ocp/test_ocp_report_summary_updater.py
Labels: pr-check-build, ocp-smoke-tests

#3464 COST-2066: Migrations for additional context field.
  koku/api/migrations/0053_additional_context.py
  koku/api/provider/models.py
Labels: migration

#3448 COST-2066: Access denied errors during AWS org unit crawling (part one)
  docs/source/specs/openapi.json
  koku/api/provider/provider_manager.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/external/accounts/hierarchy/aws/aws_org_unit_crawler.py
  koku/masu/test/external/accounts/hierarchy/aws/test_aws_org_unit_crawler.py
  koku/providers/aws/provider.py
  koku/providers/test/aws/test_aws_provider.py
  koku/sources/api/view.py
Labels: aws

#3466 Log unleash startup duration
  koku/koku/celery.py
  koku/koku/test_celery_startup.py
Labels: pr-check-build, full-run-smoke-tests

#3467 [COST-2317] OCP on cloud sql improvements
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  scripts/migrate_trino.py
Labels: trino migration

#3469 COST-2066: Access denied during listing account aliases (pt2)
  koku/masu/util/aws/common.py
Labels: aws

#3470 Script to show latest migrations by sha
  scripts/show_migrations
Labels: pr-check-build

#3473 Check for trino migrations
  scripts/show_migrations
Labels: pr-check-build

#3481 Discrete messaging, return codes for django, trino migration runs
  scripts/show_migrations
Labels: pr-check-build

#3485 [COST-2353] Handle a null tag value coming from GCP
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcptags_summary.sql
  koku/masu/database/sql/reporting_gcptags_summary.sql
  koku/masu/test/util/ocp/test_common.py
  koku/masu/util/ocp/common.py
Labels: trino-smoke-tests, gcp-smoke-tests

#3482 Safe ORM attribute access
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/test/external/accounts/db/test_cur_accounts_db.py
Labels: pr-check-build, hot-fix-smoke-tests

#3484 [COST-2352] raw daily summary deletes
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/azure/azure_report_parquet_summary_updater.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
  koku/masu/test/processor/azure/test_azure_report_parquet_summary_updater.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_summary_updater.py
Labels: trino-smoke-tests

#3486 Add CJI script to truncate Azure lid tables on trino accounts
  .dockerignore
  scripts/job_script.sh
  scripts/truncate_old_tables.py
Labels: pr-check-build

#3479 Cost 1880 source delete retry
  koku/api/provider/provider_builder.py
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/koku/settings.py
  koku/sources/sources_provider_coordinator.py
  koku/sources/tasks.py
Labels: trino-smoke-tests

#3487 Cost 2133
  .unleash/flags.json
  koku/hcs/__init__.py
  koku/hcs/tasks.py
  koku/hcs/test/test_tasks.py
  koku/koku/celery.py
  koku/masu/api/hcs_report_data.py
  koku/masu/test/api/test_hcs_report_data.py
Labels: hot-fix-smoke-tests

#3488 COST-2356 - catch invalid payload and log better error message
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: ocp-smoke-tests

#3492 [COST-2353] Handle null tags in ocp tag updates
  koku/masu/database/sql/reporting_ocpstoragevolumelabel_summary.sql
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
Labels: smoke-tests
