Repository project-koku/koku, pull requests merged in 2022-06, with the labels that each got.

#3677 Fix AWS reports API permissions for Org Units
  koku/api/report/aws/view.py
Labels: aws-smoke-tests, smokes-required

#3679 Start of the month fix for OCI unit tests
  koku/api/report/test/util/model_bakery_loader.py
Labels: ok-to-skip-smokes

#3681 Fix first of month distribution test errors.
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: ok-to-skip-smokes

#3680 [COST-2619] - add org_id to Sources/Customer tables
  koku/api/iam/models.py
  koku/api/migrations/0057_add_org_ids.py
  koku/api/provider/models.py
Labels: smoke-tests, smokes-required

#3641 DRAFT: Currency support order
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/test_views.py
Labels: smokes-required

#3584 [COST-2514] add currency support for volumes endpoint
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/openshift/test_views.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_views.py
Labels: smokes-required

#3682 COST-2648: Increase max paginiation for resource type views
  koku/api/common/pagination.py
  koku/api/common/permissions/resource_type_access.py
  koku/api/common/permissions/test/test_resource_types_access.py
  koku/api/resource_types/aws_accounts/view.py
  koku/api/resource_types/aws_org_unit/view.py
  koku/api/resource_types/aws_regions/view.py
  koku/api/resource_types/aws_services/view.py
  koku/api/resource_types/azure_regions/view.py
  koku/api/resource_types/azure_services/view.py
  koku/api/resource_types/azure_subscription_guid/view.py
  koku/api/resource_types/cost_models/view.py
  koku/api/resource_types/gcp_accounts/view.py
  koku/api/resource_types/gcp_projects/view.py
  koku/api/resource_types/gcp_regions/view.py
  koku/api/resource_types/gcp_services/view.py
  koku/api/resource_types/openshift_clusters/view.py
  koku/api/resource_types/openshift_nodes/view.py
  koku/api/resource_types/openshift_projects/view.py
  koku/api/resource_types/view.py
Labels: smokes-required

#3637 [COST-2561] resource level gcp downloader
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
Labels: smokes-required

#3686 Name on two of the charts were reversed
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#3689 added gauges to grafana dash for celery
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#3690 Fixed chart names
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#3675 Cost 2389 apis openapi
  docs/specs/openapi.json
  koku/api/common/permissions/__init__.py
  koku/api/common/permissions/oci_access.py
  koku/api/forecast/serializers.py
  koku/api/forecast/test/test_views.py
  koku/api/forecast/views.py
  koku/api/metrics/constants.py
  koku/api/query_params.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/api/resource_types/oci_regions/__init__.py
  koku/api/resource_types/oci_regions/view.py
  koku/api/resource_types/oci_services/__init__.py
  koku/api/resource_types/oci_services/view.py
  koku/api/resource_types/oci_tenant_id/__init__.py
  koku/api/resource_types/oci_tenant_id/view.py
  koku/api/resource_types/test/oci_regions/__init__.py
  koku/api/resource_types/test/oci_regions/test_views.py
  koku/api/resource_types/test/oci_services/__init__.py
  koku/api/resource_types/test/oci_services/test_views.py
  koku/api/resource_types/test/oci_tenants/__init__.py
  koku/api/resource_types/test/oci_tenants/test_views.py
  koku/api/settings/settings.py
  koku/api/test_query_params.py
  koku/api/urls.py
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/api/views.py
  koku/forecast/__init__.py
  koku/forecast/forecast.py
  koku/forecast/test/test_forecast.py
  koku/koku/cache.py
  koku/reporting/models.py
  koku/sources/test/api/test_view.py
Labels: smokes-required

#3692 COST-2705: Quiet down unnecessary logs in the org unit crawler
  koku/masu/external/accounts/hierarchy/aws/aws_org_unit_crawler.py
Labels: smokes-required

#3696 minio has added a feature that is not backwards compatible.
  Dockerfile.minio
Labels: ok-to-skip-smokes

#3695 raise exception after logging in execute_delete_sql
  koku/koku/database.py
Labels: pr-check-build, full-run-smoke-tests, smokes-required

#3703 M1 dev related changes for M1 refresher and M1 docker compose files
  dev/scripts/m1_refresher.sh
  testing/compose_files/docker-compose-m1.yml
Labels: ok-to-skip-smokes

#3701 Cost 2683 orchestrator stub
  koku/api/utils.py
  koku/masu/api/report_data.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/aws_local/aws_local_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure_local/azure_local_report_downloader.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/gcp_local/gcp_local_report_downloader.py
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/downloader/oci_local/oci_local_report_downloader.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/azure_local/test_azure_local_report_downloader.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/external/downloader/gcp_local/test_gcp_local_report_downloader.py
  koku/masu/test/external/downloader/oci/test_oci_report_downloader.py
  koku/masu/test/external/downloader/oci_local/test_oci_local_report_downloader.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#3704 fixing start/end nonetype bug
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#3691 COST-2678 - create source and load test customer data for OCI
  Pipfile
  Pipfile.lock
  dev/scripts/cost_models/oci_cost_model.json
  dev/scripts/create_test_customer.py
  dev/scripts/load_test_customer_data.sh
  dev/scripts/nise_ymls/oci/oci_static_data.yml
  dev/scripts/test_customer.yaml
  koku-manifest
Labels: smoke-tests, smokes-required

#3700 Adding OCI changes to onboard to new ochestrator
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/downloader/oci_local/oci_local_report_downloader.py
  koku/masu/processor/oci/oci_report_parquet_summary_updater.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/external/downloader/oci/test_oci_report_downloader.py
  koku/masu/test/external/downloader/oci_local/test_oci_local_report_downloader.py
Labels: smokes-required

#3657 Cost 2639 targeted provider delete cascade
  koku/api/provider/models.py
  koku/koku/test_delete_sql.py
  koku/koku/test_provider_delete_cascade.py
Labels: pr-check-build, smoke-tests, smokes-required

#3663 [COST-2643] pandas based rank limit
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/oci/query_handler.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_views.py
Labels: smokes-required

#3709 Adding correct rbac perms
  koku/koku/rbac.py
  koku/koku/test_rbac.py
Labels: smokes-required

#3710 Adding small tweak to initial summary months
  koku/api/utils.py
  koku/masu/api/report_data.py
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/processor/tasks.py
Labels: smokes-required

#3707 Create rates dictionary for currency
  koku/api/currency/models.py
  koku/api/currency/test/test_utils.py
  koku/api/currency/test/test_views.py
  koku/api/currency/utils.py
  koku/api/currency/view.py
  koku/api/migrations/0058_exchangeratedictionary.py
  koku/api/urls.py
  koku/api/views.py
  koku/koku/test_json_transcode.py
  koku/koku/type_json_transcode.py
  koku/masu/celery/tasks.py
Labels: smokes-required

#3705 [COST-2225] Source stats only show information for current and previous month
  koku/api/provider/provider_manager.py
Labels: smoke-tests, smokes-required

#3661 [COST-1702] Traceback when using * with tag filtering on Openshift key values.
  koku/api/tags/queries.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
Labels: gcp-smoke-tests, smokes-required

#3718 reduce risk of DateAccessor unit test failure
  koku/masu/test/external/test_date_accessor.py
Labels: ok-to-skip-smokes

#3721 Fixing bad SQL
  koku/masu/database/presto_sql/reporting_ocpinfrastructure_provider_map.sql
Labels: smokes-required

#3712 Cost2270 RBAC changes don't invalidate the cache
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#3685 [COST-2689] validate end date to be leq tomorrow
  koku/api/organizations/serializers.py
  koku/api/organizations/test/test_serializers.py
  koku/api/report/serializers.py
  koku/api/report/test/test_serializers.py
  koku/api/tags/serializers.py
  koku/api/tags/test/test_serializers.py
Labels: smoke-tests, smokes-required

#3723 [COST-2750] - use path instead of full_path
  koku/api/report/queries.py
Labels: smoke-tests

#3702 COST-2715: Include report_period_id in tag based rates delete.
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
Labels: smokes-required

#3722 remove update a source from api docs
  docs/specs/openapi.json
Labels: smoke-tests, smokes-required

#3729 [COST-2764] Add raw_currency to OCP tables
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostentrylineitem_daily_summary_back_populate.sql
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_by_node_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_volume_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_volume_summary_p.sql
  koku/masu/database/sql/reporting_ocpawscostentrylineitem_daily_summary_back_populate.sql
  koku/masu/database/sql/reporting_ocpazurecostentrylineitem_daily_summary_back_populate.sql
  koku/reporting/migrations/0257_raw_currency_ocp_on_cloud.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#3724 [Cost-2137] HCS code hardening
  koku/hcs/daily_report.py
  koku/hcs/database/report_db_accessor.py
  koku/hcs/exceptions.py
  koku/hcs/tasks.py
  koku/hcs/test/__init__.py
  koku/hcs/test/test_daily_report.py
  koku/hcs/test/test_exceptions.py
  koku/hcs/test/test_tasks.py
Labels: aws-smoke-tests

#3726 Adding start/end dates
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required
