Repository project-koku/koku, pull requests merged in 2022-07, with the labels that each got.

#3720 Initial notification stubs
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/masu.yaml
  docker-compose.yml
  koku/kafka_utils/utils.py
  koku/koku/notifications.py
  koku/koku/settings.py
  koku/koku/test_notifications.py
  koku/masu/celery/tasks.py
  koku/masu/config.py
  koku/masu/test/celery/test_tasks.py
Labels: smokes-required

#3738 Fix semantic error on organizations endpoint in API docs
  docs/specs/openapi.json
Labels: smokes-required

#3740 Add python 3.9 to our unit test matrix
  .github/workflows/unittests.yml
Labels: ok-to-skip-smokes

#3741 Prevent duplicate providers across accounts
  koku/api/provider/serializers.py
  koku/api/provider/test/test_serializers.py
Labels: smoke-tests, smokes-required

#3747 fix unleash schema strategy so it handles exact match
  koku/hcs/tasks.py
  koku/koku/feature_flags.py
Labels: ok-to-skip-smokes

#3737 fix/update settings API docs
  docs/specs/openapi.json
Labels: ok-to-skip-smokes

#3748 Added ability to check for invalid request params
  koku/masu/api/hcs_report_finalization.py
  koku/masu/test/api/test_hcs_report_finalization.py
Labels: ok-to-skip-smokes

#3749 [COST-2813] Expand currency fields for azure
  koku/masu/database/presto_sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/reporting/provider/azure/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3736 COST-2670 Org Units showing correct total cost for each sub org
  koku/api/report/aws/query_handler.py
Labels: smoke-tests, smokes-required

#3751 Bulk delete for gcp self healing.
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/util/aws/common.py
Labels: smokes-required

#3753 Fix parquet reference in self healing.
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
Labels: smokes-required

#3756 gcp bulk delete in groups of 250
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/util/aws/common.py
Labels: smokes-required

#3758 Removing manifest id check from self healing delete.
  koku/masu/util/aws/common.py
Labels: smokes-required

#3760 Speed up trino bulk delete collection
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/util/aws/common.py
Labels: smokes-required

#3761 Fixing df error
  koku/masu/util/gcp/common.py
Labels: smoke-tests, smokes-required

#3752 [COST-2621] Job to populate ORG-ID
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: smokes-required

#3762 [COST-2621] fix job name for org-id job in clowdapp
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: smokes-required

#3763 [COST-2620] sources filtered by org_id
  koku/koku/middleware.py
  koku/sources/api/view.py
  koku/sources/test/api/test_view.py
Labels: smoke-tests, smokes-required

#3765 fix create test customer flow
  dev/scripts/create_test_customer.py
  dev/scripts/insert_org_tree.py
  dev/scripts/load_test_customer_data.sh
  dev/scripts/test_customer.yaml
  koku/koku/dev_middleware.py
  koku/koku/settings.py
Labels: smokes-required

#3764 Fix schema name
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/hcs/tasks.py
  koku/masu/openapi.json
Labels: ok-to-skip-smokes

#3660 truncate lintitem, lineitem_daily tables
  Makefile
  deploy/koku-cji.yaml
  scripts/cji_scripts/mp_truncate_lineitem_tables.py
  scripts/job_script.sh
Labels: pr-check-build, smoke-tests, smokes-required

#3767 add masu endpoint to trigger notification tasks
  koku/masu/api/notifications.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/openapi.json
  koku/masu/test/api/test_notification.py
Labels: smoke-tests, smokes-required

#3766 [COST-2829] - switch ingress kafka topic
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  koku/kafka_utils/utils.py
  koku/masu/config.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/sources/kafka_message_processor.py
Labels: smoke-tests, smokes-required

#3739 [Cost-2729]Local error - Task failed: 'NoneType' object has no attribute 'id'
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_summary_updater.py
Labels: smoke-tests, smokes-required

#3769 [COST-1380] - update kafka config
  koku/kafka_utils/utils.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/sources/kafka_listener.py
  koku/sources/test/test_kafka_listener.py
Labels: smokes-required

#3770 [COST-1380] - update ssl cert location
  koku/kafka_utils/utils.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/sources/kafka_listener.py
  koku/sources/test/test_kafka_listener.py
Labels: smokes-required

#3771 bump nise version
  Pipfile
  Pipfile.lock
Labels: gcp-smoke-tests

#3768 Fixing a few OCI bugs
  koku/masu/database/presto_sql/reporting_ocicostentrylineitem_daily_summary.sql
  koku/masu/database/sql/oci/reporting_oci_storage_summary_by_account_p.sql
  koku/masu/database/sql/oci/reporting_oci_storage_summary_p.sql
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/downloader/oci_local/oci_local_report_downloader.py
  koku/masu/test/external/downloader/oci/test_oci_report_downloader.py
  koku/masu/test/external/downloader/oci_local/test_oci_local_report_downloader.py
Labels: smoke-tests, smokes-required

#3772 HCS, GCP data collection
  koku/hcs/database/report_db_accessor.py
  koku/hcs/database/sql/reporting_gcp-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_gcp_hcs_daily_summary.sql
  koku/hcs/tasks.py
Labels: ok-to-skip-smokes

#3725 [Cost-2026]order_by date cannot sort on a day without data
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/oci/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: gcp-smoke-tests, smokes-required

#3775 Fixing notification kafka message
  koku/koku/notifications.py
Labels: smokes-required

#3773 [COST-2838] filter sources object on org_id not account_id
  koku/sources/api/view.py
Labels: smoke-tests, smokes-required
