Repository project-koku/koku, pull requests merged in 2022-11, with the labels that each got.

#3972 [COST-3209] update azure queries to include CCSP data
  koku/hcs/database/sql/reporting_azure-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_azure_hcs_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#3979 fix `Categorical categories cannot be null`
  koku/api/report/queries.py
Labels: hot-fix-smoke-tests, smokes-required

#3981 [COST-2659] - fix sources-cleanup pagination
  koku/masu/api/source_cleanup.py
Labels: smokes-required

#3975 Turn migration file into a no-op for production
  koku/reporting/migrations/0262_standard_numeric_on_calculated_feilds.py
  koku/reporting/provider/all/openshift/models.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/aws/openshift/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/gcp/openshift/models.py
  koku/reporting/provider/oci/models.py
  koku/reporting/provider/ocp/costs/models.py
Labels: smokes-required

#3957 COST-3050 Repeated update of timestamp for OCI source
  Makefile
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/downloader/oci_local/oci_local_report_downloader.py
  koku/masu/test/external/downloader/oci/test_oci_report_downloader.py
  koku/masu/test/external/downloader/oci_local/test_oci_local_report_downloader.py
Labels: smokes-required, oci-smoke-tests

#3974 [COST-3213] rate limit tasks
  .unleash/flags.json
  koku/koku/settings.py
  koku/masu/processor/__init__.py
  koku/masu/processor/tasks.py
  koku/masu/processor/worker_cache.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/processor/test_worker_cache.py
Labels: smoke-tests, smokes-required

#3980 [COST-3208] add lineitemdescription to aws line items daily
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/reporting/provider/aws/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: aws-smoke-tests, smokes-required

#3937 makefile cleanup
  Makefile
Labels: ok-to-skip-smokes

#3982 [COST-3208] AWS HCS gather CCSP data
  koku/hcs/database/sql/reporting_aws-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_aws_hcs_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#3985 COST-3031: Remove dead panels from grafana dashboard
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#3987 protect key word from project/tag groupby/filtering
  koku/api/report/queries.py
Labels: smoke-tests, smokes-required

#3978 [CI] Update action versions, remove deprecated commands, improve organization
  .github/scripts/check_migrations.sh
  .github/scripts/get_description.sh
  .github/workflows/check-clowdapp.yml
  .github/workflows/ci.yml
  .github/workflows/pre-commit.yml
  .github/workflows/pre-release.yaml
  .github/workflows/required-smokes-labeler.yaml
  .github/workflows/unittests.yml
Labels: ok-to-skip-smokes

#3988 fix OCI serializer order-by
  koku/api/report/oci/serializers.py
Labels: smokes-required

#3986 [COST-3227] - sources: `argument of type NoneType is not iterable`
  koku/sources/sources_http_client.py
Labels: smoke-tests, smokes-required

#3992 [COST-2659] - paginate providers-without-sources
  dev/scripts/create_test_customer.py
  docker-compose.yml
  koku/masu/api/source_cleanup.py
  koku/masu/test/api/test_source_cleanup.py
Labels: smokes-required

#3984 get source details before enqueueing deletion
  koku/sources/kafka_message_processor.py
  koku/sources/test/test_kafka_listener.py
Labels: smoke-tests, smokes-required

#3991 Trino migration for cost_category
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#4000 Fix intermittent test failure when trying to exclude no-option
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: ok-to-skip-smokes

#3994 [COST-3216] - reset the meta data when order_by[date] is used
  koku/api/report/queries.py
  koku/api/report/test/test_views.py
  koku/api/report/view.py
Labels: smoke-tests, smokes-required

#4001 Unittests: reduce the number of users created
  koku/api/forecast/test/test_serializers.py
  koku/api/iam/test/iam_test_case.py
  koku/api/organizations/test/test_serializers.py
  koku/api/report/test/aws/openshift/test_serializers.py
  koku/api/report/test/azure/openshift/test_serializers.py
  koku/api/report/test/azure/test_serializers.py
  koku/api/report/test/gcp/openshift/test_serializers.py
  koku/api/report/test/gcp/test_serializers.py
  koku/api/report/test/oci/test_serializers.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/test_serializers.py
  koku/api/tags/test/test_serializers.py
Labels: ok-to-skip-smokes

#3993 commit after deletes
  koku/api/provider/models.py
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_models.py
  koku/api/provider/test/test_provider_manager.py
  koku/koku/test_provider_delete_cascade.py
  koku/masu/test/api/test_source_cleanup.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_kafka_source_manager.py
Labels: smoke-tests, smokes-required

#3989 Initial sql/api work for 3096
  koku/api/query_params.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/test_serializers.py
  koku/api/test_query_params.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostentrylineitem_daily_summary_back_populate.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_p.sql
  koku/masu/database/sql/azure/openshift/reporting_ocpazure_cost_summary_p.sql
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_cost_summary_p.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_compute_summary_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_cost_summary_by_account_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_cost_summary_by_region_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_cost_summary_by_service_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_cost_summary_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_database_summary_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_network_summary_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpall_storage_summary_pt.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_aws.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_azure.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_gcp.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_aws.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_azure.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_gcp.sql
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_by_node_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_volume_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_volume_summary_p.sql
Labels: smokes-required

#4002 [COST-3009] Get OCP on Cloud Unallocated Cost
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: smokes-required

#4003 Rerun migration for specific schemas
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#4004 default projects startwith
  koku/api/report/queries.py
Labels: smokes-required

#3948 [COST-582] Update Azure libraries to use new authentication
  Pipfile
  Pipfile.lock
  koku/providers/azure/client.py
  koku/providers/azure/provider.py
  koku/providers/test/azure/test_client.py
  koku/providers/test/azure/test_provider.py
  koku/sources/sources_error_message.py
  koku/sources/test/api/test_source_status.py
  koku/sources/test/test_sources_error_message.py
Labels: azure-smoke-tests

#4006 use _delete_from_target to delete api_provider
  koku/api/provider/models.py
Labels: smoke-tests, smokes-required

#4008 fix storage units in reporting_oci_storage_summary_by_account_p
  koku/masu/database/sql/oci/reporting_oci_storage_summary_by_account_p.sql
Labels: smokes-required, oci-smoke-tests

#4011 dependency updates
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4012 Script to remove left over trino partitions
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#4013 [COST-3270] delete managed trino partitions on provider delete
  koku/masu/celery/tasks.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/reporting/models.py
Labels: smoke-tests, smokes-required

#4010 Reenable skipped tests & obsolete COST-2470
  koku/api/report/test/aws/openshift/test_views.py
  koku/api/report/test/ocp/test_views.py
Labels: ok-to-skip-smokes

#3997 Cost 3199: custom lookup to allow nulls to be returned during tag exclusion
  koku/api/report/queries.py
  koku/api/report/test/all/openshift/test_query_handler.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/view.py
  koku/reporting/provider/__init__.py
Labels: smokes-required

#4015 simplify category filtering
  koku/api/report/queries.py
  koku/api/report/test/test_queries.py
Labels: smoke-tests, smokes-required

#4021 fix unleash summary log
  koku/masu/processor/__init__.py
Labels: smokes-required

#4019 Adding special case category filtering
  koku/api/report/all/openshift/provider_map.py
  koku/api/report/aws/openshift/provider_map.py
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: smokes-required

#4018 attempt to fix category filter/exclude logic
  koku/api/report/queries.py
  koku/api/report/test/test_queries.py
Labels: smoke-tests, smokes-required

#4024 fix multiple exclude
  koku/api/query_params.py
  koku/api/report/queries.py
Labels: smoke-tests, smokes-required

#3942 [COST-3016] - Don't gather PVCs when no storage
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#3999 COST-3121 migration for ocp-aws additional cost fields
  koku/reporting/migrations/0264_ocpaws_cost_fields.py
  koku/reporting/provider/aws/openshift/models.py
Labels: migration, smokes-required

#4017 Fix pod credit in the OCP on GCP provider map.
  koku/api/report/gcp/openshift/provider_map.py
Labels: smokes-required

#4016 [COST-3277] Handle `ValueError` raised by Azure libraries
  koku/providers/azure/provider.py
  koku/providers/provider_errors.py
  koku/providers/test/azure/test_provider.py
  koku/sources/sources_error_message.py
Labels: azure-smoke-tests

#4027 Fix missing columns in OCP/GCP table
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3998 trino migration for ocpaws additional cost fields
  scripts/cji_scripts/migrate_trino.py
Labels: trino migration, smokes-required

#4028 fix ocp/gcp node migration
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#4025 [COST-3294] ocp on cloud delete fix
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  scripts/cji_scripts/migrate_trino.py
Labels: smoke-tests, smokes-required

#3930 Cost 3008: Calculate unallocated capacity for the OCP nodes
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data.yml
  dev/scripts/nise_ymls/ocp_on_azure/ocp_static_data.yml
  dev/scripts/nise_ymls/ocp_on_gcp/ocp_static_data.yml
  koku/api/query_handler.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/test_queries.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_p.sql
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
Labels: smokes-required

#4031 COST-3199 (pt3): Tag Exclusions for OCP tables should be an AND.
  koku/api/report/queries.py
Labels: smokes-required

#3990 [COST-3226] - distribute by resource usage (AWS)
  koku/api/report/aws/openshift/provider_map.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/openshift/test_views.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_compute_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_by_account_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_by_region_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_by_service_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_cost_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_database_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_network_summary_p.sql
  koku/masu/database/sql/aws/openshift/reporting_ocpaws_storage_summary_p.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_aws.sql
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpawstags_summary.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_cloud_report_summary_updater.py
  koku/reporting/provider/aws/openshift/models.py
Labels: smokes-required
