Repository project-koku/koku, pull requests merged in 2022-10, with the labels that each got.

#3918 First of the month unittest failures.
  koku/api/report/test/util/nise_data_loader.py
Labels: ok-to-skip-smokes

#3916 [COST-3080] - implement currency for OCI endpoint
  koku/api/report/oci/query_handler.py
Labels: smokes-required

#3919 export DOCKER_BUILDKIT in build-deploy
  build_deploy.sh
Labels: ok-to-skip-smokes

#3904 [COST-3039] Move ProviderInfrastructureMap off of get_or_create in provider_db_accessor
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#3920 [COST-3038] - only get unique count when `count` is a column
  koku/api/report/queries.py
Labels: smokes-required

#3873 [COST-2516] - Currency support for Forecasts
  koku/api/currency/currencies.py
  koku/api/forecast/serializers.py
  koku/api/forecast/views.py
  koku/api/report/serializers.py
  koku/api/settings/utils.py
  koku/cost_models/serializers.py
  koku/forecast/forecast.py
  koku/forecast/test/test_forecast.py
  koku/masu/celery/tasks.py
Labels: smoke-tests, smokes-required

#3909 consolidate docker-compose files
  Makefile
  deploy/hadoop/hadoop-config/core-site.xml
  docker-compose.m1.yml
  docker-compose.yml
  testing/compose_files/docker-compose-m1.yml
  testing/compose_files/docker-compose-trino.yml
Labels: ok-to-skip-smokes

#3854 Cost-444 azure unit tests
  .github/workflows/unittests.yml
  koku/api/provider/test/test_models.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/report/test/all/openshift/test_query_handler.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/ocp/test_views.py
  koku/api/report/test/util/baker_recipes.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/api/settings/test/test_views.py
  koku/api/tags/test/azure/test_azure_tag_query_handler.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
  koku/koku/koku_test_runner.py
  koku/koku/test_provider_delete_cascade.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/external/downloader/aws_local/test_aws_local_report_downloader.py
  koku/masu/test/external/downloader/azure_local/test_azure_local_report_downloader.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/external/downloader/gcp_local/test_gcp_local_report_downloader.py
  koku/masu/test/external/downloader/oci_local/test_oci_local_report_downloader.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/processor/ocp/test_ocp_cloud_report_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/processor/test_report_processor.py
  koku/masu/test/processor/test_report_summary_updater.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/aws/test_common.py
  koku/sources/test/test_kafka_source_manager.py
  tox.ini
Labels: ok-to-skip-smokes

#3862 COST-2992: Add unleash flag to summarize ocp on gcp by node
  .unleash/flags.json
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/processor/__init__.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: smokes-required

#3912 [COST-3007] add node role queries to get nodes and fill in node role on topology
  dev/scripts/nise_ymls/ocp/ocp_on_premise.yml
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data.yml
  dev/scripts/nise_ymls/ocp_on_azure/ocp_static_data.yml
  dev/scripts/nise_ymls/ocp_on_gcp/ocp_static_data.yml
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#3914 Update development setup
  .env.example
  Makefile
  README.rst
  dev/scripts/m1_refresher.sh
  docker-compose.arm.yml
  docker-compose.yml
  docs/koku_setup_on_m1.rst
  docs/rosetta_on_m1.rst
Labels: ok-to-skip-smokes

#3932 [COST-3047] - convert product-code to TextField
  koku/reporting/migrations/0260_productcode_textfields.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/aws/openshift/models.py
Labels: aws-smoke-tests, smokes-required

#3927 Super topo structure + cluster agnostic processing for tag matching.
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcp_matched_tags.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/presto_sql/reporting_ocpaws_matched_tags.sql
  koku/masu/database/presto_sql/reporting_ocpazure_matched_tags.sql
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/util/gcp/common.py
Labels: smoke-tests, smokes-required

#3936 add make clear-trino-data
  Makefile
Labels: ok-to-skip-smokes

#3929 [COST-3104] masu api for ocp on cloud processing
  koku/api/iam/test/iam_test_case.py
  koku/koku/trino_database.py
  koku/masu/api/process_openshift_on_cloud.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/openapi.json
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_process_openshift_on_cloud.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#3939 Letter case fix
  koku/api/user_settings/settings.py
Labels: ok-to-skip-smokes

#3940 trino migration for pod credit
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3943 Fix trino migration for multiple tables.
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3946 trino migration retry logic
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3947 remove prod-sec manifest
  .github/scripts/check_manifest.sh
  .github/workflows/check-manifest.yml
  Makefile
  dev/scripts/create_manifest.py
  koku-manifest
Labels: ok-to-skip-smokes

#3931 COST-3073 - fix oci compute instance usage units
  koku/api/report/oci/provider_map.py
  koku/masu/database/presto_sql/reporting_ocicostentrylineitem_daily_summary.sql
  koku/masu/database/sql/oci/reporting_oci_storage_summary_p.sql
Labels: smokes-required, oci-smoke-tests

#3949 cost-2453 postgres migration
  koku/reporting/migrations/0261_ocpgcpcostlineitemprojectdailysummaryp_pod_credit.py
  koku/reporting/provider/gcp/openshift/models.py
Labels: smokes-required

#3938 Fixing OCP/GCP project credit distribution
  koku/api/report/gcp/openshift/provider_map.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostentrylineitem_daily_summary_back_populate.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/processor/gcp/gcp_report_parquet_processor.py
  koku/masu/util/gcp/common.py
Labels: smoke-tests, smokes-required

#3945 trino migration
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3944 [COST-1408] - currency support
  dev/scripts/clear_testing.py
  koku/api/currency/currencies.py
  koku/api/currency/test/test_utils.py
  koku/api/currency/utils.py
  koku/api/currency/view.py
  koku/api/forecast/serializers.py
  koku/api/forecast/test/test_serializers.py
  koku/api/organizations/test/test_serializers.py
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/api/report/all/openshift/provider_map.py
  koku/api/report/aws/openshift/provider_map.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/oci/provider_map.py
  koku/api/report/oci/query_handler.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/openshift/test_serializers.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/openshift/test_serializers.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/azure/test_serializers.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/openshift/test_serializers.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/gcp/test_serializers.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/oci/test_serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/api/settings/utils.py
  koku/api/tags/test/test_serializers.py
  koku/api/utils.py
  koku/cost_models/serializers.py
  koku/cost_models/test/test_serializers.py
  koku/cost_models/view.py
  koku/forecast/forecast.py
  koku/forecast/test/test_forecast.py
  koku/masu/celery/tasks.py
  koku/masu/test/celery/test_tasks.py
  testing/local_providers/azure_local_0/.gitkeep
  testing/local_providers/azure_local_1/.gitkeep
Labels: smokes-required

#3951 currency settings unleash
  koku/api/settings/settings.py
  koku/api/settings/test/test_views.py
Labels: smoke-tests, smokes-required

#3954 unleash: create fallback function based on development environment
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  koku/api/settings/settings.py
  koku/koku/feature_flags.py
Labels: smoke-tests, smokes-required

#3956 Small Trino migration for OCP/GCP
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3958 [COST-2453] Fix trino migration data type
  scripts/cji_scripts/migrate_trino.py
Labels: trino migration, smokes-required

#3960 Revert "Revert "[COST-1408] - currency support""
  dev/scripts/clear_testing.py
  koku/api/currency/currencies.py
  koku/api/currency/test/test_utils.py
  koku/api/currency/utils.py
  koku/api/currency/view.py
  koku/api/forecast/serializers.py
  koku/api/forecast/test/test_serializers.py
  koku/api/organizations/test/test_serializers.py
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/api/report/all/openshift/provider_map.py
  koku/api/report/aws/openshift/provider_map.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/oci/provider_map.py
  koku/api/report/oci/query_handler.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/openshift/test_serializers.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/openshift/test_serializers.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/azure/test_serializers.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/openshift/test_serializers.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/gcp/test_serializers.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/oci/test_serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/api/settings/utils.py
  koku/api/tags/test/test_serializers.py
  koku/api/utils.py
  koku/cost_models/serializers.py
  koku/cost_models/test/test_serializers.py
  koku/cost_models/view.py
  koku/forecast/forecast.py
  koku/forecast/test/test_forecast.py
  koku/masu/celery/tasks.py
  koku/masu/test/celery/test_tasks.py
  testing/local_providers/azure_local_0/.gitkeep
  testing/local_providers/azure_local_1/.gitkeep
Labels: smokes-required

#3961 OCP/GCP node trino migration
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3962 Updating OCP/GCP sql for node/pod costs
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/presto_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/test/database/test_gcp_report_db_accessor.py
Labels: smokes-required

#3963 [COST-2460] re-enable HCS GCP processing
  koku/hcs/database/sql/reporting_gcp-local_hcs_daily_summary.sql
  koku/hcs/database/sql/reporting_gcp_hcs_daily_summary.sql
  koku/hcs/tasks.py
Labels: gcp-smoke-tests, smokes-required

#3952 unit-testing: create more robust test User
  koku/api/iam/test/iam_test_case.py
Labels: ok-to-skip-smokes

#3933 [COST-3047] - update product-code trino sql
  koku/masu/database/presto_sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/presto_sql/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/util/aws/common.py
  koku/reporting/provider/aws/models.py
Labels: smokes-required

#3955 remove `units` query parameter and refactor serializers
  docs/specs/openapi.json
  koku/api/forecast/serializers.py
  koku/api/forecast/test/test_serializers.py
  koku/api/organizations/serializers.py
  koku/api/organizations/test/test_serializers.py
  koku/api/report/all/openshift/serializers.py
  koku/api/report/aws/openshift/serializers.py
  koku/api/report/aws/serializers.py
  koku/api/report/aws/view.py
  koku/api/report/azure/openshift/serializers.py
  koku/api/report/azure/serializers.py
  koku/api/report/gcp/openshift/serializers.py
  koku/api/report/gcp/serializers.py
  koku/api/report/oci/serializers.py
  koku/api/report/ocp/serializers.py
  koku/api/report/serializers.py
  koku/api/report/test/all/openshift/test_serializers.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/openshift/test_serializers.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/aws/test_views.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/openshift/test_serializers.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/azure/test_serializers.py
  koku/api/report/test/azure/test_views.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/openshift/test_serializers.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/gcp/test_serializers.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/oci/test_serializers.py
  koku/api/report/test/oci/test_views.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/test_serializers.py
  koku/api/report/test/test_views.py
  koku/api/report/view.py
  koku/api/tags/all/openshift/serializers.py
  koku/api/tags/all/openshift/view.py
  koku/api/tags/aws/openshift/serializers.py
  koku/api/tags/aws/openshift/view.py
  koku/api/tags/aws/serializers.py
  koku/api/tags/aws/view.py
  koku/api/tags/azure/openshift/serializers.py
  koku/api/tags/azure/openshift/view.py
  koku/api/tags/azure/serializers.py
  koku/api/tags/azure/view.py
  koku/api/tags/gcp/openshift/serializers.py
  koku/api/tags/gcp/openshift/view.py
  koku/api/tags/gcp/serializers.py
  koku/api/tags/gcp/view.py
  koku/api/tags/oci/serializers.py
  koku/api/tags/oci/view.py
  koku/api/tags/ocp/serializers.py
  koku/api/tags/ocp/view.py
  koku/api/tags/serializers.py
  koku/api/tags/test/test_serializers.py
  koku/api/test_utils.py
  koku/api/utils.py
Labels: smoke-tests, smokes-required

#3965 pr-checks: exit with exit-code
  pr_check.sh
Labels: hot-fix-smoke-tests, smokes-required

#3964 Refactor cost-explorer `order_by[date]`
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/oci/query_handler.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/queries.py
  koku/api/report/view.py
Labels: smoke-tests, smokes-required

#3967 COST-3206: Log SourceNotFoundError as warning
  koku/sources/api/source_status.py
Labels: hot-fix-smoke-tests, smokes-required

#3969 allow duplicates across customers for non-OCP providers
  koku/api/provider/serializers.py
  koku/api/provider/test/test_serializers.py
Labels: smoke-tests, smokes-required

#3973 trino migrations: drop aws-openshift-daily table
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#3971 COST-3130: Update ClowApp with kube-linter ignore for min-three-replicas
  deploy/clowdapp.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-listener.yaml
Labels: smokes-required
