Repository project-koku/koku, pull requests merged in 2022-05, with the labels that each got.

#3616 Small cost model API fixes
  docs/source/specs/openapi.json
  koku/cost_models/test/test_view.py
  koku/cost_models/view.py
Labels: smoke-tests

#3577 [Cost 2466] Add HCS automation into current Cost data pipeline
  koku/hcs/tasks.py
  koku/hcs/test/test_tasks.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: azure-smoke-tests

#3619 _zerofill_rank tune-up
  koku/api/report/queries.py
  koku/api/report/view.py
Labels: pr-check-build, aws-smoke-tests

#3621 Cost 2605 rank summation tune up
  koku/api/report/queries.py
Labels: pr-check-build, aws-smoke-tests

#3624 Adding DB t-shirt size for ephemeral runs
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: smoke-tests

#3626 Bumping masu liveness probe
  deploy/clowdapp.yaml
  deploy/kustomize/patches/masu.yaml
Labels: smoke-tests

#3617 [COST-2602] Update unit handling in Azure SQL
  koku/masu/database/presto_sql/reporting_azurecostentrylineitem_daily_summary.sql
Labels: PR Group 3

#3632 Add org unit to user access check
  koku/api/user_access/view.py
Labels: aws-smoke-tests, PR Group 3

#3634 undo dockerfile change
  Dockerfile
Labels: hot-fix-smoke-tests

#3618 [COST-2603] Add additional fields to AWS daily table
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  scripts/cji_scripts/migrate_trino.py
Labels: aws-smoke-tests, trino migration, PR Group 3

#3633 Cost 2629 retire cascade delete
  koku/masu/processor/aws/aws_report_db_cleaner.py
  koku/masu/processor/azure/azure_report_db_cleaner.py
  koku/masu/processor/gcp/gcp_report_db_cleaner.py
  koku/masu/processor/oci/oci_report_db_cleaner.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/test/processor/azure/test_azure_report_db_cleaner.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
Labels: pr-check-build, smoke-tests

#3635 Updated .dockerignore file to fix issues on static files permissions
  .dockerignore
Labels: hot-fix-smoke-tests

#3644 Added docker-compose file for M1 & created auto-reload workaround of …
  dev/scripts/m1_refresher.sh
  docs/source/koku_setup_on_m1.rst
  testing/compose_files/docker-compose-m1.yml
Labels: hot-fix-smoke-tests

#3647 repopulate ocp ui tables after update_cost_model_costs
  koku/api/report/test/util/model_bakery_loader.py
Labels: ok-to-skip-smokes

#3642 [COST-2635] remove refresh views task
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_models.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/api/report/test/util/nise_data_loader.py
  koku/cost_models/cost_model_manager.py
  koku/cost_models/test/test_cost_model_manager.py
  koku/cost_models/test/test_view.py
  koku/masu/api/update_cost_model_costs.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_update_cost_model_costs.py
  koku/masu/test/processor/test_tasks.py
Labels: PR Group 3, smokes-required

#3646 COST-1293 changed description filter method to allow more than one filter
  koku/cost_models/view.py
Labels: smoke-tests, smokes-required

#3652 [COST-2642] - Allow longer headers in requetsts via gunicorn
  koku/gunicorn_conf.py
Labels: hot-fix-smoke-tests, smokes-required

#3649 Dropping filtering of deleted OUs from query
  koku/api/resource_types/aws_org_unit/view.py
Labels: smokes-required

#3655 Fix sources API check which was missing some resource types.
  koku/api/common/permissions/__init__.py
  koku/api/common/permissions/test/test_provider_access.py
  koku/sources/api/view.py
  koku/sources/test/api/test_view.py
Labels: hot-fix-smoke-tests, smokes-required

#3656 COST-2646 Moved documentation to docs folder & updated all refs to the moved files
  .dockerignore
  README.rst
  dev/scripts/e2e-secrets.yml
  docs/aws.rst
  docs/devtools.rst
  docs/install.rst
  docs/koku_setup_on_m1.rst
  docs/openshift.rst
  docs/source/README.rst
  docs/source/development.rst
  docs/source/index.rst
  docs/sources.rst
  docs/sources/aws.rst
  docs/sources/azure.rst
  docs/sources/gcp.rst
  docs/sources/local.rst
  docs/sources/ocp.rst
  docs/sources/openshift_on_aws.rst
  docs/sources/resource_visibility.rst
  docs/specs/openapi.json
  docs/testing.rst
  docs/users.rst
  koku/api/openapi/test_openapi.py
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#3628 [COST-2595] - Depend only on RBAC permissions with Cost Administrator added to admin_default
  .env.example
  .github/workflows/unittests.yml
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/api/common/permissions/aws_access.py
  koku/api/common/permissions/azure_access.py
  koku/api/common/permissions/cost_models_access.py
  koku/api/common/permissions/gcp_access.py
  koku/api/common/permissions/ibm_access.py
  koku/api/common/permissions/openshift_access.py
  koku/api/common/permissions/openshift_all_access.py
  koku/api/common/permissions/resource_type_access.py
  koku/api/resource_types/aws_accounts/view.py
  koku/api/resource_types/aws_org_unit/view.py
  koku/api/resource_types/aws_regions/view.py
  koku/api/resource_types/aws_services/view.py
  koku/api/resource_types/azure_regions/view.py
  koku/api/resource_types/azure_services/view.py
  koku/api/resource_types/azure_subscription_guid/view.py
  koku/api/resource_types/gcp_accounts/view.py
  koku/api/resource_types/gcp_projects/view.py
  koku/api/resource_types/gcp_regions/view.py
  koku/api/resource_types/gcp_services/view.py
  koku/api/resource_types/openshift_clusters/view.py
  koku/api/resource_types/openshift_nodes/view.py
  koku/api/resource_types/openshift_projects/view.py
  koku/cost_models/view.py
  koku/koku/middleware.py
  koku/koku/settings.py
  koku/sources/api/view.py
  tox.ini
Labels: hot-fix-smoke-tests, smokes-required

#3636 [COST-2562] Use resource level GCP table by default
  koku/providers/gcp/provider.py
  koku/providers/test/gcp/test_provider.py
Labels: PR Group 3, smokes-required

#3662 Updated documentation for M1 Mac
  docs/koku_setup_on_m1.rst
  docs/rosetta_on_m1.rst
Labels: ok-to-skip-smokes

#3665 add indices to ocp label keys
  koku/reporting/migrations/0255_ocp_label_indices.py
  koku/reporting/provider/ocp/models.py
Labels: hot-fix-smoke-tests, smokes-required

#3670 Tweaking source update-save
  koku/providers/gcp/provider.py
Labels: hot-fix-smoke-tests, smokes-required

#3671 Update CODEOWNERS
  .github/CODEOWNERS
Labels: ok-to-skip-smokes

#3673 put codeowners on single line
  .github/CODEOWNERS
Labels: ok-to-skip-smokes

#3650 Cost 2606
  koku/api/organizations/serializers.py
  koku/api/organizations/test/aws/test_views.py
  koku/api/organizations/test/test_serializers.py
  koku/api/report/aws/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/aws/openshift/test_serializers.py
  koku/api/report/test/aws/openshift/test_views.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/aws/test_views.py
  koku/api/report/test/azure/openshift/test_serializers.py
  koku/api/report/test/azure/test_serializers.py
  koku/api/report/test/gcp/openshift/test_serializers.py
  koku/api/report/test/gcp/test_serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/test_serializers.py
  koku/api/tags/test/test_serializers.py
Labels: smoke-tests, smokes-required

#3667 COST-2648 - Increase the max limit for the resource types APIs
  koku/api/common/pagination.py
  koku/api/resource_types/view.py
Labels: smokes-required

#3643 Adding OCI provider map + serializers
  koku/api/common/permissions/oci_access.py
  koku/api/report/oci/__init__.py
  koku/api/report/oci/provider_map.py
  koku/api/report/oci/query_handler.py
  koku/api/report/oci/serializers.py
  koku/api/report/oci/view.py
  koku/api/report/queries.py
  koku/api/report/test/oci/__init__.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/oci/test_serializers.py
  koku/api/report/test/oci/test_views.py
  koku/api/tags/__init__.py
  koku/api/tags/oci/__init__.py
  koku/api/tags/oci/queries.py
  koku/api/tags/oci/view.py
  koku/api/tags/serializers.py
  koku/masu/database/oci_report_db_accessor.py
  koku/masu/database/sql/oci/reporting_oci_compute_summary_p.sql
  koku/masu/processor/oci/oci_report_summary_updater.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/test/processor/oci/test_oci_report_summary_updater.py
  koku/reporting/models.py
Labels: smoke-tests, smokes-required

#3668 [COST-2654] - do not build a list of tags to compare against
  koku/api/query_params.py
  koku/api/report/test/test_queries.py
  koku/api/test_query_params.py
Labels: smoke-tests, smokes-required

#3639 COST-2626: Fine tuning our GCP resummary range
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
Labels: smokes-required

#3676 remove filter limit/offset for tags
  koku/api/tags/serializers.py
Labels: smoke-tests, smokes-required
