Repository project-koku/koku, pull requests merged in 2023-09, with the labels that each got.

#4666 update cluster_alias in OCPUsageReportPeriod if the source name changed
  koku/masu/processor/ocp/ocp_report_parquet_processor.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_processor.py
Labels: smoke-tests, smokes-required

#4618 [COST-3609] Return PVCs created by namespace
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/serializers.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/masu/database/sql/openshift/reporting_ocp_volume_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_volume_summary_p.sql
  koku/reporting/migrations/0305_pvc.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#4667 [COST-3572] - actually use the constructed daily archives for OCP
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/_tasks/process.py
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#4651 [COST-4104] Update API spec for new settings APIs
  docs/specs/openapi.json
Labels: smokes-required, ok-to-skip-smokes

#4671 [COST-4070] - clear gcp files for ingress flow
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#4677 [COST-4188] - Allow split azure ingress files
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/processor/__init__.py
  koku/masu/processor/parquet/parquet_report_processor.py
Labels: smoke-tests, smokes-required

#4630 [COST-4033] Use source application.extra.metered value for subs check
  koku/masu/processor/orchestrator.py
  koku/sources/sources_http_client.py
  koku/subs/tasks.py
  koku/subs/test/test_tasks.py
Labels: aws-smoke-tests, smokes-required

#4669 [COST-4168] null storage usage
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data.yml
  koku/api/report/ocp/provider_map.py
Labels: smoke-tests, smokes-required

#4681 update dependencies
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4668 Daily archives minor bug fixes + code cleanup
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/gcp_local/gcp_local_report_downloader.py
  koku/masu/external/downloader/ibm/ibm_report_downloader.py
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#4672 Update CI status badge
  README.md
Labels: ok-to-skip-smokes

#4673 [COST-4178] - (OCP) determine metadata during csv creation
  koku/masu/api/purge_trino_files.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/data/ocp/ros_payload.tar.gz
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#4683 fix: compare integers not integer strings
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#4678 [COST-4109] Start subs processing at midnight day before source creation
  koku/api/utils.py
  koku/subs/subs_data_extractor.py
  koku/subs/tasks.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/test/test_tasks.py
  koku/subs/trino_sql/aws_subs_summary.sql
Labels: aws-smoke-tests, smokes-required

#4685 [COST-4178] use the filename-stem instead of the report-type to track clearing s3
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#4682 Ensure consistent permissions for bind mounts
  .env.example
  .trino/parquet_data/.gitkeep
  .trino/trino/.gitkeep
  Dockerfile.minio
  Makefile
  docker-compose.yml
  pg_data/.gitkeep
Labels: ok-to-skip-smokes

#4675 [COST-4182] Return status code 412 when enabled tags limit is exceeded
  docs/specs/openapi.json
  koku/api/settings/tags/view.py
  koku/api/settings/test/tags/test_api.py
Labels: smoke-tests, smokes-required

#4688 [COST-4185] Make ROS presigned URL timeout configurable
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/listener.yaml
  koku/masu/config.py
  koku/masu/external/ros_report_shipper.py
Labels: smoke-tests, smokes-required

#4567 Create new Provider Managers and remove `CURAccountsInterface`, `CURAccountsDB`, `AccountsAccessor`
  koku/api/provider/models.py
  koku/api/provider/test/test_models.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/koku/settings.py
  koku/koku/test_notifications.py
  koku/masu/api/bigquery_cost.py
  koku/masu/api/crawl_account_hierarchy.py
  koku/masu/api/purge_trino_files.py
  koku/masu/celery/tasks.py
  koku/masu/config.py
  koku/masu/database/provider_billing_source_db_accessor.py
  koku/masu/database/provider_collector.py
  koku/masu/exceptions.py
  koku/masu/external/__init__.py
  koku/masu/external/accounts/cur_accounts_interface.py
  koku/masu/external/accounts/db/__init__.py
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/external/accounts_accessor.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_bigquery_cost.py
  koku/masu/test/api/test_crawl_account_hierarchy.py
  koku/masu/test/api/test_purge_trino_files.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/database/test_provider_billing_source_db_accessor.py
  koku/masu/test/database/test_provider_collector.py
  koku/masu/test/external/accounts/db/__init__.py
  koku/masu/test/external/accounts/db/test_cur_accounts_db.py
  koku/masu/test/external/test_accounts_accessor.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
  koku/masu/util/gcp/common.py
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#4676 [COST-4208] remove `CustomerDBAccessor` and `ProviderAuthDBAccessor`
  koku/masu/database/customer_db_accessor.py
  koku/masu/database/provider_auth_db_accessor.py
  koku/masu/providers/__init__.py
  koku/masu/test/database/test_customer_db_accessor.py
  koku/masu/test/database/test_provider_auth_db_accessor.py
  koku/masu/test/database/test_provider_db_accessor.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#4689 [COST-4209] enable OCP polling ingest only when DEBUG is true
  koku/api/provider/models.py
  koku/api/provider/test/test_models.py
Labels: smoke-tests, smokes-required

#4690 [COST-4209] Fix Masu download endpoint query params
  koku/api/provider/models.py
  koku/masu/api/download.py
  koku/masu/celery/tasks.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#4694 [COST-4209] remove schedule flag from orchestrator
  koku/api/provider/models.py
  koku/koku/celery.py
  koku/masu/api/download.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#4693 just delete bucket contents
  Makefile
  docker-compose.yml
Labels: ok-to-skip-smokes

#4703 Add schema name to the provider map
  koku/api/organizations/aws/provider_map.py
  koku/api/organizations/aws/queries.py
  koku/api/report/all/openshift/provider_map.py
  koku/api/report/all/openshift/query_handler.py
  koku/api/report/aws/openshift/provider_map.py
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/openshift/query_handler.py
  koku/api/report/azure/provider_map.py
  koku/api/report/azure/query_handler.py
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/openshift/query_handler.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/gcp/query_handler.py
  koku/api/report/oci/provider_map.py
  koku/api/report/oci/query_handler.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/provider_map.py
  koku/api/report/test/ocp/test_views.py
  koku/api/tags/all/openshift/queries.py
  koku/api/tags/aws/openshift/queries.py
  koku/api/tags/aws/queries.py
  koku/api/tags/azure/openshift/queries.py
  koku/api/tags/azure/queries.py
  koku/api/tags/gcp/openshift/queries.py
  koku/api/tags/gcp/queries.py
  koku/api/tags/oci/queries.py
  koku/api/tags/ocp/queries.py
  koku/forecast/forecast.py
Labels: smoke-tests, smokes-required

#4702 [COST-4231] - handle empty OCP daily file
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
Labels: smoke-tests, smokes-required

#4679 [COST-4110] Handle duplicate usage ids from subs processing
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/reporting/migrations/0306_subsidmap.py
  koku/reporting/models.py
  koku/reporting/provider/models.py
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/trino_sql/aws_subs_summary.sql
Labels: aws-smoke-tests, smokes-required
