Repository project-koku/koku, pull requests merged in 2023-10, with the labels that each got.

#4687 [COST-3083] - enable volume labels on OCP cost endpoint
  .unleash/flags.json
  koku/api/report/ocp/provider_map.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_views.py
  koku/api/report/test/util/baker_recipes.py
  koku/masu/database/sql/openshift/cost_model/default_infrastructure_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/default_supplementary_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/infrastructure_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/monthly_cost_cluster_and_node.sql
  koku/masu/database/sql/openshift/cost_model/monthly_cost_node_by_tag.sql
  koku/masu/database/sql/openshift/cost_model/monthly_cost_persistentvolumeclaim.sql
  koku/masu/database/sql/openshift/cost_model/monthly_cost_persistentvolumeclaim_by_tag.sql
  koku/masu/database/sql/openshift/cost_model/supplementary_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/usage_costs.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary_update_enabled_tags.sql
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/processor/__init__.py
  koku/reporting/migrations/0308_ocpusagelineitemdailysummary_all_labels.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#4696 Improve PostgreSQL and minio container builds
  .env.example
  Dockerfile.minio
  Makefile
  dev/containers/postgresql/99_postgresql_conf.sh
  dev/containers/postgresql/Dockerfile
  docker-compose.yml
Labels: ok-to-skip-smokes

#4692 [COST-4198] Order by pvc & storage_class
  koku/api/report/ocp/serializers.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/test_serializers.py
Labels: smoke-tests, smokes-required

#4711 [COST-4263] add sources-psk to priority worker
  deploy/clowdapp.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
Labels: hot-fix-smoke-tests, smokes-required

#4712 make the tag population a no-op
  koku/reporting/migrations/0308_ocpusagelineitemdailysummary_all_labels.py
Labels: hot-fix-smoke-tests, smokes-required

#4716 Turn fallback on for all labels unleash flag.
  koku/masu/processor/__init__.py
Labels: ocp-smoke-tests, smokes-required

#4644 [COST-4120] Fix capacity instance counts.
  koku/api/report/ocp/dataclasses/__init__.py
  koku/api/report/ocp/dataclasses/cluster_capacity.py
  koku/api/report/ocp/dataclasses/node_capacity.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/test_dataclasses.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: smoke-tests, ocp-smoke-tests, smokes-required

#4670 [COST-3797] Deprecate Settings endpoint
  .unleash/flags.json
  koku/api/common/deprecate_view.py
  koku/api/deprecated_settings/__init__.py
  koku/api/deprecated_settings/default_settings.py
  koku/api/deprecated_settings/settings.py
  koku/api/deprecated_settings/test/__init__.py
  koku/api/deprecated_settings/test/test_utils.py
  koku/api/deprecated_settings/test/test_views.py
  koku/api/deprecated_settings/utils.py
  koku/api/deprecated_settings/view.py
  koku/api/settings/serializer.py
  koku/api/settings/settings.py
  koku/api/settings/test/test_utils.py
  koku/api/settings/test/test_views.py
  koku/api/settings/utils.py
  koku/api/settings/views.py
  koku/api/test_utils.py
  koku/api/urls.py
  koku/api/user_settings/settings.py
  koku/api/user_settings/test/test_views.py
  koku/api/utils.py
  koku/api/views.py
  koku/koku/middleware.py
  koku/koku/test_middleware.py
  koku/masu/processor/__init__.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#4721 Fix flags.json
  .unleash/flags.json
Labels: ok-to-skip-smokes

#4715 Improve logging around ocp on cloud summary dates.
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
Labels: smoke-tests, smokes-required

#4720 [COST-4257] Fix unused percentage for first days of the month.
  koku/api/report/ocp/capacity/__init__.py
  koku/api/report/ocp/capacity/cluster_capacity.py
  koku/api/report/ocp/capacity/node_capacity.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/test_dataclasses.py
Labels: smoke-tests, smokes-required

#4719 Bump the worker timout for large customers
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#4722 unpin Pandas and dependencies update
  Pipfile
  Pipfile.lock
  koku/masu/util/aws/aws_post_processor.py
  koku/masu/util/oci/oci_post_processor.py
Labels: smoke-tests, smokes-required

#4724 Adding cache timeout params
  deploy/clowdapp.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
Labels: hot-fix-smoke-tests, smokes-required

#4725 Add storage class filter, and lax serializer checks.
  dev/scripts/nise_ymls/ocp/ocp_on_premise.yml
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/serializers.py
  koku/api/report/test/ocp/test_serializers.py
Labels: smoke-tests, smokes-required

#4454 More info on what celery tasks are in queue
  koku/masu/api/running_celery_tasks.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/celery/tasks.py
  koku/masu/test/api/test_running_celery_tasks.py
  koku/masu/test/celery/test_tasks.py
Labels: smoke-tests, smokes-required

#4727 add the ability to purge a specific queue of tasks
  koku/masu/api/running_celery_tasks.py
  koku/masu/test/api/test_running_celery_tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#4713 [COST-4242] process and track metered RHEL by resource id
  koku/reporting/migrations/0309_auto_20231004_1009.py
  koku/reporting/provider/models.py
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/trino_sql/aws_subs_summary.sql
Labels: aws-smoke-tests, smokes-required

#4718 [COST-4268] Do not attempt creating a new cluster without cluster_id
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_summary_updater.py
Labels: smoke-tests, smokes-required

#4708 [COST-4235] Properly handle null values in the tags settings API
  koku/api/settings/aws_category_keys/view.py
  koku/api/settings/tags/view.py
  koku/api/settings/test/tags/test_api.py
  koku/api/settings/utils.py
Labels: smoke-tests, smokes-required

#4699 [COST-4224] Only read currency API data from a good response
  koku/masu/celery/tasks.py
  koku/masu/test/celery/test_tasks.py
Labels: smoke-tests, smokes-required

#4705 [COST-4315] - upgrade local and ephemeral to Postgres 14
  .github/postgres/docker-compose.yaml
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  dev/containers/postgresql/Dockerfile
  docker-compose.yml
  koku/masu/test/api/test_db_performance.py
Labels: smoke-tests, smokes-required

#4731 [COST-4252] Add tag counts to meta in GET response
  koku/api/settings/tags/view.py
  koku/api/settings/test/tags/test_api.py
Labels: smoke-tests, smokes-required

#4736 [COST-4028] drop OCPPodSummaryByNodeP table
  koku/reporting/migrations/0310_delete_ocppodsummarybynodep.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#4737 [COST-4028] recreate OCPPodSummaryByNodeP as partitioned table
  koku/reporting/migrations/0301_create_ocppod_by_node_p.py
  koku/reporting/migrations/0310_delete_ocppodsummarybynodep.py
  koku/reporting/migrations/0311_create_ocppod_by_node_p.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#4740 [COST-4328] Fix subs vCPU trino filter and ensure columns exist on aws_line_items table
  koku/reporting/provider/aws/models.py
  koku/subs/trino_sql/aws_subs_summary.sql
Labels: aws-smoke-tests, smokes-required

#4741 [COST-4028] - redo table drop and create
  koku/reporting/migrations/0301_create_ocppod_by_node_p.py
  koku/reporting/migrations/0311_actually_delete_ocppodsummarybynodep.py
  koku/reporting/migrations/0312_create_ocppod_by_node_p.py
Labels: hot-fix-smoke-tests, smokes-required

#4742 [COST-4028] make migrations no-op
  koku/reporting/migrations/0301_create_ocppod_by_node_p.py
  koku/reporting/migrations/0310_delete_ocppodsummarybynodep.py
  koku/reporting/migrations/0311_actually_delete_ocppodsummarybynodep.py
Labels: hot-fix-smoke-tests, smokes-required

#4745 [COST-4328] Fix where clause SQL and check for results before attempting to upload
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
Labels: hot-fix-smoke-tests, smokes-required

#4739 [COST-3341] Add 'cost_type' param in OCP AWS Forecas Report
  koku/api/common/pagination.py
  koku/api/forecast/views.py
Labels: smoke-tests, smokes-required

#4738 Add a unittest to ensure django models are partitioned in postgres.
  koku/masu/test/database/test_partitions.py
Labels: ok-to-skip-smokes

#4744 [COST-4331] Parse tags for ELS not EUS and use ID 204 if ELS is present for SUBS processing
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/subs/trino_sql/aws_subs_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#4735 [COST-4289] - Skip OCP clusters without a matching billing report date for OCP on Cloud processing
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#4747 [COST-4345] delete ReportingCommonDBAccessor and region_map tests
  koku/masu/database/reporting_common_db_accessor.py
  koku/masu/test/api/test_region_map.py
  koku/masu/test/data/test_region_page.html
  koku/masu/test/database/test_reporting_common_db_accessor.py
Labels: smoke-tests

#4749 [COST-4350] delete AccountAliasAccessor, AWSAccountAlias, AccountLabel
  koku/masu/database/account_alias_accessor.py
  koku/masu/external/account_label.py
  koku/masu/external/accounts/labels/__init__.py
  koku/masu/external/accounts/labels/aws/__init__.py
  koku/masu/external/accounts/labels/aws/aws_account_alias.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_account_alias_accessor.py
  koku/masu/test/external/accounts/labels/__init__.py
  koku/masu/test/external/accounts/labels/aws/__init__.py
  koku/masu/test/external/accounts/labels/aws/test_aws_account_alias.py
  koku/masu/test/external/test_account_label.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#4748 [COST-4346] replace ReportStatsDBAccessor with Django methods
  koku/masu/database/report_stats_db_accessor.py
  koku/masu/external/downloader/downloader_interface.py
  koku/masu/external/downloader/ibm/ibm_report_downloader.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/aws_local/test_aws_local_report_downloader.py
  koku/masu/test/external/downloader/azure_local/test_azure_local_report_downloader.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/external/downloader/test_report_downloader_base.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/test/processor/test_expired_data_remover.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/providers/__init__.py
  koku/masu/test/providers/test_report_stats_db_accessor.py
  koku/reporting_common/models.py
  koku/reporting_common/test_reporting_common.py
Labels: smoke-tests, smokes-required

#4728 RHIROS-1292 Make ROS OCP API spec available under Cost-Mgmt API doc
  docs/specs/openapi.json
Labels: smoke-tests

#4752 Deprecation documentation
  docs/team_workflows/deprecating_an_endpoint.md
Labels: ok-to-skip-smokes
