Repository project-koku/koku, pull requests merged in 2023-05, with the labels that each got.

#4334 [COST-3554] Add line item type to AWS line items daily table
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/reporting/provider/aws/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: smoke-tests, trino migration, smokes-required

#4347 PVC_DIR cleanup
  testing/data/.gitkeep
  testing/data/insights_local/.gitkeep
Labels: ok-to-skip-smokes

#4337 [COST-3720] Update confluent kafka and don't create a new producer every time
  Pipfile
  Pipfile.lock
  koku/kafka_utils/test/test_utils.py
  koku/kafka_utils/utils.py
  koku/koku/notifications.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#4345 [COST-3774] duplicate violates pod label constraint.
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
Labels: smokes-required

#4348 [COST-3702] remove unused _get_associated_tags
  koku/api/report/aws/query_handler.py
  koku/api/report/aws/serializers.py
  koku/api/report/gcp/serializers.py
  koku/api/report/oci/serializers.py
  koku/api/report/test/aws/test_queries.py
Labels: smokes-required

#4351 Change authorization header format for Unleash 4
  koku/koku/feature_flags.py
Labels: ok-to-skip-smokes

#4353 Revert "Change authorization header format for Unleash 4"
  koku/koku/feature_flags.py
Labels: smokes-required, ok-to-skip-smokes

#4354 move logic into try/except
  koku/masu/processor/orchestrator.py
Labels: smokes-required

#4355 Remove scheduled task that removes stale tenants
  koku/koku/celery.py
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#4357 move ROS unleash gate to prevent kafka message only
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/external/test_ros_report_shipper.py
Labels: smokes-required

#4352 [COST-3779] Sentry: None is not a valid integer literal
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/azure/azure_report_parquet_summary_updater.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
  koku/masu/test/processor/azure/test_azure_report_parquet_summary_updater.py
Labels: smoke-tests, smokes-required

#4344 [COST-3554] Calculate and store AWS amortized cost
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#4341 Get celery hostname without using regexp
  koku/masu/processor/worker_cache.py
Labels: smoke-tests, smokes-required

#4358 Add AWS cache to cost categories resource-types
  koku/api/resource_types/aws_category/view.py
  koku/api/urls.py
Labels: aws-smoke-tests, smokes-required

#4349 [COST-3769] Add unleash flag to disable a source.
  .unleash/flags.json
  koku/koku/feature_flags.py
  koku/masu/processor/__init__.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: smokes-required

#4359 [COST-3790] Remove negative filtering unleash flag.
  .unleash/flags.json
  koku/api/query_params.py
  koku/api/report/test/all/openshift/test_query_handler.py
  koku/api/report/test/aws/openshift/test_ocp_aws_query_handler.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/azure/openshift/test_ocp_azure_query_handler.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/oci/test_oci_query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/test_query_params.py
Labels: smokes-required

#4363 COST-3748: Filtering on disabled aws category key.
  koku/api/report/aws/openshift/query_handler.py
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/test_queries.py
Labels: smoke-tests, smokes-required

#4343 [COST-3773] Properly update group by data when there is overlap between groups
  koku/api/report/queries.py
  koku/api/report/test/test_queries.py
Labels: smoke-tests, smokes-required

#4369 Re-enable generic ocp-gcp tag matching
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
Labels: smoke-tests, smokes-required

#4290 [COST-3685] Move post processor logic into its own provider specific class.
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/util/aws/test_aws_post_processor.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_azure_post_processor.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/gcp/test_gcp_post_processor.py
  koku/masu/test/util/oci/test_common.py
  koku/masu/test/util/oci/test_oci_post_processor.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/test/util/ocp/test_ocp_post_processor.py
  koku/masu/util/aws/aws_post_processor.py
  koku/masu/util/aws/common.py
  koku/masu/util/azure/azure_post_processor.py
  koku/masu/util/azure/common.py
  koku/masu/util/common.py
  koku/masu/util/gcp/common.py
  koku/masu/util/gcp/gcp_post_processor.py
  koku/masu/util/oci/common.py
  koku/masu/util/oci/oci_post_processor.py
  koku/masu/util/ocp/common.py
  koku/masu/util/ocp/ocp_post_processor.py
Labels: smokes-required

#4350 [COST-3783] ocp on azure UI summary via trino
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_compute_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_location_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_database_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_network_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_storage_summary_p.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: azure-smoke-tests, smokes-required

#4366 [COST-3800] Handle invalid data in OCP order by serializer
  koku/api/report/ocp/serializers.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/ocp/test_views.py
Labels: smoke-tests, smokes-required

#4375 Automatically append a slash to URLs
  koku/api/urls.py
  koku/koku/settings.py
  koku/sources/api/urls.py
Labels: smoke-tests, smokes-required

#4379 adding report definition retry logic
  koku/masu/util/aws/common.py
Labels: smokes-required

#4372 [COST-3817] Fix cluster capacity annotations in daily view
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: bug, smoke-tests, smokes-required

#4371 [COST-3801] Account for values that can be None
  koku/api/utils.py
Labels: smoke-tests, smokes-required

#4367 [COST-3788] Migration to remove duplicate OCP clusters
  koku/reporting/migrations/0278_ocpcluster_remove_duplicates.py
Labels: smoke-tests, django migration, smokes-required

#4380 [COST-3784] Switching OCP on AWS summary to Trino
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_compute_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_region_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_database_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_network_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_storage_summary_p.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: smokes-required

#4386 Change authorization header format for Unleash 4
  koku/koku/feature_flags.py
Labels: hot-fix-smoke-tests, smokes-required

#4373 [COST-3809] external id when using assume role
  koku/masu/external/account_label.py
  koku/masu/external/accounts/hierarchy/aws/aws_org_unit_crawler.py
  koku/masu/external/accounts/labels/aws/aws_account_alias.py
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/test/external/accounts/hierarchy/aws/test_aws_org_unit_crawler.py
  koku/masu/test/external/accounts/labels/aws/test_aws_account_alias.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/test_account_label.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/providers/aws/provider.py
  koku/providers/test/aws/test_aws_provider.py
  koku/sources/test/api/test_source_status.py
  koku/sources/test/test_kafka_source_manager.py
Labels: aws-smoke-tests, smokes-required

#4384 [COST-3788] Migration to add constraints to OCP tables
  koku/reporting/migrations/0279_ocp_alter_unique_together.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, django migration, smokes-required

#4390 Update local development version of Unleash
  .env.example
  .gitleaks.toml
  docker-compose.yml
  docs/devtools.md
Labels: ok-to-skip-smokes

#4397 [COST-2077] replace pytz with zoneinfo
  koku/api/query_handler.py
  koku/api/test_utils.py
  koku/api/utils.py
  koku/koku/settings.py
  koku/koku/test_json_transcode.py
  koku/koku/test_provider_delete_cascade.py
  koku/masu/api/hcs_report_data.py
  koku/masu/external/date_accessor.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/processor/aws/aws_report_parquet_processor.py
  koku/masu/processor/azure/azure_report_parquet_processor.py
  koku/masu/processor/expired_data_remover.py
  koku/masu/processor/gcp/gcp_report_parquet_processor.py
  koku/masu/processor/oci/oci_report_parquet_processor.py
  koku/masu/processor/ocp/ocp_report_parquet_processor.py
  koku/masu/test/api/test_update_cost_model_costs.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/external/test_date_accessor.py
  koku/masu/test/processor/aws/test_aws_report_db_cleaner.py
  koku/masu/test/processor/azure/test_azure_report_db_cleaner.py
  koku/masu/test/processor/gcp/test_gcp_report_db_cleaner.py
  koku/masu/test/processor/oci/test_oci_report_db_cleaner.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
  koku/masu/test/processor/test_expired_data_remover.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/oci/test_common.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#4388 Dependency update
  Dockerfile
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4377 [COST-3827] Make masu sources PATCH api for external id
  koku/masu/api/sources/serializers.py
  koku/masu/api/sources/test/test_serializers.py
  koku/masu/api/sources/test/test_views.py
  koku/masu/api/sources/views.py
  koku/masu/openapi.json
  koku/masu/test/__init__.py
Labels: smoke-tests, smokes-required

#4402 [COST-3688] update Orchestrator logs
  koku/api/common/__init__.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: hot-fix-smoke-tests, smokes-required

#4378 [COST-3554] Add column to store amortized cost with markup
  koku/api/report/test/util/baker_recipes.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/aws/reporting_aws_compute_summary_by_account_p.sql
  koku/masu/database/sql/aws/reporting_aws_compute_summary_p.sql
  koku/masu/database/sql/aws/reporting_aws_cost_summary_by_account_p.sql
  koku/masu/database/sql/aws/reporting_aws_cost_summary_by_region_p.sql
  koku/masu/database/sql/aws/reporting_aws_cost_summary_by_service_p.sql
  koku/masu/database/sql/aws/reporting_aws_cost_summary_p.sql
  koku/masu/database/sql/aws/reporting_aws_database_summary_p.sql
  koku/masu/database/sql/aws/reporting_aws_network_summary_p.sql
  koku/masu/database/sql/aws/reporting_aws_storage_summary_by_account_p.sql
  koku/masu/database/sql/aws/reporting_aws_storage_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_compute_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_region_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_database_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_network_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_storage_summary_p.sql
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/reporting/migrations/0280_markup_amortized_cost.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/aws/openshift/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: smoke-tests, django migration, trino migration, smokes-required

#4403 [COST-3688] update celery task logs
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/test_tasks.py
Labels: hot-fix-smoke-tests, smokes-required
