Repository project-koku/koku, pull requests merged in 2023-12, with the labels that each got.

#4774 [COST-4367] Add product_vcpu to aws_line_items_daily
  koku/masu/test/util/aws/test_aws_post_processor.py
  koku/masu/util/aws/aws_post_processor.py
  scripts/cji_scripts/migrate_trino.py
Labels: aws-smoke-tests, trino migration, smokes-required

#4814 Temporary disable upload of results to Report portal
  smoke_test.sh
Labels: ok-to-skip-smokes

#4816 [COST-4334] - Adding dtypes for AWS
  koku/masu/util/aws/aws_post_processor.py
  koku/reporting/provider/aws/models.py
Labels: aws-smoke-tests, smokes-required

#4819 [COST-4360] - Adding dtypes for OCI
  koku/masu/util/oci/oci_post_processor.py
  koku/reporting/provider/oci/models.py
Labels: smokes-required, oci-smoke-tests

#4820 [COST-4230] - log warning when operator payload is set to basic auth
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#4823 [COST-4489] add uniqueness constraint on the ProviderInfraMap table
  koku/api/migrations/0061_alter_providerinfrastructuremap_unique_together.py
  koku/api/provider/models.py
Labels: smoke-tests, smokes-required

#4815 [COST-4335] - Adding dtypes for OCP
  koku/masu/util/ocp/ocp_post_processor.py
Labels: hot-fix-smoke-tests, smokes-required

#4817 [COST-4333] - Adding dtypes for Azure
  koku/masu/database/trino_sql/azure/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/test/util/azure/test_azure_post_processor.py
  koku/masu/util/azure/azure_post_processor.py
  koku/reporting/provider/azure/models.py
Labels: hot-fix-smoke-tests, smokes-required

#4824 [COST-4333] Fix OCP on Azure matching by resource-ids
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/azure/common.py
Labels: azure-smoke-tests, smokes-required

#4826 [COST-4481] use StringDtype(storage="pyarrow")
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#4827 [COST-4230] - add cluster-id to basic auth log message
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: hot-fix-smoke-tests, smokes-required

#4401 [COST-3794] Add new API for managing custom cost groups
  koku/api/query_filter.py
  koku/api/report/test/util/common.py
  koku/api/settings/cost_groups/__init__.py
  koku/api/settings/cost_groups/query_handler.py
  koku/api/settings/cost_groups/serializers.py
  koku/api/settings/cost_groups/view.py
  koku/api/settings/serializers.py
  koku/api/settings/test/cost_groups/__init__.py
  koku/api/settings/test/cost_groups/test_query_handler.py
  koku/api/settings/test/cost_groups/test_serializers.py
  koku/api/settings/views.py
  koku/api/urls.py
  koku/api/views.py
  koku/reporting/provider/__init__.py
Labels: smoke-tests, smokes-required

#4831 [COST-3814] Add Azure source processing to subs flow
  Pipfile
  Pipfile.lock
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  docker-compose.yml
  koku/koku/settings.py
  koku/providers/azure/client.py
  koku/subs/subs_data_extractor.py
  koku/subs/subs_data_messenger.py
  koku/subs/tasks.py
  koku/subs/test/__init__.py
  koku/subs/test/test_subs_data_messenger.py
  koku/subs/trino_sql/aws_subs_pre_or_clause.sql
  koku/subs/trino_sql/azure_subs_pre_or_clause.sql
Labels: aws-smoke-tests, smokes-required

#4834 [COST-3814] Add metered to the azure sources extras
  koku/sources/sources_http_client.py
Labels: hot-fix-smoke-tests, smokes-required

#4835 [COST-3814] Check instanceid column instead of instancename
  koku/subs/subs_data_extractor.py
  koku/subs/trino_sql/azure_subs_pre_or_clause.sql
Labels: azure-smoke-tests, smokes-required

#4836 [COST-3814] Azure subs processing start 2 days prior to source creation
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
Labels: aws-smoke-tests, smokes-required

#4812 [COST-4367] Update HCS AWS SQL
  koku/hcs/database/sql/reporting_aws_hcs_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#4830 [COST-4360] Fix default dtypes mapping for OCI
  koku/reporting/provider/oci/models.py
Labels: smoke-tests, smokes-required

#4840 [COST-3814] Add 1s to Azure last processed time
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
Labels: hot-fix-smoke-tests, smokes-required

#4838 [COST-4440] Warn when a partition already exists for OCP processing
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#4843 [COST-4532] Rename field that contains the OpenShift project name
  koku/api/settings/cost_groups/query_handler.py
  koku/api/settings/cost_groups/serializers.py
  koku/api/settings/cost_groups/view.py
  koku/api/settings/test/cost_groups/test_query_handler.py
  koku/api/settings/test/cost_groups/test_serializers.py
Labels: hot-fix-smoke-tests, smokes-required

#4829 [COST-3394] Add documentation for cost groups API
  docs/specs/openapi.json
Labels: smoke-tests, smokes-required
