Repository project-koku/koku, pull requests merged in 2023-11, with the labels that each got.

#4755 [COST-4378] update README to add Rancher Desktop
  README.md
Labels: ok-to-skip-smokes

#4700 [COST-4215] utilize kafka msg handler to ingest local OCP
  Pipfile.lock
  dev/scripts/load_test_customer_data.sh
  docker-compose.yml
  koku/masu/api/ingest_ocp_payload.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/api/test_ingest_ocp_payload.py
Labels: smoke-tests, smokes-required

#4605 [COST-4377] Remove deprecated tag models.
  koku/reporting/migrations/0313_remove_deprecated_tags.py
  koku/reporting/models.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/oci/models.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#4758 Revert "[COST-4289] - Skip OCP clusters without a matching billing report date for OCP on Cloud processing"
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: hot-fix-smoke-tests, smokes-required

#4759 add schema context to a couple of log messages.
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#4757 Applying string (str) type when reading CSV and its tests
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/test/data/aws/2023-06-01.csv
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
Labels: aws-smoke-tests, smokes-required

#4761 Add a quick rancher doc about restarting celery worker.
  docs/celery.md
Labels: ok-to-skip-smokes

#4762 Applying str data type to the reading CSV to avoid leading zeros bug.
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/test/data/azure/costreport_a243c6f2-199f-4074-9a2c-40e671cf1584.csv
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
Labels: smoke-tests, azure-smoke-tests, smokes-required

#4763 [COST-4405] support case insensitive queries for user-access endpoints
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
Labels: smoke-tests, smokes-required

#4732 add remote attach option for celery pods and auto-reload celery
  .env.example
  docker-compose.yml
  docs/vscode-debugging.md
  koku/koku/celery.py
  koku/masu/management/commands/restart_celery.py
Labels: smoke-tests, smokes-required

#4768 [COST-4028] - data migration
  dev/scripts/load_test_customer_data.sh
  koku/reporting/migrations/0314_ocppod_by_node_p_data_migration.py
Labels: smoke-tests, smokes-required

#4751 Remove AWS CCSP data from HCS Filter
  koku/hcs/database/sql/reporting_aws_hcs_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#4571 [COST-4028] utilize OCPPodSummaryByNodeP in query handler
  koku/api/report/ocp/provider_map.py
  koku/reporting/migrations/0314_ocppod_by_node_p_data_migration.py
Labels: smoke-tests, smokes-required

#4773 [COST-4429] Case insensitive special case tag matching
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#4771 add debug log level example to the .env.example
  .env.example
Labels: ok-to-skip-smokes

#4767 [COST-4210] remove ProviderDBAccessor from Masu APIs
  koku/masu/api/additional_context.py
  koku/masu/api/crawl_account_hierarchy.py
  koku/masu/api/hcs_report_data.py
  koku/masu/api/report_data.py
  koku/masu/test/api/test_additional_context.py
  koku/masu/test/api/test_hcs_report_data.py
  koku/masu/test/api/test_report_data.py
Labels: smoke-tests, smokes-required

#4765 [COST-4375] delete IngressReportDBAccessor
  koku/api/ingress/test/reports/test_serializers.py
  koku/api/ingress/test/reports/test_views.py
  koku/masu/database/ingress_report_db_accessor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_ingress_reports.py
  koku/masu/test/database/test_ingress_report_db_accessor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/processor/test_tasks.py
  koku/providers/provider_access.py
  koku/reporting/ingress/models.py
Labels: smoke-tests, smokes-required

#4775 [COST-4364] Applying string (str) data type when reading CSV (OCP)
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
Labels: smoke-tests, smokes-required

#4778 [COST-4346] stop download attempt on CostUsageReportStatus.DoesNotExist
  koku/masu/external/report_downloader.py
  koku/masu/test/external/test_report_downloader.py
Labels: smoke-tests, smokes-required

#4764 Add instrumentation to `start_manifest_processing`
  koku/masu/processor/orchestrator.py
Labels: hot-fix-smoke-tests, smokes-required

#4779 Applying string (str) data type when reading CSV (OCI)
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/test/data/oci/reports_cost-csv_0001000000603747.csv
  koku/masu/test/external/downloader/oci/test_oci_report_downloader.py
Labels: smoke-tests, smokes-required

#4766 [COST-4210] - remove ProviderDBAccessor for notifications and utils
  koku/api/iam/test/iam_test_case.py
  koku/api/provider/models.py
  koku/api/provider/provider_manager.py
  koku/koku/notifications.py
  koku/koku/test_notifications.py
  koku/masu/api/additional_context.py
  koku/masu/celery/tasks.py
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/oci/test_common.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/test/util/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/aws/insert_aws_org_tree.py
  koku/masu/util/azure/common.py
  koku/masu/util/common.py
  koku/masu/util/gcp/common.py
  koku/masu/util/oci/common.py
Labels: smoke-tests, smokes-required

#4777 Applying string (str) data type when reading CSV (GCP)
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
Labels: smoke-tests, smokes-required

#4776 [COST-4430] Handle service account in API identity header
  koku/koku/middleware.py
  koku/koku/test_middleware.py
Labels: smoke-tests, smokes-required

#4781 Revert [COST-4002] remove empty-status as requirement to create provider (#4575)
  koku/sources/storage.py
Labels: hot-fix-smoke-tests, smokes-required

#4783 [COST-4429] Add missing lower to azure tags for OCP on Azure
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#4784 [COST-4442] - Pass JOB_NAME and BUILD_NUMBER to IQE CJI's
  Jenkinsfile
  pg_data/.gitkeep
  smoke_test.sh
Labels: ok-to-skip-smokes

#4733 fix OCP post processor volume labels
  koku/masu/test/util/ocp/test_ocp_post_processor.py
  koku/masu/util/ocp/ocp_post_processor.py
Labels: smoke-tests, smokes-required

#4508 [COST-3962] Add docs on Trino Migrations and validate dropped tables are external tables.
  docs/devtools.md
  scripts/cji_scripts/migrate_trino.py
Labels: hot-fix-smoke-tests, smokes-required

#4788 [COST-4446] - suppress `missing cluster-id` alert
  koku/api/iam/test/iam_test_case.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_parquet_summary_updater.py
  koku/masu/test/processor/test_report_summary_updater.py
Labels: smoke-tests, smokes-required

#4790 [COST-4452] catch and log foreign key violation as warning
  koku/koku/celery.py
Labels: smoke-tests, smokes-required

#4785 [COST-4430] Support service account source creation and payload ingress
  koku/api/provider/provider_builder.py
  koku/koku/middleware.py
  koku/sources/config.py
  koku/sources/test/test_kafka_source_manager.py
Labels: ocp-smoke-tests, smokes-required

#4787 [COST-4445] unlink ReportManifestDBAccessor from KokuDBAccess
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_oci_report_db_accessor.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/test_report_downloader_base.py
  koku/masu/test/processor/test_report_summary_updater.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#4792 [COST-4210] remove ProviderDBAccessor
  koku/api/provider/models.py
  koku/masu/database/provider_db_accessor.py
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/database/test_provider_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: smoke-tests, smokes-required

#4786 [COST-4445] simplify OCPReportDBAccessor
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cost_model_cost_updater.py
Labels: smoke-tests, smokes-required

#4795 [COST-4463] MSK: multi-broker support
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  docs/testing.md
  koku/api/status/serializers.py
  koku/kafka_utils/test/test_utils.py
  koku/kafka_utils/utils.py
  koku/koku/configurator.py
  koku/koku/notifications.py
  koku/masu/config.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/management/commands/listener.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/sources/api/status.py
  koku/sources/config.py
  koku/sources/kafka_listener.py
  koku/sources/kafka_message_processor.py
  koku/sources/management/commands/sources_listener.py
  koku/sources/test/api/test_status.py
  koku/sources/test/test_kafka_listener.py
  koku/subs/subs_data_messenger.py
Labels: smoke-tests, smokes-required

#4760 [COST-4385] cleanup local OCP ingest
  koku/api/provider/models.py
  koku/api/provider/test/test_models.py
  koku/masu/external/downloader/ocp/__init__.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/report_downloader.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/data/ocp/434eda91-885b-40b2-8733-7a21fad62b56_namespace_labels.csv
  koku/masu/test/data/ocp/e6b3701e-1e91-433b-b238-a31e49937558_February-2019-my-ocp-cluster-1.csv
  koku/masu/test/data/ocp/e6b3701e-1e91-433b-b238-a31e49937558_node_labels.csv
  koku/masu/test/data/ocp/e6b3701e-1e91-433b-b238-a31e49937558_storage.csv
  koku/masu/test/data/ocp/manifest.json
  koku/masu/test/data/ocp/payload2.tar.gz
  koku/masu/test/data/ocp/payload2/manifest.json
  koku/masu/test/external/downloader/ocp/__init__.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#4796 [COST-4445] ReportDBAccessorBase cleanup
  koku/api/status/serializers.py
  koku/hcs/test/database/test_report_db_accessor.py
  koku/masu/config.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/engine.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/oci_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_mini_transaction_delete.py
  koku/masu/test/database/test_oci_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/external/test_ros_report_shipper.py
  koku/masu/test/processor/aws/test_aws_report_db_cleaner.py
  koku/masu/test/processor/azure/test_azure_report_db_cleaner.py
  koku/masu/test/processor/gcp/test_gcp_report_db_cleaner.py
  koku/masu/test/processor/oci/test_oci_report_db_cleaner.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/ocp/test_common.py
  koku/reporting_common/__init__.py
  koku/reporting_common/test_reporting_common.py
Labels: smoke-tests, smokes-required

#4770 Script to check postgres/trino data integrity
  dev/scripts/data_integrity.py
  docs/devtools.md
Labels: ok-to-skip-smokes

#4797 [COST-4464] Add ROS debug var to enable ROS processing in eph
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/listener.yaml
  docker-compose.yml
  koku/koku/settings.py
  koku/masu/external/ros_report_shipper.py
Labels: smoke-tests, smokes-required

#4798 [COST-4445] delete KokuDBAccess
  koku/masu/celery/tasks.py
  koku/masu/database/cost_model_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/koku_database_access.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/test/database/test_mini_transaction_delete.py
Labels: smoke-tests, smokes-required

#4800 [COST-4443] Update data model for cost groups.
  koku/reporting/migrations/0315_openshiftcostcategorynamespace.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#4802 Update functions.sh
  ci/functions.sh
Labels: ok-to-skip-smokes

#4803 Update functions.sh
  ci/functions.sh
Labels: ok-to-skip-smokes

#4801 [COST-4444] update processing to point to new model.
  koku/api/tags/queries.py
  koku/masu/database/sql/openshift/cost_model/monthly_cost_node_by_tag.sql
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#4804 Update openapi.json
  docs/specs/openapi.json
Labels: hot-fix-smoke-tests, smokes-required

#4807 [SWATCH-1779] - Enable result upload to Report portal for daily eph job
  smoke_test.sh
Labels: ok-to-skip-smokes

#4810 [COST-4445] GCP delete regression
  koku/masu/database/gcp_report_db_accessor.py
Labels: gcp-smoke-tests, smokes-required

#4799 Make ROS OCP API available in koku openapi.json
  docs/specs/openapi.json
Labels: ok-to-skip-smokes

#4811 update dependencies
  Pipfile.lock
  koku/masu/test/util/gcp/test_common.py
  koku/masu/util/gcp/common.py
Labels: smoke-tests, smokes-required
