Repository project-koku/koku, pull requests merged in 2023-07, with the labels that each got.

#4529 [COST-3883] Fixing Start date for Azure/AWS
  koku/api/test_utils.py
  koku/api/utils.py
  koku/masu/test/processor/test_tasks.py
Labels: smokes-required

#4528 add operator versions for engineering metrics reports
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#4534 [COST-3847] Use new unleash flag for rate limiting a large customer
  koku/masu/processor/__init__.py
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#4527 Adds Dev docs for RBAC
  docs/rbac.md
Labels: ok-to-skip-smokes

#4536 [COST-3688] Update extract context method
  koku/masu/database/report_db_accessor_base.py
Labels: smokes-required

#4535 [COST-3864] batching polling
  .env.example
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/api/migrations/0060_provider_polling_timestamp.py
  koku/api/provider/models.py
  koku/koku/celery.py
  koku/masu/config.py
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/external/accounts/db/test_cur_accounts_db.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#4541 more makefile updates
  Makefile
Labels: ok-to-skip-smokes

#4543 update django and scipy
  Pipfile.lock
Labels: smokes-required

#4531 [COST-3965] Update logs for AWS processor.
  koku/masu/processor/aws/aws_cost_model_cost_updater.py
  koku/masu/processor/aws/aws_report_db_cleaner.py
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
Labels: smokes-required

#4547 [COST-3864] Dropping OCP from scheduled polling
  koku/koku/celery.py
  koku/masu/api/download.py
  koku/masu/external/accounts/db/cur_accounts_db.py
  koku/masu/external/accounts_accessor.py
  koku/masu/processor/orchestrator.py
Labels: hot-fix-smoke-tests, smokes-required

#4548 [COST-2665] Clowder now applying annotations from deployment spec level
  deploy/clowdapp.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
Labels: smoke-tests, smokes-required

#4549 Set default download scheduled param to false
  koku/masu/api/download.py
Labels: smokes-required

#4542 [COST-3963] Enable order_by for subscription_name with Azure
  koku/api/report/azure/query_handler.py
  koku/api/report/azure/serializers.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/test_serializers.py
Labels: smoke-tests, smokes-required

#4550 Improve oci error message
  koku/providers/oci/provider.py
Labels: smokes-required

#4554 add pid to log messages
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#4555 [COST-3864] adding logging to batch
  koku/masu/external/accounts/db/cur_accounts_db.py
Labels: smokes-required

#4510 [COST-3969] Update logs in OCP processor
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/processor/ocp/ocp_report_parquet_processor.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: ocp-smoke-tests, smokes-required

#4545 [COST-3998] update logging in masu/util - common
  koku/masu/util/common.py
Labels: smokes-required

#4558 [COST-3963] Fix Azure annotation of subscription name when group_by present and not ordered by name
  koku/api/report/azure/query_handler.py
Labels: smoke-tests, smokes-required

#4537 Fix openapi.json by adding parameters to put.
  docs/specs/openapi.json
Labels: smokes-required

#4526 [COST-3978] Modify RBAC settings to handle read & write for new apis
  koku/api/common/permissions/settings_access.py
  koku/api/common/permissions/test/test_settings_access.py
  koku/api/settings/test/aws_category_keys/test_view.py
  koku/api/settings/view.py
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/api/user_settings/test/test_views.py
  koku/api/user_settings/views.py
Labels: smokes-required

#4551 [COST-4000] Add env var to control tag limit.
  .env.example
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  docker-compose.yml
  docs/devtools.md
  koku/masu/config.py
Labels: smokes-required

#4560 [COST-3963] Fix condition for adding subscrption_name annotation
  koku/api/report/azure/query_handler.py
Labels: smoke-tests, smokes-required

#4564 add more logging
  koku/masu/external/accounts/db/cur_accounts_db.py
Labels: smokes-required

#4568 Fix polling seconds
  koku/masu/external/accounts/db/cur_accounts_db.py
Labels: hot-fix-smoke-tests, smokes-required

#4566 do not log pvcs, nodes, projects
  koku/masu/database/ocp_report_db_accessor.py
Labels: smokes-required

#4563 delete report_processor_base.py which is unused
  koku/masu/processor/report_processor_base.py
Labels: ok-to-skip-smokes

#4553 increasing group by limit to 3
  .env.example
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  docker-compose.yml
  koku/api/report/all/openshift/serializers.py
  koku/api/report/aws/openshift/serializers.py
  koku/api/report/aws/serializers.py
  koku/api/report/serializers.py
  koku/koku/settings.py
  koku/masu/processor/__init__.py
Labels: hot-fix-smoke-tests, smokes-required

#4572 [COST-4028] migration and sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_node_p.sql
  koku/reporting/migrations/0301_create_ocppod_by_node_p.py
  koku/reporting/provider/ocp/models.py
Labels: smokes-required

#4569 scale base resources below what we have set in stage
  deploy/clowdapp.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/nginx.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-priority.yaml
Labels: smoke-tests, smokes-required

#4574 [COST-4002] Add check for provider in source status flow
  koku/providers/provider_errors.py
  koku/sources/api/source_status.py
  koku/sources/test/api/test_source_status.py
Labels: smoke-tests, smokes-required

#4577 fix unleash flag for XL customers
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#4578 Remove deprecation for rbac setting
  koku/api/common/permissions/settings_access.py
  koku/api/common/permissions/test/test_settings_access.py
  koku/api/settings/view.py
  koku/api/user_settings/test/test_views.py
  koku/api/user_settings/views.py
Labels: smoke-tests, smokes-required

#4585 Update settings if condition.
  koku/api/common/permissions/settings_access.py
Labels: hot-fix-smoke-tests, smokes-required

#4581 [COST-4026] Correct refresh XL queue name
  koku/masu/prometheus_stats.py
Labels: smokes-required

#4573 use `inclause` sqljinja filter in templates
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcptags_summary.sql
  koku/masu/database/sql/oci/reporting_ocicostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/oci/reporting_ocienabledtagkeys.sql
  koku/masu/database/sql/oci/reporting_ocitags_summary.sql
  koku/masu/database/sql/reporting_awscategory_summary.sql
  koku/masu/database/sql/reporting_awscostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_awsenabledtagkeys.sql
  koku/masu/database/sql/reporting_awstags_summary.sql
  koku/masu/database/sql/reporting_azurecostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_azureenabledtagkeys.sql
  koku/masu/database/sql/reporting_azuretags_summary.sql
  koku/masu/database/sql/reporting_gcpcostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_gcpenabledtagkeys.sql
  koku/masu/database/sql/reporting_gcptags_summary.sql
  koku/masu/database/sql/reporting_ocpawstags_summary.sql
  koku/masu/database/sql/reporting_ocpazuretags_summary.sql
  koku/masu/database/sql/reporting_ocpstoragevolumelabel_summary.sql
  koku/masu/database/sql/reporting_ocpusagelineitem_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
Labels: smokes-required

#4583 [COST-3896] bump nise version to include subs columns in test data
  Pipfile.lock
  dev/scripts/nise_ymls/org_tree_aws_static_data.yml
Labels: hot-fix-smoke-tests, smokes-required

#4552 [COST-3984] Do not update summary tables if there are no AWS bills
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/masu/util/aws/common.py
  koku/masu/util/azure/common.py
  koku/masu/util/gcp/common.py
  koku/masu/util/oci/common.py
Labels: ocp-smoke-tests, smokes-required

#4586 Add settings to rbac python file.
  koku/api/common/permissions/settings_access.py
  koku/koku/rbac.py
  koku/koku/test_rbac.py
Labels: hot-fix-smoke-tests, smokes-required

#4570 [COST-3990] Add write check to user_access endpoint
  koku/api/user_access/test/test_view.py
  koku/api/user_access/view.py
  koku/koku/test_middleware.py
Labels: smoke-tests, smokes-required

#4546 [COST-3572] handle daily operator payloads
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/ocp/ocp_report_downloader.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/processor/worker_cache.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/ocp/test_ocp_report_downloader.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/processor/test_report_processor.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/ocp/common.py
  koku/reporting_common/migrations/0034_costusagereportmanifest_operator_daily_files.py
  koku/reporting_common/models.py
Labels: smoke-tests, django migration, smokes-required

#4582 [COST-3891/COST-3893] Add workers for SUBS data extraction and transmission
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/kustomization.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  docker-compose.yml
  koku/masu/prometheus_stats.py
Labels: smoke-tests, smokes-required

#4579 [COST-4026] Update Grafana dashboard for XL queue
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#4591 [COST-4044] log schema_name rather than customer id
  koku/masu/external/accounts/db/cur_accounts_db.py
Labels: hot-fix-smoke-tests, smokes-required

#4589 [COST-3808] add external-id to sources integration
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/providers/aws/provider.py
  koku/providers/test/aws/test_aws_provider.py
  koku/sources/sources_http_client.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_sources_http_client.py
Labels: aws-smoke-tests, smokes-required

#4593 Revert "[COST-3891/COST-3893] Add workers for SUBS data extraction a…
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/kustomization.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  docker-compose.yml
  koku/masu/prometheus_stats.py
Labels: hot-fix-smoke-tests, smokes-required

#4592 Just for Eva
  ci/functions.sh
  pr_check.sh
Labels: gcp-smoke-tests, smokes-required

#4594 [COST-3975] Create new model to hold all tags
  koku/reporting/migrations/0302_unified_enabledtags.py
  koku/reporting/models.py
  koku/reporting/provider/all/models.py
  tox.ini
Labels: hot-fix-smoke-tests, smokes-required

#4596 Deprecate pr_check.sh script
  ci/functions.sh
  pr_check.sh
Labels: hot-fix-smoke-tests

#4597 [COST-3891/COST-3893] Add workers for SUBS data extraction and transmission
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/kustomization.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  docker-compose.yml
  koku/masu/prometheus_stats.py
Labels: smoke-tests, smokes-required

#4598 [COST-3996] Unleash flag to disable tag enablement on settings.
  .unleash/flags.json
  koku/api/settings/settings.py
  koku/masu/processor/__init__.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#4601 bump oci, certifi, cryptography
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4556 [COST-3890/3892] Data Extraction and Kafka Messaging for SUBS
  Makefile
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  docker-compose.yml
  koku/api/provider/models.py
  koku/koku/settings.py
  koku/masu/celery/tasks.py
  koku/masu/config.py
  koku/masu/processor/orchestrator.py
  koku/masu/util/aws/common.py
  koku/reporting/migrations/0304_subslastprocessed.py
  koku/reporting/models.py
  koku/reporting/provider/models.py
  koku/subs/__init__.py
  koku/subs/subs_data_extractor.py
  koku/subs/subs_data_messenger.py
  koku/subs/tasks.py
  koku/subs/test/__init__.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/test/test_subs_data_messenger.py
  koku/subs/test/test_tasks.py
  koku/subs/trino_sql/aws_subs_summary.sql
Labels: aws-smoke-tests, smokes-required
