Repository project-koku/koku, pull requests merged in 2023-04, with the labels that each got.

#4264 Small unit test fix
  koku/masu/test/api/test_update_cost_model_costs.py
Labels: ok-to-skip-smokes

#4251 adding additional AWS column logic
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/common.py
Labels: aws-smoke-tests, smokes-required

#4248 Update dependencies
  Pipfile
  Pipfile.lock
Labels: smoke-tests

#4265 pin watchtower and re-lock
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4266 removing currency unleash flag
  koku/api/settings/settings.py
  koku/api/settings/test/test_views.py
Labels: smoke-tests, smokes-required

#4242 [COST-3561] Correct path to OCI archived data
  koku/masu/celery/tasks.py
  koku/masu/util/oci/common.py
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#4234 [COST-3649] Migration to collect aws category for type ahead.
  koku/reporting/migrations/0275_aws_category_tables.py
  koku/reporting/provider/aws/models.py
Labels: django migration, smokes-required

#4268 lock FOR UPDATE
  koku/masu/database/sql/reporting_ocpstoragevolumelabel_summary.sql
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
Labels: smokes-required

#4270 remove `metrics` from webServices
  deploy/clowdapp.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/nginx.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
Labels: hot-fix-smoke-tests, smokes-required

#4267 [COST-3664] Allow customers to enable/disable aws cost categories.
  koku/api/report/test/util/model_bakery_loader.py
  koku/api/settings/settings.py
  koku/api/settings/test/test_views.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/data/test_cur.csv
  koku/masu/test/data/test_cur.csv.gz
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/oci/test_common.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/azure/common.py
  koku/masu/util/gcp/common.py
  koku/masu/util/oci/common.py
  koku/masu/util/ocp/common.py
  koku/reporting/models.py
Labels: smokes-required

#4271 [COST-3615] Improve AWS category serializer sanity to use enabled fields
  koku/api/query_params.py
  koku/api/report/test/aws/test_views.py
Labels: smokes-required

#4235 [COST-3649] Populate AWS cost category summary table for type ahead
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  dev/scripts/nise_ymls/org_tree_aws_static_data.yml
  dev/scripts/render_templated_sql.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/__init__.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/reporting_awscategory_summary.sql
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
Labels: smokes-required

#4224 [COST-3582] Use today if end_date is earlier than summary_month
  koku/api/test_utils.py
  koku/api/utils.py
  koku/masu/test/api/test_update_cost_model_costs.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#4275 remove PRESTO_HOST and PRESTO_PORT
  README.md
  deploy/clowdapp.yaml
  deploy/koku-cji.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  dev/config.yaml.local-example
  dev/scripts/trino_query.py
  docker-compose.yml
  koku/koku/settings.py
  koku/koku/trino_database.py
  koku/masu/api/trino.py
  koku/masu/processor/report_parquet_processor_base.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#4276 remove references to RabbitMQ
  .env.example
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  docs/specs/openapi.json
  koku/koku/celery.py
  koku/koku/settings.py
  koku/masu/external/kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#4277 Update Trino version used for development
  deploy/trino/etc/catalog/hive.properties
  docker-compose.arm.yml
  docker-compose.yml
Labels: ok-to-skip-smokes

#4278 COST-3682: Fix sonarqube integration
  sonarqube.sh
  sonarqube_exec.sh
Labels: ok-to-skip-smokes

#4280 Handle beta or preview from referer
  koku/koku/middleware.py
Labels: hot-fix-smoke-tests, smokes-required

#4282 remove references to RabbitMQ
  docker-compose.yml
Labels: ok-to-skip-smokes

#4284 remove set nounset in sonarqube script
  sonarqube.sh
Labels: ok-to-skip-smokes

#4285 sonarqube: print each command the sonarqube script executes
  sonarqube.sh
Labels: ok-to-skip-smokes

#4286 sonarqube: compare gitBranch to origin/main
  sonarqube.sh
Labels: ok-to-skip-smokes

#4292 [COST-3702] sonarqube: remove old code with raw sql generation
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/report_processor_base.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_aws_report_db_accessor.py
Labels: smoke-tests, smokes-required

#4291 [COST-3700] - sonarqube: remove unused code which uses pseudorandom num…
  koku/api/report/test/__init__.py
  koku/api/report/test/aws/test_queries.py
Labels: ok-to-skip-smokes

#4289 [COST-3699] - sonarqube: replace expression with iterable
  koku/koku/database_exc.py
Labels: smokes-required

#4297 [COST-3705] schema exists check
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smokes-required

#4281 [COST-3687] - sonarqube: Refactor statements with no side effects
  koku/api/organizations/queries.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: smokes-required

#4298 [COST-3710] - sonarqube: remove redundant exception
  koku/masu/api/status.py
Labels: hot-fix-smoke-tests, smokes-required

#4296 remove NiseDataLoader since we are fully transitioned to the ModelBakeryDataLoader
  koku/api/report/test/util/nise_data_loader.py
Labels: ok-to-skip-smokes

#4288 [COST-3692] - sonarqube: use argument before reassigning
  dev/scripts/create_sources.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#4301 COST-3614: Correct url for aws-categories endpoint
  koku/api/urls.py
Labels: hot-fix-smoke-tests, smokes-required

#4302 [COST-3713] - sonarqube: setup sonarcloud
  .github/workflows/ci.yml
  sonar-project.properties
Labels: ok-to-skip-smokes

#4299 Remove codecov and update README
  Pipfile
  Pipfile.lock
  README.md
  tox.ini
Labels: smoke-tests, smokes-required

#4305 [COST-3710] - sonarcloud: remove redundant exception
  koku/masu/api/status.py
Labels: hot-fix-smoke-tests, smokes-required

#4309 [COST-3713] more sonarcloud test inclusion/exclusion
  sonar-project.properties
Labels: ok-to-skip-smokes

#4310 [COST-3614] Add filter options to aws category resource types endpoint.
  docs/specs/openapi.json
  koku/api/resource_types/aws_category/view.py
  koku/api/resource_types/test/aws_category/test_views.py
  koku/api/settings/settings.py
Labels: hot-fix-smoke-tests, smokes-required

#4306 Adding year month partitions to Trino temp table SQL
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/reporting/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: smokes-required

#4312 [COST-3720] pin confluent-kafka version
  Pipfile
  Pipfile.lock
Labels: smokes-required

#4315 Fixing old GCP sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
Labels: gcp-smoke-tests, smokes-required

#4304 [COST-3711] Order by distributed cost
  koku/api/report/ocp/query_handler.py
  koku/api/report/ocp/serializers.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/ocp/test_views.py
Labels: smokes-required

#4176 [COST-3558] Remove old processing tables
  koku/api/report/test/azure/test_azure_query_handler.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/koku/database.py
  koku/koku/test_provider_delete_cascade.py
  koku/masu/database/__init__.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/azure/azure_report_parquet_summary_updater.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/oci/oci_report_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/processor/report_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_db_performance.py
  koku/masu/test/api/test_db_performance_views.py
  koku/masu/test/database/helpers.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_cost_model_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_oci_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/aws/test_aws_report_db_cleaner.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
  koku/masu/test/processor/azure/test_azure_report_db_cleaner.py
  koku/masu/test/processor/azure/test_azure_report_parquet_summary_updater.py
  koku/masu/test/processor/gcp/test_gcp_report_db_cleaner.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
  koku/masu/test/processor/oci/test_oci_report_db_cleaner.py
  koku/masu/test/processor/oci/test_oci_report_parquet_summary_updater.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/ocp/test_common.py
  koku/reporting/models.py
  koku/reporting_common/__init__.py
  koku/reporting_common/test_reporting_common.py
Labels: smokes-required

#4314 [COST-3539] masu task process daily partitioned OCP on Cloud Parquet
  koku/masu/api/process_openshift_on_cloud.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_process_openshift_on_cloud.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#4321 Removing unneeded log message from OCI SQL flow
  koku/masu/database/oci_report_db_accessor.py
Labels: smokes-required

#4320 Fix container not found sentry error
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
Labels: smokes-required

#4318 COST-3733: Fix order by distributed_cost for ranked list.
  koku/api/report/ocp/query_handler.py
  koku/api/report/ocp/serializers.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/ocp/test_views.py
Labels: smokes-required

#4316 [COST-3728] Remove rows when distribute overhead disabled
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/distribute_platform_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_worker_cost.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smokes-required

#4323 Add key_only param to aws category resource types
  docs/specs/openapi.json
  koku/api/resource_types/aws_category/serializers.py
  koku/api/resource_types/aws_category/view.py
  koku/api/resource_types/test/aws_category/test_views.py
Labels: smokes-required

#4325 [COST-3648] Fix dropped pod labels from OCP on cloud resource matching
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_by_node.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#4307 [COST-3714] Check if ROS report is in current payload before trying to process
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/data/ocp/ros_payload.tar.gz
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smokes-required

#4326 sonarcloud: use tmp directory for data
  Makefile
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary.yaml
  dev/scripts/clear_testing.py
  dev/scripts/load_test_customer_data.sh
  docker-compose.yml
  koku/api/status/serializers.py
  koku/koku/celery.py
  koku/masu/celery/tasks.py
  koku/masu/config.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/_tasks/download.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/test_tasks.py
  sonarqube.sh
Labels: smoke-tests, smokes-required

#4327 [COST-3748] return empty list when accessing a disabled aws category key
  koku/api/query_params.py
Labels: smoke-tests, smokes-required

#4330 [COST-3534] replace empty string group by value to No-{group by}
  koku/api/report/queries.py
  koku/api/report/test/test_queries.py
Labels: smokes-required

#4311 [COST-3558] Migrations to remove old Postgres raw data tables
  koku/reporting/migrations/0276_auto_20230303_1947.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/gcp/models.py
  koku/reporting/provider/ocp/models.py
Labels: smokes-required

#4331 Add a flag to show if overhead cost is distributed.
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: smoke-tests, smokes-required

#4324 [COST-3746] limit distributed_cost param to only group by project
  koku/api/report/ocp/query_handler.py
  koku/api/report/ocp/serializers.py
  koku/api/report/provider_map.py
  koku/api/report/queries.py
  koku/api/report/test/ocp/test_serializers.py
  koku/api/report/test/ocp/test_views.py
Labels: smokes-required

#4332 [CI] Move SonarCloud to separate workflow
  .github/workflows/ci.yml
  .github/workflows/sonarcloud.yml
Labels: ok-to-skip-smokes

#4322 Add more pieces to dev tools docs
  docs/devtools.md
Labels: ok-to-skip-smokes

#4333 [CI] Revert Move SonarCloud to separate workflow
  .github/workflows/ci.yml
  .github/workflows/sonarcloud.yml
Labels: ok-to-skip-smokes

#4336 sonarcloud: add duplicate lines exclusions
  sonar-project.properties
Labels: ok-to-skip-smokes

#4335 [COST-3715] Handle unexpected error message data type
  koku/providers/provider_errors.py
  koku/sources/sources_error_message.py
  koku/sources/test/test_sources_error_message.py
Labels: smoke-tests, smokes-required

#4263 [COST-3554] Create column for storing calculated value
  koku/reporting/migrations/0277_store_aws_amoritized_cost.py
  koku/reporting/provider/aws/models.py
  koku/reporting/provider/aws/openshift/models.py
Labels: smoke-tests, django migration, smokes-required

#4338 [COST-3767] gate ROS shipping with Unleash
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/external/test_ros_report_shipper.py
Labels: smokes-required

#4339 [COST-3767] fix context key
  koku/masu/external/kafka_msg_handler.py
Labels: smokes-required
