Repository project-koku/koku, pull requests merged in 2024-02, with the labels that each got.

#4881 [COST-4602] - Initial migrations adding fields
  koku/reporting_common/migrations/0036_auto_20240129_1604.py
  koku/reporting_common/models.py
Labels: hot-fix-smoke-tests, smokes-required

#4887 fix broken unit tests
  koku/masu/api/upgrade_trino/test/test_view.py
Labels: ok-to-skip-smokes

#4880 [COST-4602] - Code changes to use new manifest and report status fields
  docs/specs/openapi.json
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/masu/api/manifest/serializers.py
  koku/masu/api/manifest/test/test_serializer.py
  koku/masu/api/manifest/views.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/oci/oci_report_downloader.py
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/report_downloader.py
  koku/masu/openapi.json
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/oci/test_oci_report_downloader.py
  koku/masu/test/external/downloader/test_report_downloader_base.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/test/processor/test_expired_data_remover.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting_common/models.py
  koku/reporting_common/test_reporting_common.py
Labels: hot-fix-smoke-tests, smokes-required

#4885 [COST-4602] - Migrate manifest and report data
  koku/reporting_common/migrations/0037_manifest_report_data_migration.py
Labels: hot-fix-smoke-tests, smokes-required

#4884 create .snyk file with exclusions
  .snyk
Labels: ok-to-skip-smokes

#4888 Make `masu.api.upgrade_trino.test.test_view` deterministic
  koku/masu/api/upgrade_trino/test/test_view.py
Labels: ok-to-skip-smokes

#4890 fix ocp provider map regression pod_labels --> all_labels
  koku/api/report/ocp/provider_map.py
Labels: hot-fix-smoke-tests, smokes-required

#4892 Update pillow
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4894 [COST-4631] - remove sonarcloud integration
  .github/workflows/ci.yml
  .gitignore
  Makefile
  README.md
  sonar-project.properties
Labels: ok-to-skip-smokes

#4899 temporarily stop using codecov token
  .github/workflows/ci.yml
Labels: ok-to-skip-smokes

#4898 set max retry for trino connection
  koku/koku/trino_database.py
Labels: smoke-tests, smokes-required

#4900 [COST-3828] Add tag mapping model.
  koku/reporting/migrations/0317_tagmapping.py
  koku/reporting/provider/all/models.py
Labels: hot-fix-smoke-tests, smokes-required

#4902 [COST-4194] replace jinjasql with jinjasql2
  Pipfile
  Pipfile.lock
  dev/scripts/render_templated_sql.py
  koku/koku/database.py
  koku/koku/test_trino_db_utils.py
  koku/koku/trino_database.py
  koku/masu/api/enabled_tags.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#4907 Temp. update daily job to debug potential regression
  smoke_test.sh
Labels: ok-to-skip-smokes

#4909 Revert debugging smoke tests
  smoke_test.sh
Labels: ok-to-skip-smokes

#4910 pin pandas < 2.2
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4903 AWS Tags: Remove an unused code path
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/reporting_awscostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/sql/reporting_awsenabledtagkeys.sql
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/test/database/test_aws_report_db_accessor.py
Labels: aws-smoke-tests, smokes-required

#4896 [COST-4603] - Adding enhanced report status info
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/_tasks/download.py
  koku/masu/processor/_tasks/process.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/external/downloader/aws_local/test_aws_local_report_downloader.py
  koku/masu/test/external/downloader/azure_local/test_azure_local_report_downloader.py
  koku/masu/test/external/test_report_downloader.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/processor/test_report_processor.py
  koku/masu/test/processor/test_report_summary_updater.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting_common/migrations/0038_auto_20240208_1759.py
  koku/reporting_common/models.py
  koku/reporting_common/states.py
  koku/reporting_common/test_reporting_common.py
  koku/sources/api/view.py
Labels: smoke-tests, smokes-required

#4914 [COST-4603] - Minor fix to handle manifest state as null
  koku/masu/database/report_manifest_db_accessor.py
Labels: smoke-tests, smokes-required

#4905 [COST-3829] API to read/update source/target tag mappings
  docs/specs/openapi.json
  koku/api/settings/tags/mapping/__init__.py
  koku/api/settings/tags/mapping/query_handler.py
  koku/api/settings/tags/mapping/serializers.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/__init__.py
  koku/api/settings/test/tags/mappings/test_view.py
  koku/api/urls.py
  koku/api/views.py
Labels: smoke-tests, smokes-required

#4901 [COST-4588] Aws, OCP on Aws tag key mapping.
  .unleash/flags.json
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data.yml
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/aws/aws_tag_mapping_update_daily_summary.sql
  koku/masu/database/sql/aws/openshift/ocpaws_tag_mapping_update_daily_summary.sql
  koku/masu/processor/__init__.py
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/database/test_aws_report_db_accessor.py
Labels: ocp-smoke-tests, smokes-required

#4915 [COST-3749] GCP credits not included in OCP on ALL costs by project
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_gcp.sql
Labels: gcp-smoke-tests, smokes-required

#4917 [COST-4394] Inserting the 'TB_MS' clause in WHEN
  koku/masu/database/trino_sql/reporting_ocicostentrylineitem_daily_summary.sql
  koku/masu/test/data/oci/reports_usage-csv_0001000000829494.csv
  koku/masu/test/database/test_oci_report_db_accessor.py
Labels: smoke-tests, smokes-required

#4912 [COST-4602] remove redundant code prior to migration
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/report_downloader_base.py
  koku/masu/processor/_tasks/process.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/processor/test_tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#4919 [COST-4219] - Fix wrongly updated manifest state
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#4918 [COST-4394] Removing unrelated unit test
  koku/masu/test/database/test_oci_report_db_accessor.py
Labels: ok-to-skip-smokes

#4920 Remove aws org unit load from load-test-customer-data.
  Makefile
Labels: ok-to-skip-smokes

#4897 [COST-4589] Correctly get end of month data for Azure Metering
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/trino_sql/aws/determine_ids_for_provider.sql
  koku/subs/trino_sql/aws/determine_resource_ids_for_usage_account.sql
  koku/subs/trino_sql/aws/subs_row_count.sql
  koku/subs/trino_sql/aws/subs_summary.sql
  koku/subs/trino_sql/azure/determine_ids_for_provider.sql
  koku/subs/trino_sql/azure/determine_resource_ids_for_usage_account.sql
  koku/subs/trino_sql/azure/subs_row_count.sql
  koku/subs/trino_sql/azure/subs_summary.sql
Labels: azure-smoke-tests, smokes-required

#4844 [COST-2231] Upgrade to Django 4
  Pipfile
  Pipfile.lock
  db_functions/clone_schema.sql
  koku/api/common/__init__.py
  koku/api/dataexport/syncer/__init__.py
  koku/api/dataexport/validators.py
  koku/api/iam/models.py
  koku/api/iam/test/iam_test_case.py
  koku/api/iam/test/test_clone_schema.py
  koku/api/metrics/views.py
  koku/api/provider/serializers.py
  koku/api/query_params.py
  koku/api/report/aws/serializers.py
  koku/api/report/oci/serializers.py
  koku/api/report/ocp/serializers.py
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/ocp/test_views.py
  koku/api/settings/views.py
  koku/cost_models/view.py
  koku/koku/cache.py
  koku/koku/database.py
  koku/koku/migration_sql_helpers.py
  koku/koku/settings.py
  koku/koku/test_middleware.py
  koku/masu/api/enabled_tags.py
  koku/masu/api/manifest/views.py
  koku/masu/external/accounts/hierarchy/aws/aws_org_unit_crawler.py
  koku/masu/management/commands/migrate_serial_to_identity_columns.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/api/test_db_performance_views.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/aws/test_aws_post_processor.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/test/util/gcp/test_gcp_post_processor.py
  koku/masu/test/util/oci/test_oci_post_processor.py
  koku/masu/test/util/ocp/test_ocp_post_processor.py
  koku/providers/aws/provider.py
  koku/providers/oci/provider.py
  koku/providers/test/aws/test_aws_provider.py
  koku/providers/test/oci/test_oci_provider.py
  koku/sources/api/view.py
  licenses/Apache-2.0.txt
  licenses/MIT.txt
  tox.ini
Labels: smoke-tests, smokes-required

#4925 add operator versions
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#4922 OCI: Making unit conversion CASE statement cleaner.
  koku/masu/database/trino_sql/reporting_ocicostentrylineitem_daily_summary.sql
Labels: smokes-required, oci-smoke-tests

#4931 Go back to using django-redis
  Pipfile
  Pipfile.lock
  koku/koku/cache.py
  koku/koku/settings.py
Labels: smoke-tests, smokes-required

#4921 [COST-4591] GCP, OCP on GCP tag mapping.
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/sql/gcp/gcp_tag_mapping_update_daily_summary.sql
  koku/masu/database/sql/gcp/openshift/ocpgcp_tag_mapping_update_daily_summary.sql
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: gcp-smoke-tests, smokes-required

#4936 [COST-4682] fix "Infastructure" typo
  koku/masu/database/sql/openshift/cost_model/default_infrastructure_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/infrastructure_tag_rates.sql
Labels: smoke-tests, smokes-required

#4923 [COST-4588] Optimize AWS tag mapping sql
  docs/specs/openapi.json
  koku/masu/database/sql/aws/aws_tag_mapping_update_daily_summary.sql
  koku/masu/database/sql/aws/openshift/ocpaws_tag_mapping_update_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#4882 [COST-4623] - Migration to remove old fields
  koku/reporting_common/migrations/0039_auto_20240213_1715.py
  koku/reporting_common/models.py
Labels: smoke-tests, smokes-required

#4927 [COST-4644] OCP tag key mapping.
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/ocp_tag_mapping_update_daily_summary.sql
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: hot-fix-smoke-tests, smokes-required

#4924 [COST-4423] - Initial work for cluster/source info page
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/api/upgrade_trino/test/test_verify_parquet_files.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/aws/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/azure/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/gcp/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
  koku/masu/util/ocp/common.py
  koku/sources/api/view.py
Labels: smoke-tests, smokes-required

#4943 [COST-4571] Add env vars for delayed summary.
  .env.example
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/koku/settings.py
Labels: hot-fix-smoke-tests, smokes-required

#4940 [COST-4571] Migrations for delayed celery task table
  koku/reporting_common/migrations/0040_delayedcelerytasks.py
  koku/reporting_common/models.py
Labels: hot-fix-smoke-tests, smokes-required

#4942 [COST-4423] update missed sql file for cluster info
  koku/masu/api/sources/serializers.py
  koku/masu/api/sources/test/test_serializers.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/gcp/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: smoke-tests, smokes-required

#4947 [COST-3830] Prevent disabling mapped tags.
  koku/api/settings/tags/view.py
  koku/api/settings/test/tags/test_api.py
Labels: smoke-tests, smokes-required

#4952 [COST-4715] add glitchtip config
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
Labels: hot-fix-smoke-tests, smokes-required

#4953 Fix leap year unittest failures.
  koku/koku/test_pg_partition.py
Labels: ok-to-skip-smokes

#4933 [COST-4571] Mechanism to delay summary for settings
  koku/api/settings/tags/mapping/utils.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_utils.py
  koku/koku/celery.py
  koku/masu/celery/tasks.py
  koku/masu/processor/tasks.py
  koku/reporting_common/test_reporting_common.py
Labels: smoke-tests, smokes-required

#4946 [COST-4713] Handle Azure billingcurrency column
  koku/koku/test_pg_partition.py
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required
