Repository project-koku/koku, pull requests merged in 2024-08, with the labels that each got.

#5241 [COST-5345] EC2 API - exclude tags when exporting to CSV
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/test_queries.py
Labels: smoke-tests, smokes-required

#5218 [COST-4620] - Add basic provider data validation
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-penalty.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-penalty.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-penalty.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-penalty.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-penalty.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/api/test_utils.py
  koku/api/utils.py
  koku/koku/settings.py
  koku/masu/api/urls.py
  koku/masu/api/validate_data.py
  koku/masu/api/views.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/__init__.py
  koku/masu/processor/_tasks/data_validation.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_validate_data.py
  koku/masu/test/processor/test_data_validation.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#5246 test docker compose
  .github/workflows/ci.yml
Labels: ok-to-skip-smokes

#5244 [COST-5367] - Fix Azure ingress required columns
  koku/masu/util/azure/azure_post_processor.py
  koku/masu/util/azure/common.py
Labels: smoke-tests, smokes-required

#5242 [COST-5347] Filter for active providers when expiring Trino partitions
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5245 [COST-5161] - Drop Azure v1 support
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
Labels: hot-fix-smoke-tests, smokes-required

#5217 [COST-5279] Update HCS AWS CCSP Estimate
  koku/hcs/database/sql/reporting_aws_hcs_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5243 [COST-5357] Fully distribute Storage unattributed costs to user projects
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5249 [COST-5367] Add RG vs sub column support
  koku/masu/test/util/azure/test_azure_post_processor.py
  koku/masu/util/azure/azure_post_processor.py
  koku/masu/util/azure/common.py
Labels: smoke-tests, smokes-required

#5248 [COST-4820] Remove all_label unleash flag
  koku/api/report/ocp/provider_map.py
  koku/api/report/test/ocp/view/test_views.py
  koku/masu/processor/__init__.py
Labels: ocp-smoke-tests, smokes-required

#5228 [COST-5255] Update Azure instance id and send display name for subs
  dev/scripts/nise_ymls/ocp_on_azure/azure_static_data.yml
  koku/subs/subs_data_extractor.py
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/test/test_subs_data_messenger.py
  koku/subs/trino_sql/azure/determine_resource_ids_for_usage_account.sql
  koku/subs/trino_sql/azure/subs_summary.sql
Labels: azure-smoke-tests, smokes-required

#5247 [COST-5148] EC2 insert sql - set SavingsPlanCoveredUsage unblended_cost to zero
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute.sql
Labels: aws-smoke-tests, smokes-required

#5253 [COST-5371] Ensure we do not use NULL values when summing
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_gcp.sql
  koku/masu/database/sql/reporting_ocpazure_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpgcp_ocp_infrastructure_back_populate.sql
Labels: smoke-tests, smokes-required

#5256 Remove missed code during the trino upgrade clean up
  koku/masu/api/upgrade_trino/test/test_view.py
  koku/masu/api/upgrade_trino/util/task_handler.py
Labels: ok-to-skip-smokes

#5254 update dependencies
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5260 Unleash rate limiting to cost model updates
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#5210 [COST-4852] Inserting attempts loop to Trino queries
  koku/hcs/test/database/test_report_db_accessor.py
  koku/koku/test_trino_db_utils.py
  koku/koku/trino_database.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5220 [COST-5254] Drop Azure v1 Report fields
  koku/hcs/database/sql/reporting_azure_hcs_daily_summary.sql
  koku/masu/database/trino_sql/azure/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazure_matched_tags.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/processor/_tasks/data_validation.py
  koku/masu/processor/azure/azure_report_parquet_processor.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/masu/test/util/azure/test_common.py
  koku/masu/util/azure/azure_post_processor.py
  koku/masu/util/azure/common.py
  koku/reporting/provider/azure/models.py
  koku/subs/trino_sql/azure/determine_resource_ids_for_usage_account.sql
  koku/subs/trino_sql/azure/subs_row_count.sql
  koku/subs/trino_sql/azure/subs_summary.sql
Labels: full-run-smoke-tests, smokes-required

#5259 switch validation checks to priority queue
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#5251 openapi.json cost-type to cost_type
  docs/specs/openapi.json
Labels: smoke-tests

#5258 [COST-5385] Update Trino and Hive images
  dev/containers/trino/etc/jvm.config
  docker-compose.yml
Labels: ok-to-skip-smokes

#5255 [COST-4904] Update aws resource matching to include csi_volume_handle
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data.yml
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/util/aws/common.py
Labels: aws-smoke-tests, smokes-required

#5262 [COST-4907] Add temp table to track aws disk capacities
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/processor/__init__.py
  koku/reporting/models.py
Labels: aws-smoke-tests, smokes-required

#5266 [COST-5425] Fix regression with false unleash flag
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#5252 [COST-5098] - Fix usage counts and savings plan OCP on AWS
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5261 Include provider in OCP/cloud tag sql params
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcptags_summary.sql
  koku/masu/database/sql/reporting_ocpawstags_summary.sql
  koku/masu/database/sql/reporting_ocpazuretags_summary.sql
  koku/masu/processor/ocp/ocp_cloud_parquet_summary_updater.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: smoke-tests, smokes-required

#5273 [COST-5437] Update alert thresholds on dashboards
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#5270 [COST-5413] - Minor validation bug fixes
  koku/masu/api/update_openshift_on_cloud.py
  koku/masu/processor/_tasks/data_validation.py
  koku/masu/test/processor/test_data_validation.py
Labels: hot-fix-smoke-tests, smokes-required

#5274 Remove deprecated sbom-json-check
  .tekton/koku-pull-request.yaml
  .tekton/koku-push.yaml
Labels: ok-to-skip-smokes

#5275 Ignore `dev/containers` for updates
  renovate.json
Labels: ok-to-skip-smokes

#5263 [COST-5132] OCP AWS Parquet Processing
  koku/api/provider/models.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/processor/__init__.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting/models.py
  koku/reporting/provider/aws/models.py
Labels: hot-fix-smoke-tests, smokes-required
