Repository project-koku/koku, pull requests merged in 2024-03, with the labels that each got.

#4934 [COST-4313] - subscription_name migrations
  koku/reporting/migrations/0318_ocpazurecomputesummaryp_subscription_name_and_more.py
  koku/reporting/provider/azure/openshift/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: hot-fix-smoke-tests, smokes-required

#4930 [COST-4662] Map Azure columns to expected names from TRINO_REQUIRED_COLUMNS
  koku/masu/test/util/azure/test_azure_post_processor.py
  koku/masu/util/azure/azure_post_processor.py
Labels: azure-smoke-tests, smokes-required

#4935 [COST-4313] - Fix azure subscription_name issue
  koku/api/report/azure/openshift/provider_map.py
  koku/api/report/azure/openshift/query_handler.py
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_compute_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_location_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_database_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_network_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_storage_summary_p.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#4949 [COST-4295] AWS Group by ranks only annotate if account in group by
  koku/api/report/queries.py
Labels: aws-smoke-tests, smokes-required

#4954 [COST-4727] Fix tag mapping parent child filters.
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
Labels: smoke-tests, smokes-required

#4951 [COST-4604] - Catch more failures correctly for observability
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/report_downloader.py
  koku/masu/processor/tasks.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#4955 [COST-4728] Log the AWS region
  koku/masu/external/downloader/aws/aws_report_downloader.py
Labels: aws-smoke-tests, smokes-required

#4958 [COST-4713] Azure OpenShift daily trino migration
  scripts/cji_scripts/migrate_trino.py
Labels: hot-fix-smoke-tests, smokes-required

#4944 [COST-4219] Update masu manifest endpoint filters
  koku/masu/api/manifest/test/test_view.py
  koku/masu/api/manifest/views.py
Labels: smoke-tests, smokes-required

#4939 [COST-4686] Handling tag rates in tag mapping.
  koku/api/settings/tags/mapping/serializers.py
  koku/api/settings/tags/mapping/utils.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_utils.py
  koku/api/settings/test/tags/mappings/test_view.py
  koku/koku/cache.py
  koku/koku/test_cache.py
  koku/masu/processor/cost_model_cost_updater.py
Labels: smoke-tests, smokes-required

#4957 [COST-4729] Fix ordering for tag mapping api.
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
  koku/api/settings/utils.py
Labels: smoke-tests, smokes-required

#4950 [COST-4459] Normalize product ids for subs variants
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
  koku/subs/trino_sql/aws/subs_summary.sql
  koku/subs/trino_sql/aws_subs_pre_or_clause.sql
  koku/subs/trino_sql/azure/subs_summary.sql
  koku/subs/trino_sql/azure_subs_pre_or_clause.sql
Labels: azure-smoke-tests, smokes-required

#4948 [COST-4716] Prevent removal of stale tags linked to a mapping.
  koku/masu/database/sql/aws/remove_stale_enabled_tags.sql
  koku/masu/database/sql/azure/remove_stale_enabled_tags.sql
  koku/masu/database/sql/gcp/remove_stale_enabled_tags.sql
  koku/masu/database/sql/oci/remove_stale_enabled_tags.sql
  koku/masu/database/sql/openshift/remove_stale_enabled_tags.sql
  koku/masu/test/api/test_enabled_tags.py
Labels: smoke-tests, smokes-required

#4938 [COST-4390] OCP changing GB to GiB
  koku/api/metrics/constants.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/test/ocp/test_views.py
Labels: ocp-smoke-tests, smokes-required

#4941 [COST-4714] - explicitly check for Tenant existence in KokuTenantSchemaExistsMiddleware
  koku/koku/middleware.py
  koku/koku/test_middleware.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#4961 [COST-4750] OCP Scrub disabled tags in trino.
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/database/trino_sql/test/ocp/mimic_remove_disabled_tags.sql
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: ocp-smoke-tests, smokes-required

#4962 [COST-4537] Update crytography and oci
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4971 [COST-4578] add v3.2.0 operator commit mapping
  koku/masu/util/ocp/common.py
Labels: hot-fix-smoke-tests, smokes-required

#4972 [COST-4121] OpenAPI spec. update: new unit (GiB) used on OCP
  docs/specs/openapi.json
Labels: ocp-smoke-tests, smokes-required

#4904 [COST-4392] Converting gigibyte to gigabyte and fixing units labels
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/util/constants.py
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_gcpcostentrylineitem_daily_summary.sql
Labels: gcp-smoke-tests, smokes-required

#4969 [COST-4643] use cascade_delete to remove expired CostUsageReportManifest
  koku/masu/database/report_manifest_db_accessor.py
Labels: smoke-tests, smokes-required

#4974 [COST-4394] Fixing OCI GB and TB calculations
  koku/masu/database/trino_sql/reporting_ocicostentrylineitem_daily_summary.sql
Labels: smokes-required, oci-smoke-tests

#4970 [COST-4423] - Cluster info include timestamps
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/test/processor/test_tasks.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
  koku/sources/api/view.py
Labels: smoke-tests, smokes-required

#4965 [COST-4730] Fixing pagination to paginate by parent instead of by children
  koku/api/settings/tags/mapping/query_handler.py
  koku/api/settings/tags/mapping/serializers.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
Labels: smoke-tests, smokes-required

#4977 [COST-4750] Fix regression caused by bad cast in trino
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: ocp-smoke-tests, smokes-required

#4973 [COST-4765] Fix org unit join
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#4978 [COST-4423] - Fix OCP-GCP summary timestamp issue
  koku/masu/processor/tasks.py
  koku/masu/util/common.py
Labels: gcp-smoke-tests, smokes-required

#4967 [COST-4752] Azure scrub disabled tags in trino.
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_azurecostentrylineitem_daily_summary.sql
  koku/masu/processor/azure/azure_report_parquet_summary_updater.py
  koku/masu/test/database/test_azure_report_db_accessor.py
Labels: azure-smoke-tests, smokes-required

#4988 Increase gunicorn workers for sources client
  deploy/clowdapp.yaml
  deploy/kustomize/patches/sources-client.yaml
  koku/gunicorn_conf.py
Labels: smoke-tests, smokes-required

#4986 Revert "[COST-4392] Converting gibibyte to gigabyte and fixing units labels"
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/test/gcp/openshift/test_ocp_gcp_query_handler.py
  koku/api/report/test/gcp/test_gcp_query_handler.py
  koku/api/report/test/util/constants.py
  koku/masu/database/sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_gcpcostentrylineitem_daily_summary.sql
Labels: gcp-smoke-tests, smokes-required

#4976 [COST-4772] Tag mapping multiple filter functionality
  koku/api/settings/tags/mapping/utils.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
Labels: smoke-tests, smokes-required

#4990 Add populate exchange rates make command
  Makefile
Labels: ok-to-skip-smokes

#4993 catch non-existent manifest for ocp-on-cloud infra provider
  koku/api/provider/provider_manager.py
Labels: smoke-tests, smokes-required

#4994 add release note section to PR template
  .github/pull_request_template.md
Labels: ok-to-skip-smokes

#4991 [COST-4794] Deduplicate parent keys for tag mapping.
  koku/api/settings/tags/mapping/serializers.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
Labels: smoke-tests, smokes-required

#4966 [COST-4751] GCP Scrub disabled tags in trino.
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/sql/reporting_gcpcostentryline_item_daily_summary_update_enabled_tags.sql
  koku/masu/database/trino_sql/reporting_gcpcostentrylineitem_daily_summary.sql
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/gcp/test_gcp_report_parquet_summary_updater.py
Labels: gcp-smoke-tests, smokes-required

#4995 [COST-4802] Add conversion field to subs kafka message
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
Labels: azure-smoke-tests, smokes-required

#4997 Revert "[COST-4794] Deduplicate parent keys for tag mapping."
  koku/api/settings/tags/mapping/serializers.py
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
Labels: smoke-tests, smokes-required

#5000 [COST-4423] - fix manifest updates for cluster info
  koku/masu/processor/tasks.py
  koku/masu/test/util/test_common.py
  koku/masu/util/common.py
Labels: smoke-tests, smokes-required

#4989 [COST-3607, COST-4627] model for key metrics
  Makefile
  koku/key_metrics/__init__.py
  koku/key_metrics/apps.py
  koku/key_metrics/migrations/0001_initial.py
  koku/key_metrics/migrations/__init__.py
  koku/key_metrics/models.py
  koku/koku/settings.py
Labels: hot-fix-smoke-tests, smokes-required

#5004 [COST-4814] Tag mapping inconsistent ordering.
  koku/api/settings/tags/mapping/query_handler.py
Labels: smoke-tests, smokes-required

#4998 [COST-4801] Add a tracing id to the delayed summary tasks.
  koku/api/settings/tags/mapping/view.py
  koku/reporting_common/models.py
  koku/reporting_common/test_reporting_common.py
Labels: smoke-tests, smokes-required

#5003 [COST-4807] fix CWE-547 false positive
  koku/providers/provider_errors.py
  koku/sources/sources_error_message.py
  koku/sources/test/test_sources_error_message.py
Labels: azure-smoke-tests, smokes-required

#4906 Add make target to run local snyk scan
  Makefile
  dev/scripts/snyk-scan.py
Labels: ok-to-skip-smokes
