Repository project-koku/koku, pull requests merged in 2024-09, with the labels that each got.

#5278 Validation checks - dont cross month boundary
  koku/masu/processor/_tasks/data_validation.py
Labels: smoke-tests, smokes-required

#5285 [COST-5364] Update Renovate config
  renovate.json
Labels: ok-to-skip-smokes

#5292 [COST-4876] Deploy with ubi9-minimal
  .github/workflows/check-image.yml
  Dockerfile
  ci/functions.sh
Labels: hot-fix-smoke-tests, smokes-required

#5295 [COST-5132] Fix duplication in managed ocp on aws flow
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
Labels: aws-smoke-tests, smokes-required

#5293 [COST-5204] Fix duplicate metrics
  koku/gunicorn_conf.py
  koku/koku/metrics.py
  koku/masu/prometheus_stats.py
Labels: hot-fix-smoke-tests, smokes-required

#5298 [COST-5132] update Managed OCP on AWS tag matching
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
Labels: hot-fix-smoke-tests, smokes-required

#5299 drop bad invoice months from ingress flow
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
Labels: gcp-smoke-tests, smokes-required

#5287 [COST-5133 + COST-5134] - Add support for OCP/(GCP/Azure) trino updates
  koku/api/provider/models.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_gcp_openshift_daily.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting/models.py
  koku/reporting/provider/azure/models.py
  koku/reporting/provider/gcp/models.py
Labels: hot-fix-smoke-tests, smokes-required

#5290 [COST-5480] Add verification SQL to check parquet to managed conversion
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/verify/managed_ocp_on_cloud_tables.sql
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5297 Update renovate config again
  renovate.json
Labels: ok-to-skip-smokes

#5304 [COST-5513] Specify registry when pushing metrics
  koku/koku/metrics.py
Labels: hot-fix-smoke-tests, smokes-required

#5300 [COST-5443] Creating a common filter for filtering by resource_id and instance_name.
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/serializers.py
  koku/api/report/test/aws/test_views.py
Labels: aws-smoke-tests, smokes-required

#5303 [COST-5400] - use amortized cost for ocp on all endpoints
  koku/api/report/all/openshift/provider_map.py
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_aws.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_aws.sql
Labels: hot-fix-smoke-tests, smokes-required

#5305 [COST-5133] - Clean up some unused columns
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/processor/azure/azure_report_parquet_processor.py
  koku/masu/util/azure/azure_post_processor.py
  koku/masu/util/azure/common.py
  koku/reporting/provider/azure/models.py
Labels: smoke-tests, smokes-required

#5302 [COST-4520] Use multi-arch images built by Konflux for dev
  docker-compose.yml
Labels: ok-to-skip-smokes

#5307 [COST-5433] Fixing null values for account_alias and instance_name
  koku/api/report/aws/provider_map.py
Labels: aws-smoke-tests, smokes-required

#5310 [cost-4945] Fix lowercase instance_name on EC2 report
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute.sql
Labels: aws-smoke-tests, smokes-required

#5301 [COST-5133] Switch to contains logic for Azure & GCP managed
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_gcp_openshift_daily.sql
Labels: hot-fix-smoke-tests, smokes-required

#5314 [COST-5452] Deduplicate AWS EC2 tags on UI
  koku/api/report/aws/query_handler.py
Labels: aws-smoke-tests, smokes-required

#5317 [COST-5449] - Create new partitioned EC2 table
  koku/reporting/migrations/0325_awscostentrylineitemsummarybyec2computep.py
  koku/reporting/provider/aws/models.py
Labels: smoke-tests, smokes-required

#5318 [COST-5449] - Switch code to point at new EC2 table
  koku/api/report/aws/provider_map.py
  koku/api/report/test/util/baker_recipes.py
  koku/api/resource_types/aws_ec2_compute_instances/view.py
  koku/api/resource_types/aws_ec2_compute_os/view.py
  koku/masu/database/__init__.py
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute_p.sql
  koku/masu/test/database/test_aws_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5321 [COST-5449] - Delete old EC2 table/model
  koku/reporting/migrations/0326_delete_awscostentrylineitemsummarybyec2compute.py
  koku/reporting/provider/aws/models.py
Labels: smoke-tests, smokes-required

#5322 [COST-5545] Ignore RIFee rows for HCS daily summary SQL
  koku/hcs/database/sql/reporting_aws_hcs_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#5267 [COST-4910] Add unattributed storage for AWS
  Pipfile.lock
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#5286 [COST-5510] Use Konflux images for integration tests
  .tekton/koku-pull-request.yaml
  .tekton/koku-push.yaml
  Jenkinsfile
  ci/functions.sh
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: smoke-tests, smokes-required

#5325 [COST-5502] Update image used by smoke test
  smoke_test.sh
Labels: ok-to-skip-smokes

#5328 Remove obsolete version element from compose file
  docker-compose.yml
Labels: hot-fix-smoke-tests, ok-to-skip-smokes

#5324 [COST-5427] - cost model updates by date via unleash check
  koku/masu/processor/__init__.py
  koku/masu/processor/cost_model_cost_updater.py
Labels: smoke-tests, smokes-required

#5316 Silence a noisy alert
  koku/masu/processor/_tasks/data_validation.py
  koku/masu/test/processor/test_data_validation.py
Labels: hot-fix-smoke-tests, smokes-required

#5329 tweak prometheus dashboard
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
Labels: hot-fix-smoke-tests, smokes-required

#5327 [COST-5434] Remove extraneous error message
  koku/masu/database/report_db_accessor_base.py
Labels: hot-fix-smoke-tests, smokes-required

#5330 [COST-5555] Improve logging in data validation
  koku/masu/processor/_tasks/data_validation.py
Labels: hot-fix-smoke-tests, smokes-required
