Repository project-koku/koku, pull requests merged in 2024-11, with the labels that each got.

#5356 [COST-4176, COST-5651] add Indian Rupee and Brazilian Real currencies
  koku/api/currency/currencies.py
  koku/api/migrations/0065_alter_exchangerates_currency_type.py
Labels: smoke-tests, smokes-required

#5358 switch to --deploy flag
  .github/workflows/ci.yml
  tox.ini
Labels: ok-to-skip-smokes

#5357 [COST-5565] Fix managed tables strpos
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_gcp_openshift_daily.sql
Labels: smoke-tests, smokes-required

#5354 [COST-5650] Support cross account RBAC access
  koku/api/provider/provider_builder.py
  koku/api/provider/serializers.py
  koku/koku/middleware.py
  koku/koku/test_middleware.py
Labels: hot-fix-smoke-tests, smokes-required

#5359 CI: Add new required task
  .tekton/koku-pull-request.yaml
  .tekton/koku-push.yaml
Labels: ok-to-skip-smokes

#5361 [COST-4176, COST-5651] currency: fix capitalization
  koku/api/currency/currencies.py
Labels: smoke-tests, smokes-required

#5362 [COST-5652] - Performance improvmeent for OCP label deletes
  koku/masu/database/sql/reporting_ocpstoragevolumelabel_summary.sql
  koku/masu/database/sql/reporting_ocpusagepodlabel_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5363 Remove unused celery task
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: smokes-required, ok-to-skip-smokes

#5364 format json files with pre-commit hook
  .pre-commit-config.yaml
  docs/specs/openapi.json
  koku/masu/openapi.json
  koku/masu/test/data/ocp/payload2/manifest.json
  koku/masu/test/external/downloader/azure/fixtures/manifest.json
  koku/sources/openapi.json
  renovate.json
Labels: hot-fix-smoke-tests, smokes-required

#5353 [COST-20] Openshift virt
  dev/scripts/nise_ymls/ocp/ocp_on_premise.yml
  docs/specs/openapi.json
  koku/api/common/pagination.py
  koku/api/common/test_pagination.py
  koku/api/query_params.py
  koku/api/report/aws/view.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/ocp/serializers.py
  koku/api/report/ocp/view.py
  koku/api/report/queries.py
  koku/api/report/test/util/constants.py
  koku/api/report/view.py
  koku/api/resource_types/openshift_virtual_machines/__init__.py
  koku/api/resource_types/openshift_virtual_machines/view.py
  koku/api/resource_types/test/openshift_virtual_machines/__init__.py
  koku/api/resource_types/test/openshift_virtual_machines/test_views.py
  koku/api/tags/test/ocp/test_ocp_tag_query_handler.py
  koku/api/urls.py
  koku/api/views.py
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/processor/__init__.py
  koku/reporting/migrations/0327_ocpvirtualmachinesummaryp.py
  koku/reporting/provider/ocp/models.py
Labels: ocp-smoke-tests, smokes-required

#5360 Add licenses file to container image
  .dockerignore
  Dockerfile
Labels: hot-fix-smoke-tests, smokes-required

#5367 Prevent Renovate bot from opening PRs outside the schedule
  renovate.json
Labels: ok-to-skip-smokes

#5368 COST-20: Adjust OpenShift virt provider map for memory & storage
  koku/api/report/ocp/provider_map.py
Labels: ocp-smoke-tests, smokes-required

#5375 [COST-5657] add logging for debugging subs query
  koku/subs/subs_data_extractor.py
Labels: smoke-tests, smokes-required

#5369 OCP VM Order by vm_name
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/serializers.py
Labels: ocp-smoke-tests, smokes-required

#5378 [COST-5681] - add operator v3.3.1 versions
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#5373 update dependencies
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5380 Change Ibutsu job_name and set build_url for jenkins pr-checks
  Jenkinsfile
Labels: ok-to-skip-smokes

#5377 Fix ocp vm csv export formatting
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: ocp-smoke-tests, smokes-required

#5381 [COST-5657] subs: use subquery in Trino to join from Postgres
  koku/subs/subs_data_extractor.py
  koku/subs/trino_sql/aws/determine_ids_for_provider.sql
  koku/subs/trino_sql/aws/determine_resource_ids_for_usage_account.sql
  koku/subs/trino_sql/azure/determine_ids_for_provider.sql
  koku/subs/trino_sql/azure/determine_resource_ids_for_usage_account.sql
Labels: smoke-tests, smokes-required

#5343 [COST-5558] Fixing EC2 report to get the proper latest values
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute_p.sql
Labels: hot-fix-smoke-tests, smokes-required

#5386 Skip Jenkins tests and run tests in Konflux if label is set on PR
  ci/functions.sh
Labels: ok-to-skip-smokes

#5385 Adjust vm latests values to be second to last day
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
Labels: smoke-tests, smokes-required

#5387 [COST-5280] Run tests with defined resource requirements
  Jenkinsfile
  smoke_test.sh
Labels: hot-fix-smoke-tests

#5391 [COST-5637] Fix provider map infra calcuations for virtualization
  koku/api/report/ocp/provider_map.py
Labels: hot-fix-smoke-tests, smokes-required

#5392 [COST-5635] Remove bad distinct on from virt sql
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
Labels: hot-fix-smoke-tests, smokes-required

#5388 [COST-5637] Change tag exclusions to an or operation for openshift-virt
  dev/scripts/nise_ymls/ocp/ocp_on_premise.yml
  koku/api/report/queries.py
  koku/api/report/test/test_queries.py
  koku/api/report/view.py
Labels: hot-fix-smoke-tests, smokes-required

#5393 [COST-5728] switch OCP on AWS endpoints to use amortized costs
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_daily_summary_aws.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_aws.sql
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
Labels: smoke-tests, smokes-required

#5397 [COST-5732] add delta description api sepc
  docs/specs/openapi.json
Labels: hot-fix-smoke-tests, smokes-required

#5395 [COST-5711] Provide endpoint of all regions for integrations team
  koku/api/resource_types/aws_regions/view.py
  koku/api/resource_types/test/test_views.py
  koku/api/urls.py
  koku/api/views.py
Labels: hot-fix-smoke-tests, smokes-required

#5277 [COST-5135] Update Masu endpoint to handle new ocp on cloud flow
  koku/masu/api/process_openshift_on_cloud.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_process_openshift_on_cloud.py
Labels: hot-fix-smoke-tests, smokes-required

#5399 Revert "[COST-5711] Provide endpoint of all regions for integrations team"
  koku/api/resource_types/aws_regions/view.py
  koku/api/resource_types/test/test_views.py
  koku/api/urls.py
  koku/api/views.py
Labels: hot-fix-smoke-tests, smokes-required

#5400 [COST-5711] - Add new middleware access check
  koku/koku/middleware.py
Labels: hot-fix-smoke-tests, smokes-required

#5398 [COST-5738] Exclude usage rows from virtualization table
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
Labels: smoke-tests, smokes-required

#5405 Prevent unnecessary unleash checks for group by override
  koku/api/report/all/openshift/serializers.py
  koku/api/report/aws/openshift/serializers.py
  koku/api/report/aws/serializers.py
  koku/api/report/serializers.py
  koku/masu/processor/__init__.py
Labels: smoke-tests, smokes-required

#5351 Replace version-two with resource-group flag
  dev/scripts/load_test_customer_data.sh
Labels: ok-to-skip-smokes

#5407 [RHCLOUD-36497] - switch error messages from sources to integrations
  koku/api/provider/serializers.py
Labels: hot-fix-smoke-tests, smokes-required

#5404 Remove unleash flag to disable checking ingress columns
  koku/masu/processor/__init__.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
Labels: hot-fix-smoke-tests, smokes-required
