Repository project-koku/koku, pull requests merged in 2024-04, with the labels that each got.

#5008 [COST-4828] Handle 0 in divisor for cost distribution SQL
  koku/masu/database/sql/openshift/cost_model/distribute_platform_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_worker_cost.sql
Labels: ocp-smoke-tests, smokes-required

#5010 [COST-4715] sentry -> glitchtip cleanup p1
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/koku/sentry.py
Labels: hot-fix-smoke-tests, smokes-required

#5011 [COST-4715] sentry -> glitchtip cleanup p1
  deploy/clowdapp.yaml
  deploy/kustomize/patches/koku.yaml
Labels: hot-fix-smoke-tests, smokes-required

#5009 [COST-4704] Update django to 4.2.11 to address CVE-2024-27351
  Pipfile.lock
Labels: smoke-tests, smokes-required

#4964 [COST-4372] OCP: Fix capacity instance count
  koku/api/report/ocp/capacity/cluster_capacity.py
  koku/api/report/ocp/capacity/node_capacity.py
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/test_dataclasses.py
Labels: smoke-tests, smokes-required

#5014 [COST-4835] validate tag uuids
  koku/api/settings/tags/mapping/view.py
  koku/api/settings/test/tags/mappings/test_view.py
Labels: smoke-tests, smokes-required

#4982 [COST-4775] add v3.2.1 commit shas
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#5023 [COST-4874] address shellcheck warnings
  build_deploy.sh
  dev/scripts/genssc
Labels: ok-to-skip-smokes

#5024 Upgrade Codecov action
  .github/workflows/ci.yml
Labels: ok-to-skip-smokes

#5007 [COST-4807] Remove remove-stale from enabled tags masu endpoint options
  koku/masu/api/enabled_tags.py
  koku/masu/database/sql/aws/remove_stale_enabled_tags.sql
  koku/masu/database/sql/azure/remove_stale_enabled_tags.sql
  koku/masu/database/sql/gcp/remove_stale_enabled_tags.sql
  koku/masu/database/sql/oci/remove_stale_enabled_tags.sql
  koku/masu/database/sql/openshift/remove_stale_enabled_tags.sql
Labels: smoke-tests, smokes-required

#5012 [COST-4715] sentry -> glitchtip cleanup p2
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  koku/koku/sentry.py
Labels: smoke-tests, smokes-required

#5020 COST-4764 Set lower level rbac roles when only top level are set for OpenShift cluster/node/project
  koku/koku/rbac.py
  koku/koku/test_rbac.py
Labels: smoke-tests, smokes-required

#5021 [COST-4757] - Remove custom Unleash strategies
  .unleash/flags.json
  koku/koku/feature_flags.py
  scripts/cji_scripts/lite/unleash.py
Labels: hot-fix-smoke-tests, smokes-required

#5026 [COST-4822] Remove OCPAWS Special Cluster tag matching
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#4999 [COST-4785] Fix bug with worker unallocated
  koku/masu/database/sql/openshift/cost_model/distribute_platform_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_worker_cost.sql
Labels: ocp-smoke-tests, smokes-required

#4968 [COST-3761] Add models for OCP node networking costs
  koku/reporting/migrations/0319_node_network_costs.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, django migration, smokes-required

#5019 [COST-4877] Report correct PostgreSQL version
  koku/masu/api/db_performance/db_performance.py
  koku/masu/api/db_performance/dbp_views.py
  koku/masu/test/api/test_db_performance.py
Labels: smoke-tests, smokes-required

#4984 add provider-billing-source to sources masu endpoint
  koku/masu/api/sources/serializers.py
Labels: hot-fix-smoke-tests, smokes-required

#5025 rename variables for "COPY_PASTE_ERROR"
  koku/api/query_params.py
Labels: smoke-tests, smokes-required

#5028 [COST-4895] create tmp dir for build-deploy
  build_deploy.sh
Labels: ok-to-skip-smokes

#5029 [COST-4736] - Fix local strategies
  .unleash/flags.json
Labels: ok-to-skip-smokes

#5030 rename presto -> trino in app-interface
  Jenkinsfile
  dev/config.yaml.github-example
  smoke_test.sh
Labels: ok-to-skip-smokes

#5036 add smoke_test shell script back
  smoke_test.sh
Labels: ok-to-skip-smokes

#5037 Mark smoke_test.sh as an executable file
  smoke_test.sh
Labels: ok-to-skip-smokes

#5038 rename components to trino in smoke_test.sh
  smoke_test.sh
Labels: ok-to-skip-smokes

#5032 [COST-4372] Use Max for volume capacity count
  koku/api/report/ocp/capacity/cluster_capacity.py
  koku/api/report/ocp/provider_map.py
Labels: smoke-tests, smokes-required

#5027 Update delayed resummary logic for ocp on cloud.
  koku/api/settings/tags/mapping/utils.py
  koku/api/settings/test/tags/mappings/test_utils.py
Labels: smoke-tests, smokes-required

#5039 [COST-4626] strip `acct` from schema in parquet converter
  koku/masu/api/upgrade_trino/util/verify_parquet_files.py
Labels: hot-fix-smoke-tests, smokes-required

#5040 [COST-4626] bump parquet converter version
  koku/masu/api/upgrade_trino/util/constants.py
Labels: hot-fix-smoke-tests, smokes-required

#5035 update dependencies
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5041 Add dev doc about worker unallocated distribution
  docs/distributing_cost.md
Labels: ok-to-skip-smokes

#5022 [COST-4807] mount aws credentials as volume
  .env.example
  README.md
  ci/functions.sh
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  dev/credentials/.gitignore
  dev/credentials/aws.example
  dev/credentials/gcp.example
  dev/credentials/oci.example
  dev/credentials/oci_key_file.pem.example
  docker-compose.yml
  smoke_test.sh
Labels: aws-smoke-tests, smokes-required

#5047 update sqlparse and gunicorn
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5049 [COST-4947] Remove account and region from ProviderInfrastructureMap filter
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
Labels: smoke-tests, smokes-required

#5048 [COST-4871] mount OCI credentials as volume
  .env.example
  Makefile
  ci/functions.sh
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/koku/settings.py
  smoke_test.sh
Labels: smokes-required, oci-smoke-tests

#5050 [COST-4871] add oci env variables to subs workers
  deploy/clowdapp.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
Labels: smokes-required, oci-smoke-tests

#5053 [COST-4947] Remove references to region and account in ProviderInfrastructureMap
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/api/sources/serializers.py
  koku/masu/api/sources/test/test_serializers.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/aws/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/azure/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/database/trino_sql/gcp/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
  koku/masu/test/processor/ocp/test_ocp_cloud_parquet_report_summary_updater.py
Labels: smoke-tests, smokes-required

#5031 [COST-861] Tokenizing error - skip bad rows when reading csv
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/data/ocp/tokenizing-error.csv
  koku/masu/test/data/ocp/valid-csv.csv
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#4717 update trino and hive images for local dev
  dev/containers/trino/etc/catalog/hive.properties
  dev/containers/trino/etc/catalog/postgres.properties
  dev/containers/trino/etc/config.properties
  dev/containers/trino/etc/hadoop-config/core-site.xml
  dev/containers/trino/etc/jvm.config
  dev/containers/trino/etc/log.properties
  docker-compose.arm.yml
  docker-compose.yml
Labels: ok-to-skip-smokes

#5061 [COST-4974] Trino Migration to Drop Azure Line Items
  scripts/cji_scripts/migrate_trino.py
Labels: smoke-tests, smokes-required

#5060 [COST-4973] - Fix mid month finalization
  koku/masu/external/downloader/aws/aws_report_downloader.py
Labels: smoke-tests, smokes-required

#5063 Update view.py
  koku/sources/api/view.py
Labels: hot-fix-smoke-tests, smokes-required

#5062 [COST-4967] Update Azure Openshift Correlation to be contains.
  dev/scripts/nise_ymls/ocp_on_azure/azure_static_data.yml
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5044 [COST-4844] Add group by storageclass to OCP volume endpoint.
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: smoke-tests, smokes-required

#5070 [COST-4975] - Fix OCP infra state lookup
  koku/api/provider/provider_manager.py
Labels: smoke-tests, smokes-required

#5001 [COST-4759] Add all_labels to back populate for ocp on cloud.
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpazure_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpgcp_ocp_infrastructure_back_populate.sql
Labels: smoke-tests, smokes-required

#4979 [COST-4762] Update HCS AWS Estimate pricing
  koku/hcs/database/sql/reporting_aws_hcs_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5045 Use multi-arch container images for development
  Makefile
  docker-compose.arm.yml
  docker-compose.yml
Labels: ok-to-skip-smokes

#5073 [COST-4914] Update classification to include unattributed
  koku/api/report/queries.py
Labels: smoke-tests, smokes-required

#5075 prevent running migration CI check if removal label is present
  .github/workflows/ci.yml
Labels: ok-to-skip-smokes, skip-migration-check

#5076 [COST-4947] Remove account and region fields from ProviderInfrastructureMap
  koku/api/provider/models.py
Labels: smoke-tests, smokes-required, skip-migration-check

#5077 [COST-4947] Migration to remove account and region from ProviderInfrastructureMap
  koku/api/migrations/0063_remove_infra_map_account_region.py
Labels: hot-fix-smoke-tests, smokes-required
