Repository project-koku/koku, pull requests merged in 2024-06, with the labels that each got.

#5120 [COST-5051] Prevent TABLE_NOT_FOUND error when looking up PVCs
  docker-compose.yml
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5144 [COST-5035] - Fix OCP on GCP tag matching sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
Labels: gcp-smoke-tests, smokes-required

#5121 [COST-4946] Update EC2 compute summary table
  koku/masu/database/__init__.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute.sql
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/processor/aws/test_aws_report_parquet_summary_updater.py
Labels: smoke-tests, smokes-required

#5151 attempt to bump sources client resources for eph
  deploy/clowdapp.yaml
  deploy/kustomize/patches/sources-client.yaml
Labels: hot-fix-smoke-tests, smokes-required

#5145 [COST-5094] Default to distributing unattributed networking/storage costs
  koku/cost_models/migrations/0007_net_stor_distribute_default.py
Labels: smoke-tests, django migration, smokes-required

#5150 Run cost model update in ocp on cloud summary flow
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: ocp-smoke-tests, smokes-required

#5149 Override start date for cost model updates
  koku/api/test_utils.py
  koku/api/utils.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#5146 [COST-5095] Default to distributing networking and storage unattributed if no cost model is present
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/processor/tasks.py
Labels: ocp-smoke-tests, smokes-required

#5157 minor GCP cost model fix
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#5158 Use newer API version for Azure Cost Management client
  koku/koku/settings.py
  koku/providers/azure/client.py
Labels: azure-smoke-tests, smokes-required

#5160 Pause use of csi_volume_handle in SQL.
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5137 [COST-5072] Check schema exists prior to querying it during HCS processing
  koku/hcs/daily_report.py
  koku/hcs/test/test_daily_report.py
Labels: smoke-tests, ok-to-skip-smokes

#5152 [COST-5097] Format OCP data transfer fields like other usage fileds
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/view/test_ocp_network_view.py
Labels: ocp-smoke-tests, smokes-required

#5154 Remove suffix from masu trino endpoint
  koku/masu/api/trino.py
Labels: smoke-tests, smokes-required

#5138 catch None object
  koku/masu/api/sources/test/test_views.py
  koku/masu/api/sources/views.py
Labels: hot-fix-smoke-tests, smokes-required

#5136 [COST-4966] - Removing unleash logic for savings plan cost
  .unleash/flags.json
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
  koku/masu/processor/__init__.py
  koku/masu/test/database/test_aws_report_db_accessor.py
Labels: aws-smoke-tests, smokes-required

#5167 masu - Account for intermediate `None` values when getting cost model
  koku/masu/api/sources/test/test_views.py
  koku/masu/api/sources/views.py
Labels: hot-fix-smoke-tests, smokes-required

#5168 Update disable_source to work for tasks already in the download queue.
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#5166 [COST-5141] Add command to remove expired hive partitions
  koku/masu/management/commands/migrate_trino_tables.py
Labels: hot-fix-smoke-tests, smokes-required

#5165 Update GitHub actions
  .github/workflows/check-image.yml
  .github/workflows/ci.yml
  .github/workflows/pre-release.yaml
Labels: ok-to-skip-smokes

#5170 [COST-5141] Add group by to the outer query
  koku/masu/management/commands/migrate_trino_tables.py
Labels: hot-fix-smoke-tests, smokes-required

#5173 [COST-5141] Fix management command to use continue instead of return.
  koku/masu/management/commands/migrate_trino_tables.py
Labels: hot-fix-smoke-tests, smokes-required

#5162 [COST-5128] Process new subs tag to identify non-converted instances
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
  koku/subs/trino_sql/aws/determine_resource_ids_for_usage_account.sql
  koku/subs/trino_sql/aws/subs_summary.sql
  koku/subs/trino_sql/azure/subs_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5130 [COST-4745] Add `data_transfer_direction` to GCP network costs to Trino tables
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
Labels: gcp-smoke-tests

#5129 [COST-4741] Add `data_transfer_direction` for AWS network costs to Trino tables
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests

#5178 Improve our logging readability
  koku/api/common/__init__.py
Labels: hot-fix-smoke-tests, smokes-required

#5179 add prometheus metrics for new queues
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
  koku/common/queues.py
  koku/masu/prometheus_stats.py
Labels: hot-fix-smoke-tests, smokes-required

#5143 [COST-4916] add v3.3.0 operator commits
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#5163 [COST-5124] Improve Trino migration management command
  koku/masu/management/commands/migrate_trino_tables.py
Labels: hot-fix-smoke-tests, smokes-required

#5184 Filter accounts by matching criteria during subs processing
  koku/subs/trino_sql/aws/determine_ids_for_provider.sql
  koku/subs/trino_sql/azure/determine_ids_for_provider.sql
Labels: smoke-tests, smokes-required

#5185 Update tasks.py
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#5183 clean up grafana dashboard
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#5186 Skip tag SQL if key is present in cache but value is None
  koku/koku/cache.py
  koku/koku/test_cache.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5187 [COST-5196] - Send OCP tasks to correct queues
  koku/masu/processor/tasks.py
Labels: smoke-tests, smokes-required

#5182 [COST-5176] correctly pass context dictionary within log_json function call
  koku/hcs/daily_report.py
  koku/hcs/test/test_daily_report.py
Labels: hot-fix-smoke-tests, smokes-required

#5180 [COST-5178] - batch delete S3 files
  koku/masu/celery/tasks.py
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/test/celery/test_tasks.py
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#5189 Add flower as a dev dependency
  Pipfile
  Pipfile.lock
  docs/devtools.md
Labels: hot-fix-smoke-tests, smokes-required

#5174 [COST-4844] Serializer update for ordering by storageclass
  koku/api/report/ocp/serializers.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
Labels: azure-smoke-tests, smokes-required

#5193 Switch to using podman in build_deploy
  build_deploy.sh
Labels: ok-to-skip-smokes

#5181 skip polling providers still processing
  .env.example
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-penalty.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-penalty.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-penalty.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-penalty.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary-penalty.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/koku/settings.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#5195 [COST-5214] Move TARGETARCH declaration to the top of the Dockerfile
  Dockerfile
  Jenkinsfile
Labels: hot-fix-smoke-tests, smokes-required

#5194 [COST-5213] - fix S3 prepare
  koku/masu/database/report_manifest_db_accessor.py
  koku/masu/external/downloader/aws/aws_report_downloader.py
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/test/database/test_report_manifest_db_accessor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
  koku/masu/util/aws/common.py
  koku/reporting_common/migrations/0042_alter_costusagereportmanifest_s3_parquet_cleared.py
  koku/reporting_common/models.py
Labels: smoke-tests, smokes-required
