Repository project-koku/koku, pull requests merged in 2024-05, with the labels that each got.

#5078 [COST-4967] Undo partial matching on node for ocp on azure
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure, azure-smoke-tests, smokes-required

#5071 [COST-4936] Add memory and operating system columns to aws trino table
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
  koku/masu/test/util/aws/test_aws_post_processor.py
  koku/masu/util/aws/aws_post_processor.py
  koku/masu/util/aws/common.py
  koku/reporting/provider/aws/models.py
  scripts/cji_scripts/migrate_trino.py
Labels: aws-smoke-tests, trino migration, smokes-required

#4963 [COST-5007] move trino migration to a masu management command
  Pipfile
  Pipfile.lock
  koku/masu/management/commands/migrate_trino_tables.py
  scripts/README
  scripts/__init__.py
  scripts/cji_scripts/__init__.py
  scripts/cji_scripts/adjust_ocp_ui_numerics.py
  scripts/cji_scripts/check_for_migration_app_name.py
  scripts/cji_scripts/copy_ocp_aws_azure_data.py
  scripts/cji_scripts/copy_static_perspective_data.py
  scripts/cji_scripts/lite/__init__.py
  scripts/cji_scripts/lite/config.py
  scripts/cji_scripts/lite/env.py
  scripts/cji_scripts/lite/unleash.py
  scripts/cji_scripts/migrate_trino.py
  scripts/cji_scripts/mp_truncate_lineitem_tables.py
  scripts/cji_scripts/truncate_ocp_on_awsazure_base.py
  scripts/cji_scripts/truncate_old_tables.py
  scripts/job_script.sh
Labels: smoke-tests, smokes-required

#5052 [COST-1665, COST-4866] support new storage report columns
  koku/masu/test/util/ocp/test_common.py
  koku/masu/test/util/ocp/test_ocp_post_processor.py
  koku/masu/util/ocp/common.py
  koku/masu/util/ocp/ocp_post_processor.py
Labels: smoke-tests, smokes-required

#5082 add inital backstage integration
  docs/index.md
  koku/mkdocs.yml
Labels: ok-to-skip-smokes

#5083 fix mkdocs.yml file location
  mkdocs.yml
Labels: ok-to-skip-smokes

#5084 [COST-5012] add cost models to internal sources endpoint
  koku/masu/api/sources/serializers.py
  koku/masu/api/sources/views.py
Labels: smoke-tests, smokes-required

#5080 [COST-3617] - Fix GCP end of month crossover summary
  koku/api/utils.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_gcpcostentrylineitem_daily_summary.sql
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/external/downloader/gcp_local/gcp_local_report_downloader.py
  koku/masu/processor/parquet/parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5094 [COST-5007] add trino host/port to mgmt cji
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: smoke-tests, smokes-required

#5086 [COST-4740] Migrations for OCP Cloud table network columns
  koku/reporting/migrations/0320_ocpcloud_projsumm_network_fields.py
Labels: smoke-tests, django migration, smokes-required, skip-migration-check

#5087 [COST-4740] Model updates for OCP on Cloud project daily summary tables
  koku/reporting/provider/aws/openshift/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/reporting/provider/gcp/openshift/models.py
Labels: smoke-tests, smokes-required

#5093 add start/end date to "checking infra" logs
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
Labels: smoke-tests, smokes-required

#5081 [COST-4930] Migration for AWSCostEntryLineItemSummaryByEC2Compute model
  koku/reporting/migrations/0321_awscostentrylineitemsummarybyec2compute.py
Labels: django migration, hot-fix-smoke-tests, smokes-required, skip-migration-check

#5069 [COST-4930] Add AWS EC2 Compute summary table
  koku/reporting/provider/aws/models.py
Labels: smoke-tests, smokes-required

#5085 [COST-3761] Generate example API data for several days
  koku/api/report/ocp/network/__init__.py
  koku/api/report/ocp/network/example.py
  koku/api/report/ocp/view.py
  koku/api/report/test/ocp/view/test_ocp_network_view.py
Labels: smoke-tests, smokes-required

#5095 [COST-5011] Update correlation to include OS disks.
  dev/scripts/nise_ymls/ocp_on_azure/azure_static_data.yml
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5099 [COST-5028] guard against report_status not existing
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/processor/report_processor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5100 [COST-5024] GCP Return credits field as json in bigquery.
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
Labels: gcp-smoke-tests, smokes-required

#5102 [COST-4913] Add ability to distribute unattributed storage cost.
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_unattributed_storage_cost.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5105 [COST-5030] - use stricter tag matching strategies
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#5106 [COST-5011] Limit OS disk correlation to pod data source rows
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5108 [COST-5029] - Override start date for OCP infra mapping
  koku/masu/processor/ocp/ocp_report_parquet_summary_updater.py
Labels: ocp-smoke-tests, smokes-required

#5103 [COST-5024] Avoid custom JSON parsing for GCP credits field
  koku/masu/test/util/gcp/test_gcp_post_processor.py
  koku/masu/util/gcp/gcp_post_processor.py
Labels: gcp-smoke-tests, smokes-required

#5090 [COST-5015] Azure disk capacity table migration
  koku/reporting_common/migrations/0041_diskcapacity.py
Labels: django migration, hot-fix-smoke-tests, smokes-required, skip-migration-check

#5089 [COST-5015] Retrieve azure disk capacities
  koku/masu/api/update_rates.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/celery/tasks.py
  koku/masu/test/celery/test_tasks.py
  koku/reporting_common/models.py
Labels: hot-fix-smoke-tests, smokes-required

#5112 move gcp local create_daily_archives return outside for loop
  koku/masu/external/downloader/gcp_local/gcp_local_report_downloader.py
Labels: hot-fix-smoke-tests, smokes-required

#5110 [COST-5034] - Use json_query for OCP on Azure sql tag matching
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5115 [COST-5020] Use org_id for kafka message key in subs processing
  koku/subs/subs_data_messenger.py
Labels: smoke-tests, smokes-required

#5122 [COST-4930] Migration to alter max_length for instance_name field
  koku/reporting/migrations/0322_alter_awscostentrylineitemsummarybyec2compute_instance_name.py
Labels: smoke-tests, django migration, smokes-required, skip-migration-check

#5123 [COST-4930] Increase max_length for instance_name field
  koku/reporting/provider/aws/models.py
Labels: smoke-tests, smokes-required

#5119 [COST-4930] drop unrequested fields in ec2 model
  koku/reporting/provider/aws/models.py
Labels: smoke-tests, smokes-required, skip-migration-check

#5118 [COST-4930] Migration to drop unrequested fields from ec2-compute model
  koku/reporting/migrations/0323_remove_awscostentrylineitemsummarybyec2compute_availability_zone_and_org_unit.py
Labels: django migration, aws-smoke-tests, smokes-required

#5126 Set locale in migration script
  scripts/run_migrations.sh
Labels: hot-fix-smoke-tests, smokes-required

#5125 Add table exists check to trino migration management commands.
  koku/masu/management/commands/migrate_trino_tables.py
Labels: smoke-tests, smokes-required

#5127 [COST-4906] Update create table for Trino.
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5128 [COST-4744] Add data_transfer_direction to create table SQL for OCP on Azure trino tables
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5131 fix make load-test-customer-data
  dev/scripts/load_test_customer_data.sh
Labels: ok-to-skip-smokes

#5111 [COST-5035] - Use json_query for OCP on GCP sql tag matching
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
Labels: gcp-smoke-tests, smokes-required

#5056 [COST-4744] Azure network data processing SQL
  koku/api/report/ocp/provider_map.py
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_platform_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_worker_cost.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_node_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_p.sql
  koku/masu/database/sql/reporting_ocpazure_ocp_infrastructure_back_populate.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5057 [COST-4962] Populate OCP Network UI Summary Tables
  koku/masu/database/sql/openshift/reporting_ocp_network_summary_by_node_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_network_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_network_summary_p.sql
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#5091 [COST-4993] Unleash - function to check "EC2 Individual VM Compute" feature flag.
  koku/masu/processor/__init__.py
Labels: aws-smoke-tests, smokes-required

#5116 [COST-4749] Add ability to distribute unattributed network cost
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_unattributed_network_cost.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5124 [COST-4906] Add csi volume handle to hive ocp daily summary
  Pipfile.lock
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5135 [COST-5059] - Change source status beat cadence
  deploy/clowdapp.yaml
  deploy/kustomize/patches/scheduler.yaml
  docker-compose.yml
  koku/koku/celery.py
Labels: hot-fix-smoke-tests, smokes-required

#5139 [COST-5023, COST-5065] dependency update
  Pipfile
  Pipfile.lock
Labels: hot-fix-smoke-tests, smokes-required

#5134 [COST-4096] Migration to add volume handle to PVC topology
  koku/reporting/migrations/0324_ocppvc_csi_volume_handle.py
Labels: django migration, hot-fix-smoke-tests, smokes-required, skip-migration-check

#5132 [COST-4906] Update resource matching to use CSI volume handle
  dev/scripts/nise_ymls/ocp_on_azure/azure_static_data.yml
  dev/scripts/nise_ymls/ocp_on_azure/ocp_static_data.yml
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/util/azure/common.py
  koku/reporting/provider/ocp/models.py
Labels: hot-fix-smoke-tests, smokes-required

#5088 [COST-4742] OCP Network API
  dev/scripts/nise_ymls/ocp_on_azure/azure_static_data.yml
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/view.py
  koku/api/report/test/ocp/test_ocp_query_handler.py
  koku/api/report/test/ocp/view/test_ocp_network_view.py
  koku/api/report/test/util/baker_recipes.py
  koku/api/report/test/util/model_bakery_loader.py
Labels: ocp-smoke-tests, smokes-required

#5142 [COST-5030] - Removal of special case `namespace` tag matching
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: hot-fix-smoke-tests, smokes-required
