Repository project-koku/koku, pull requests merged in 2024-12, with the labels that each got.

#5394 [COST-5627] Fix Azure default extension issue
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
Labels: smoke-tests, smokes-required

#5413 Fix stripping of OCI tag prefix
  koku/masu/util/oci/oci_post_processor.py
Labels: hot-fix-smoke-tests, smokes-required

#5410 [COST-5675] Handling CostModel Does Not Exist exception
  koku/cost_models/cost_model_manager.py
Labels: smoke-tests, smokes-required

#5403 Remove unused unleash flag
  koku/masu/processor/__init__.py
Labels: hot-fix-smoke-tests, smokes-required

#5417 update dependencies
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5402 Remove unleash flag for disabling gcp resource matching
  koku/masu/processor/__init__.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/util/gcp/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5416 [COST-5170] - Auto large provider based on report count
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-penalty.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-penalty.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-penalty.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-penalty.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary-penalty.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/common/queues.py
  koku/common/test/test_queues.py
  koku/koku/settings.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#5419 [COST-5744, COST-57445]: dependency update
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5421 Handle AWS iam alert
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#5422 fix log message
  koku/masu/util/aws/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5423 [COST-5768] resource verification for OCP on GCP
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/verify/gcp/managed_ocp_on_gcp_verification.sql
  koku/masu/database/trino_sql/verify/gcp/managed_resources.sql
  koku/masu/test/database/test_gcp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5415 [COST-5658] Fix regression for removing report period
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
Labels: ocp-smoke-tests, smokes-required

#5428 Disable parallel testing in pr-checks and daily job
  Jenkinsfile
  smoke_test.sh
Labels: ok-to-skip-smokes
