Repository project-koku/koku, pull requests merged in 2024-10, with the labels that each got.

#5326 [COST-5548] Remove usage related to unattributed storage
  koku/api/report/aws/openshift/provider_map.py
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#5323 [COST-5453] Adding gzip support for Azure reports
  koku/masu/external/downloader/azure/azure_report_downloader.py
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
  koku/masu/util/azure/common.py
Labels: azure-smoke-tests, smokes-required

#5334 [COST-5557] - Skip validation if no provider exists
  koku/masu/processor/_tasks/data_validation.py
Labels: hot-fix-smoke-tests, smokes-required

#5313 [COST-5134] Update OpenShift tag matching to be key value pairs
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_gcp_openshift_daily.sql
  koku/masu/database/trino_sql/ocp_special_matched_tags.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_aws_verification.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_azure_verification.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_cloud_tables.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_gcp_verification.sql
  koku/masu/processor/orchestrator.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5335 [COST-5575] convert uom to metric-id
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
Labels: hot-fix-smoke-tests, smokes-required

#5333 [COST-5517] Applying security best practices in GH actions
  .github/workflows/check-image.yml
  .github/workflows/ci.yml
  .github/workflows/pre-release.yaml
Labels: ok-to-skip-smokes, github_actions

#5332 [COST-5427] Utilize an initial cte to optimize the distribution sql.
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_platform_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_unattributed_network_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_unattributed_storage_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_worker_cost.sql
Labels: ocp-smoke-tests, smokes-required

#5336 [COST-5492] Handle special characters in tag queries
  koku/api/report/queries.py
Labels: smoke-tests, ocp-smoke-tests, smokes-required

#5340 [COST-5560] update trino 461
  dev/containers/trino/etc/catalog/hive.properties
  dev/containers/trino/etc/hadoop-config/core-site.xml
  docker-compose.yml
Labels: ok-to-skip-smokes

#5339 [COST-5492] Handling OCI "free-form-tags" specific case.
  koku/api/report/queries.py
  koku/masu/util/oci/oci_post_processor.py
Labels: ocp-smoke-tests

#5341 [COST-5618] Remove schema size prometheus metric reporting
  koku/koku/celery.py
  koku/koku/metrics.py
  koku/koku/test_metrics.py
Labels: hot-fix-smoke-tests

#5344 [COST-5570] Capture prometheus metrics for RHEL ELS processing
  koku/masu/prometheus_stats.py
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
Labels: aws-smoke-tests, azure-smoke-tests

#5346 [COST-5603] Prevent zero for AWS disk capacity
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests

#5345 [COST-5609] Allow smokes-labeler job to write to pull requests
  .github/workflows/ci.yml
Labels: ok-to-skip-smokes

#5348 [COST-5570] Switch logging to info while adding debug
  koku/subs/subs_data_messenger.py
Labels: aws-smoke-tests, smokes-required

#5347 Update Masu tooling to recheck infra map
  koku/masu/api/recheck_infra_map.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/processor/ocp/ocp_cloud_updater_base.py
  koku/masu/test/api/test_recheck_infra_map.py
Labels: hot-fix-smoke-tests, smokes-required

#5355 delete dataexporter
  koku/api/dataexport/__init__.py
  koku/api/dataexport/models.py
  koku/api/dataexport/serializers.py
  koku/api/dataexport/syncer/__init__.py
  koku/api/dataexport/syncer/test_syncer.py
  koku/api/dataexport/test/__init__.py
  koku/api/dataexport/test/test_models.py
  koku/api/dataexport/test/test_serializers.py
  koku/api/dataexport/test/test_views.py
  koku/api/dataexport/uploader/__init__.py
  koku/api/dataexport/uploader/test_uploader.py
  koku/api/dataexport/validators.py
  koku/api/dataexport/views.py
  koku/api/migrations/0064_delete_dataexportrequest.py
  koku/api/models.py
  koku/api/urls.py
  koku/api/views.py
  koku/masu/celery/tasks.py
  koku/masu/test/celery/test_tasks.py
Labels: hot-fix-smoke-tests, smokes-required
