Repository project-koku/koku, pull requests merged in 2024-07, with the labels that each got.

#5196 [COST-5214] Remove directive to make the build work with docker
  Makefile
Labels: hot-fix-smoke-tests, ok-to-skip-smokes

#5197 [COST-5216] Delete filtering optimization
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: aws-smoke-tests, smokes-required

#5200 Revert "[COST-5216] Delete filtering optimization"
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5198 [COST-5226] - Skip S3 delete (daily flow) if we have marked deletion complete.
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#4444 [COST-5076] upgrade to python 3.11
  .github/workflows/ci.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.md
Labels: smoke-tests, smokes-required

#5202 [COST-5228] log outside for loop
  koku/masu/processor/_tasks/remove_expired.py
  koku/masu/processor/aws/aws_report_db_cleaner.py
  koku/masu/processor/azure/azure_report_db_cleaner.py
  koku/masu/processor/expired_data_remover.py
  koku/masu/processor/gcp/gcp_report_db_cleaner.py
  koku/masu/processor/oci/oci_report_db_cleaner.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#5204 log s3 batch deletes
  koku/masu/test/util/aws/test_common.py
  koku/masu/util/aws/common.py
Labels: smoke-tests, smokes-required

#5201 [COST-5219] Correctly report VM usage for metering when billing record is split
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
Labels: smoke-tests, smokes-required

#5058 [COST-4745] OCPGCP Network data processing SQL
  dev/scripts/nise_ymls/ocp_on_gcp/gcp_static_data.yml
  koku/masu/database/sql/reporting_ocpgcp_ocp_infrastructure_back_populate.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
Labels: gcp-smoke-tests, smokes-required

#5208 remove unused method
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
Labels: hot-fix-smoke-tests, smokes-required

#5209 Handle case when resource ID cannot be obtained
  koku/subs/subs_data_messenger.py
Labels: azure, azure-smoke-tests

#5206 [COST-5148] update EC2 compute insert sql
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute.sql
Labels: aws-smoke-tests, smokes-required

#5175 Unpause the csi volume handle sql
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#5211 [COST-5244, COST-5245, COST-5246, COST-5247] dependency update
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5148 [COST-4981] reset local unleash
  .env.example
  .gitignore
  .unleash/flags.json
  Makefile
  dev/containers/unleash/flags.json
  dev/scripts/setup_unleash.py
  docker-compose.yml
Labels: ok-to-skip-smokes

#5153 [Tech-Debt] Remove dead code from Trino upgrade.
  koku/masu/api/upgrade_trino/__init__.py
  koku/masu/api/upgrade_trino/test/__init__.py
  koku/masu/api/upgrade_trino/test/test_verify_parquet_files.py
  koku/masu/api/upgrade_trino/util/__init__.py
  koku/masu/api/upgrade_trino/util/constants.py
  koku/masu/api/upgrade_trino/util/state_tracker.py
  koku/masu/api/upgrade_trino/util/verify_parquet_files.py
  koku/masu/api/upgrade_trino/view.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/celery/tasks.py
Labels: smoke-tests, smokes-required

#5213 [COST-5252] cache schema/table exists
  koku/koku/cache.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/report_parquet_processor_base.py
  koku/masu/test/database/test_report_db_accessor_base.py
  koku/masu/test/processor/test_report_parquet_processor_base.py
Labels: smoke-tests, smokes-required

#5147 [COST-5093] Update mapped tags in EC2 summary table
  koku/api/report/test/util/baker_recipes.py
  koku/api/report/test/util/constants.py
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/sql/aws/aws_tag_mapping_update_summary_tables.sql
  koku/masu/processor/aws/aws_report_parquet_summary_updater.py
  koku/masu/test/database/test_aws_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5066 [COST-4912] Calculate node based unattributed storage (Azure)
  dev/scripts/nise_ymls/ocp_on_azure/azure_static_data.yml
  dev/scripts/nise_ymls/ocp_on_azure/ocp_static_data.yml
  docs/jinja_templating.md
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/view/test_views.py
  koku/koku/test_trino_db_utils.py
  koku/koku/trino_database.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_platform_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_unattributed_storage_cost.sql
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_worker_cost.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_node_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_by_project_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_pod_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/processor/__init__.py
  koku/masu/util/azure/common.py
Labels: azure-smoke-tests, smokes-required

#5214 [COST-5198] Only store user object on write requests
  koku/api/provider/provider_builder.py
  koku/koku/middleware.py
  koku/koku/test_middleware.py
  koku/sources/test/api/test_view.py
  koku/sources/test/test_kafka_listener.py
  koku/sources/test/test_kafka_message_processor.py
  koku/sources/test/test_kafka_source_manager.py
  koku/sources/test/test_tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#5191 [COST-5125] Trino migration command improvements
  koku/masu/management/commands/migrate_trino_tables.py
Labels: hot-fix-smoke-tests, smokes-required

#5216 [COST-4741] Add UsageType and Operation to daily data
  koku/masu/test/util/aws/test_aws_post_processor.py
  koku/masu/util/aws/aws_post_processor.py
Labels: aws-smoke-tests, trino migration, smokes-required

#5159 [COST-5114] Add type ahead support for the new EC2 fields
  docs/specs/openapi.json
  koku/api/resource_types/aws_ec2_compute_instances/__init__.py
  koku/api/resource_types/aws_ec2_compute_instances/view.py
  koku/api/resource_types/aws_ec2_compute_os/__init__.py
  koku/api/resource_types/aws_ec2_compute_os/view.py
  koku/api/resource_types/serializers.py
  koku/api/resource_types/test/test_views.py
  koku/api/urls.py
  koku/api/views.py
Labels: smoke-tests, smokes-required

#5219 [COST-5287] Prevent azure cost deduplication on disk-id resources
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: azure-smoke-tests, smokes-required

#5212 [COST-4283] OCP: set start-date based on data in file being processed
  Makefile
  koku/masu/external/kafka_msg_handler.py
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5221 [COST-5299] clear cache when table is dropped by migration
  koku/koku/cache.py
  koku/koku/test_cache.py
  koku/masu/management/commands/migrate_trino_tables.py
Labels: smoke-tests, smokes-required

#5222 Update nise and AWS DataTransferGenerator resource IDs
  .gitleaks.toml
  Pipfile.lock
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data.yml
Labels: hot-fix-smoke-tests, smokes-required

#5224 [COST-5289] EC2 compute API - update openapi doc
  docs/specs/openapi.json
Labels: smoke-tests, smokes-required

#5117 [COST-4945] Create a new API to return list of EC2-compute instances
  koku/api/common/pagination.py
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/aws/serializers.py
  koku/api/report/aws/view.py
  koku/api/report/constants.py
  koku/api/report/queries.py
  koku/api/report/test/aws/test_queries.py
  koku/api/report/test/aws/test_views.py
  koku/api/report/test/test_serializers.py
  koku/api/report/view.py
  koku/api/urls.py
  koku/api/views.py
Labels: smoke-tests, smokes-required

#5205 update data_updated_timestamp for polled provider that has no new rep…
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#5215 Consolidate local volume mounts
  .gitignore
  .trino/parquet_data/.gitkeep
  .trino/trino/.gitkeep
  Makefile
  dev/containers/minio/.gitignore
  dev/containers/trino/data/.gitignore
  dev/containers/trino/logs/.gitignore
  docker-compose.yml
Labels: ok-to-skip-smokes

#5225 [COST-5198] Skip customer save on get request
  koku/koku/middleware.py
Labels: hot-fix-smoke-tests, smokes-required

#5226 [COST-5280] - rename cpu/memory request/limits parameters
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku-reads.yaml
  deploy/kustomize/patches/koku-writes.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/nginx.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/sources-client.yaml
  deploy/kustomize/patches/sources-listener.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-penalty.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-penalty.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-penalty.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-penalty.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-penalty.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
Labels: smoke-tests, smokes-required

#5227 add additional info to INSERT operation
  koku/masu/database/ocp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5229 [COST-4993] gate ec2 endpoint with unleash
  koku/api/report/aws/view.py
  koku/api/report/test/aws/test_views.py
  tox.ini
Labels: smoke-tests, smokes-required

#5223 [COST-5288] Fix currency for network distribution
  koku/masu/database/sql/openshift/cost_model/distribute_cost/distribute_unattributed_network_cost.sql
Labels: smoke-tests, smokes-required

#5234 fix log message for failed parquet conversion
  koku/masu/processor/parquet/parquet_report_processor.py
Labels: hot-fix-smoke-tests, smokes-required

#5171 [COST-5141] vaccum expired trino partitions
  koku/masu/api/expired_data.py
  koku/masu/api/urls.py
  koku/masu/api/views.py
  koku/masu/celery/tasks.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/processor/_tasks/remove_expired.py
  koku/masu/processor/expired_data_remover.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_expired_data.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_report_db_cleaner.py
  koku/masu/test/processor/test_orchestrator.py
  koku/masu/test/processor/test_tasks.py
  koku/reporting/models.py
Labels: smoke-tests, smokes-required

#5233 [COST-5317] Support order by account_alias
  koku/api/report/aws/serializers.py
Labels: aws-smoke-tests, smokes-required

#5232 [COST-5318] Support exclude instance_name and operating_system params
  koku/api/report/aws/serializers.py
Labels: aws-smoke-tests, smokes-required

#5104 [COST-4741] - Separate AWS node network costs into a Network unattributed namespace
  koku/masu/database/sql/reporting_ocpaws_ocp_infrastructure_back_populate.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required

#5231 [COST-5315] Return network_unattributed_distributed costs in the OCP costs API
  koku/api/report/ocp/provider_map.py
  koku/api/report/ocp/query_handler.py
  koku/api/report/test/ocp/view/test_views.py
Labels: aws-smoke-tests, smokes-required

#5235 [COST-5319] Export EC2 compute response data to CSV
  koku/api/common/pagination.py
  koku/api/common/test_pagination.py
  koku/api/report/aws/provider_map.py
  koku/api/report/aws/query_handler.py
  koku/api/report/test/aws/test_queries.py
Labels: smoke-tests, smokes-required

#5240 Update ocp-smoke-tests keywords
  ci/functions.sh
Labels: ok-to-skip-smokes

#5238 [COST-5328] Fully distribute network unattributed costs
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: aws-smoke-tests, smokes-required
