Repository project-koku/koku, pull requests merged in 2025-07, with the labels that each got.

#5659 cast provider_uuid to string
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5654 Limit tag keys to enabled ones for Cloud providers and OCP in daily summary report
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpawscostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazurecostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_project_daily_summary_p.sql
Labels: smoke-tests, smokes-required

#5660 enable manage tables failback
  koku/masu/processor/__init__.py
Labels: hot-fix-smoke-tests, smokes-required

#5657 [COST-6461] Add group bys to postgresql insert
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/3_reporting_ocpawscostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/3_reporting_ocpazurecostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/3_reporting_ocpgcpcostlineitem_project_daily_summary_p.sql
  koku/masu/processor/parquet/summary_sql_metadata.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5663 [COST-4653] Remove redundant enable keys population
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/sql/reporting_azureenabledtagkeys.sql
  koku/masu/database/sql/reporting_gcpenabledtagkeys.sql
  koku/masu/processor/azure/azure_report_parquet_summary_updater.py
  koku/masu/processor/gcp/gcp_report_parquet_summary_updater.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5669 Dynamic partition matching
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
Labels: gcp-smoke-tests, smokes-required

#5667 Improve dev docs for partition pruning & GCP cross over data
  docs/gcp_cross_over_data.md
  docs/trino_partition_pruning.md
Labels: ok-to-skip-smokes

#5670 clean up previous month param
  koku/masu/database/gcp_report_db_accessor.py
Labels: smoke-tests, smokes-required

#5672 [COST-6570] - Dont process payloads outside retention period
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/data/ocp/bad_payload.tar.gz
  koku/masu/test/data/ocp/no_manifest.tar.gz
  koku/masu/test/data/ocp/outside_retention_payload.tar.gz
  koku/masu/test/data/ocp/payload.tar.gz
  koku/masu/test/data/ocp/payload2.tar.gz
  koku/masu/test/data/ocp/payload2/manifest.json
  koku/masu/test/data/ocp/ros_payload.tar.gz
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: smoke-tests, smokes-required

#5671 [COST-6477] Support fractional hours for VMs metrics
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/openshift/cost_model/hourly_cost_virtual_machine.sql
  koku/masu/database/trino_sql/openshift/cost_model/hourly_vm_core.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cost_model_cost_updater.py
Labels: ocp-smoke-tests, smokes-required

#5676 [COST-6489] add parent keys to valid list
  koku/api/query_params.py
  koku/api/report/test/test_queries.py
  koku/api/test_query_params.py
Labels: smoke-tests, smokes-required

#5675 [COST-6488] Year-Month fix
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
Labels: gcp-smoke-tests, smokes-required

#5678 [COST-6589] Rename namespace to project
  dev/scripts/cost_models/openshift_on_prem_cost_model.json
  koku/api/metrics/constants.py
  koku/cost_models/serializers.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/openshift/cost_model/monthly_project_tag_based.sql
Labels: ocp-smoke-tests, smokes-required

#5677 [COST-6501] Fix 1st of the month VM issue
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
Labels: ocp-smoke-tests, smokes-required

#5684 Revert "[COST-6498] add null/empty filters for PVC names"
  koku/masu/database/trino_sql/openshift/populate_vm_tmp_table_with_vm_report.sql
Labels: smoke-tests, smokes-required

#5688 [COST-6635] - Fix project cost node count
  koku/masu/database/trino_sql/openshift/cost_model/monthly_project_tag_based.sql
Labels: ocp-smoke-tests, smokes-required

#5689 [COST-6618] Handle null matching on vm storage data
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
Labels: ocp-smoke-tests, smokes-required

#5690 Remove adal & msrestazure
  Pipfile
  Pipfile.lock
  koku/masu/external/downloader/azure/azure_service.py
  koku/masu/test/external/downloader/azure/test_azure_services.py
  koku/providers/azure/client.py
  koku/providers/azure/provider.py
  koku/sources/test/test_sources_error_message.py
Labels: azure-smoke-tests, smokes-required
