Repository project-koku/koku, pull requests merged in 2025-02, with the labels that each got.

#5475 [COST-5137] Azure managed summary
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_azure_verification.sql
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/summary_sql_metadata.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/reporting/provider/azure/models.py
Labels: azure-smoke-tests, smokes-required

#5482 fix secret template
  dev/secrets-template.yaml
Labels: ok-to-skip-smokes

#5469 [COST-5137] Initial managed summary tasks rework
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/managed_reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_compute_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_region_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_cost_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_database_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_network_summary_p.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpaws_storage_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/managed_reporting_ocpazurecostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_compute_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_location_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_cost_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_database_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_network_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazure_storage_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_compute_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_account_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_gcp_project_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_region_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_cost_summary_by_service_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_cost_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_database_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_network_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcp_storage_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/processor/__init__.py
  koku/masu/processor/tasks.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#5485 Use local settings in ephemeral daily job to disable Ibutsu
  smoke_test.sh
Labels: ok-to-skip-smokes

#5480 [COST-5860] - hive data migration script and CJI
  Pipfile
  Pipfile.lock
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  scripts/hive-migration-polars.py
Labels: smoke-tests, smokes-required

#5487 [COST-5860] drop assume-role requirement
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  scripts/hive-migration-polars.py
Labels: hot-fix-smoke-tests, smokes-required

#5488 remove `AWS_ASSUME_ROLE_ARN` from parse args
  scripts/hive-migration-polars.py
Labels: hot-fix-smoke-tests, smokes-required

#5489 add progress to migration script
  scripts/hive-migration-polars.py
Labels: hot-fix-smoke-tests, smokes-required

#5491 Revert "Use local settings in ephemeral daily job to disable Ibutsu"
  smoke_test.sh
Labels: ok-to-skip-smokes

#5486 [COST-5137] - Fix OCP-Azure-Managed sql + report_data masu endpoint
  koku/masu/api/report_data.py
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/test/api/test_report_data.py
Labels: smoke-tests, smokes-required

#5494 [COST-5886] update kafka status check
  Pipfile
  Pipfile.lock
  koku/kafka_utils/test/test_utils.py
  koku/kafka_utils/utils.py
  koku/sources/kafka_listener.py
  koku/sources/test/test_kafka_listener.py
Labels: smoke-tests, smokes-required

#5496 Updates to the managed flow
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpawscostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazurecostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_project_daily_summary_p.sql
Labels: hot-fix-smoke-tests, smokes-required

#5490 Update env example
  .env.example
  dev/scripts/load_test_customer_data.sh
Labels: ok-to-skip-smokes

#5484 [COST-5861] OCP on AWS managed population
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_aws_verification.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/reporting/provider/aws/models.py
Labels: smoke-tests, smokes-required

#5478 [COST-5551] enable Glue Data Catalog in pr_check/daily smokes
  Jenkinsfile
  ci/functions.sh
  smoke_test.sh
Labels: smoke-tests, smokes-required

#5497 [COST-5875] Clean up new managed tables when a source is deleted
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/reporting/models.py
Labels: smoke-tests, smokes-required

#5498 [COST-5898] update to ubuntu-latest for github actions
  .github/workflows/ci.yml
  .github/workflows/pre-release.yaml
Labels: ok-to-skip-smokes

#5471 [COST-5551] add config for local Glue Data Catalog utilization
  .env.example
  Makefile
  dev/containers/trino/etc/catalog/glue.properties
  dev/containers/trino/etc/catalog/hive.properties
  dev/scripts/delete_glue.py
  docker-compose.yml
Labels: ok-to-skip-smokes

#5500 [COST-5866] Add row_uuid to parquet files
  koku/masu/test/util/azure/test_azure_post_processor.py
  koku/masu/util/aws/aws_post_processor.py
  koku/masu/util/azure/azure_post_processor.py
  koku/masu/util/gcp/gcp_post_processor.py
Labels: smoke-tests, smokes-required

#5502 improve sql filtering logic on the masu trino endpoint
  koku/masu/api/trino.py
  koku/masu/test/api/test_trino.py
Labels: smoke-tests, smokes-required

#5505 [COST-5906] do not deploy hive to ephemeral
  Jenkinsfile
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  dev/config.yaml.github-example
  dev/config.yaml.local-example
  scripts/hive-migration-polars.py
  smoke_test.sh
Labels: hot-fix-smoke-tests, smokes-required

#5501 update trino and hive config
  dev/containers/trino/etc/catalog/glue.properties
  dev/containers/trino/etc/catalog/hive.properties
  docker-compose.yml
Labels: ok-to-skip-smokes

#5503 [COST-5897] Remove unused columns from managed flow
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/processor/parquet/summary_sql_metadata.py
Labels: smoke-tests, smokes-required

#5507 Fix deduplication of csi storage on managed flow
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
Labels: smoke-tests, smokes-required

#5511 Bump dependencies
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5510 Fix EC2 attribute error
  koku/api/report/aws/query_handler.py
Labels: smoke-tests, smokes-required

#5513 [COST-5839] - Switch to dynamic batch sizing for polling
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-penalty.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-penalty.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-penalty.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-penalty.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-summary-penalty.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  docker-compose.yml
  koku/api/provider/models.py
  koku/api/provider/test/test_models.py
  koku/koku/settings.py
  koku/masu/processor/orchestrator.py
Labels: smoke-tests, smokes-required

#5509 [COST-5890] - Adding Node core month to cost model
  docs/cost_model.md
  koku/api/metrics/constants.py
  koku/api/metrics/test/test_views.py
  koku/cost_models/serializers.py
  koku/masu/database/cost_model_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/default_infrastructure_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/default_supplementary_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/infrastructure_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/monthly_cost_cluster_and_node.sql
  koku/masu/database/sql/openshift/cost_model/monthly_cost_node_by_tag.sql
  koku/masu/database/sql/openshift/cost_model/supplementary_tag_rates.sql
  koku/masu/database/sql/openshift/cost_model/usage_costs.sql
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/test/database/test_cost_model_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cost_model_cost_updater.py
  koku/reporting/migrations/0328_alter_ocpusagelineitemdailysummary_monthly_cost_type.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#5512 [COST-5919] Update OCP VMs provider map
  koku/api/report/ocp/provider_map.py
  koku/api/report/test/ocp/view/test_views.py
Labels: smoke-tests, smokes-required

#5519 update local trino to 471
  docker-compose.yml
Labels: ok-to-skip-smokes

#5517 [COST-5923] OCP virtual machine distributed cost SQL
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
Labels: smoke-tests, smokes-required

#5518 [COST-5887] - Return source status
  koku/providers/gcp/provider.py
  koku/providers/test/gcp/test_provider.py
Labels: hot-fix-smoke-tests, smokes-required

#5523 [COST-3663] db upgrade prep
  Pipfile
  Pipfile.lock
  koku/masu/api/db_performance/db_performance.py
  koku/masu/database/report_db_accessor_base.py
Labels: smoke-tests, smokes-required
