Repository project-koku/koku, pull requests merged in 2025-06, with the labels that each got.

#5629 [COST-6114] Populate virtualization with vm report values
  koku/api/report/test/util/model_bakery_loader.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/create_virtualization_tmp_table.sql
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p.sql
  koku/masu/database/sql/openshift/reporting_ocp_vm_summary_p_storage.sql
  koku/masu/database/trino_sql/openshift/populate_vm_tmp_table.sql
  koku/masu/database/trino_sql/openshift/populate_vm_tmp_table_with_vm_report.sql
  koku/masu/database/trino_sql/openshift/pvc_to_vm_name_mapping.sql
  koku/masu/database/trino_sql/test/ocp/mimic_virt_ui.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#5630 OCP Summary: Don't include pods without a node
  koku/masu/database/trino_sql/reporting_ocpusagelineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#5632 [COST-6390] Add sql files for vm core per hour & month
  koku/masu/database/sql/openshift/cost_model/delete_monthly_cost.sql
  koku/masu/database/trino_sql/openshift/cost_model/hourly_vm_core.sql
  koku/masu/database/trino_sql/openshift/cost_model/monthly_vm_core.sql
Labels: ok-to-skip-smokes

#5635 [COST-6116] add VM core-hour/core-month metrics
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data.yml
  koku/api/metrics/constants.py
  koku/api/metrics/test/test_views.py
  koku/api/metrics/views.py
  koku/cost_models/serializers.py
  koku/cost_models/test/test_serializers.py
  koku/cost_models/test/test_view.py
  koku/masu/database/cost_model_db_accessor.py
  koku/masu/processor/__init__.py
  koku/masu/test/database/test_cost_model_db_accessor.py
  koku/reporting/migrations/0335_alter_ocpusagelineitemdailysummary_monthly_cost_type.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#5637 [COST-6116] switch error log to warning
  koku/masu/database/ocp_report_db_accessor.py
Labels: hot-fix-smoke-tests, smokes-required

#5646 [COST-6460] - fix row_uuid usage for network unallocated
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
Labels: smoke-tests, smokes-required

#5647 [COST-6164] Replaces inline PromQL expressions with pre-aggregated metrics
  dashboards/grafana-dashboard-insights-hccm.configmap.yaml
Labels: ok-to-skip-smokes

#5649 update urllib3
  Pipfile.lock
Labels: smoke-tests, smokes-required
