Repository project-koku/koku, pull requests merged in 2025-09, with the labels that each got.

#5729 [COST-6527] add v4.1.0 operator commits
  koku/masu/util/ocp/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5724 [COST-6699] Memory distribution
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/usage_costs.sql
Labels: hot-fix-smoke-tests, smokes-required

#5731 [COST-6689] fix EXACT_AWS_CATEGORY_PREFIX definition
  koku/api/report/constants.py
Labels: aws-smoke-tests, smokes-required

#5732 [COST-6672, COST-6673] add autoscalers for all download workers
  deploy/clowdapp.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
Labels: hot-fix-smoke-tests, smokes-required

#5736 [COST-6743] handle empty operator payload file
  koku/masu/external/kafka_msg_handler.py
  koku/masu/test/data/ocp/empty-file-payload/empty-file.csv
  koku/masu/test/data/ocp/empty-file-payload/manifest.json
  koku/masu/test/data/ocp/empty-file-payload/not-empty-file.csv
  koku/masu/test/external/test_kafka_msg_handler.py
Labels: ocp-smoke-tests, smokes-required

#5741 [COST-6645] unpin boto3
  Pipfile
  Pipfile.lock
  koku/sources/test/api/test_view.py
Labels: full-run-smoke-tests, smokes-required

#5748 update settings dict
  koku/api/resource_types/view.py
Labels: smoke-tests, smokes-required

#5751 Bump nise
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5749 [COST-6649] handle ReportSummaryUpdaterProviderNotFoundError
  koku/masu/processor/tasks.py
  koku/masu/test/processor/test_tasks.py
Labels: smoke-tests, smokes-required

#5743 [COST-4905] GCP Persistent Disk Capacity & resource matching
  dev/scripts/nise_ymls/ocp_on_gcp/gcp_static_data.yml
  dev/scripts/nise_ymls/ocp_on_gcp/ocp_static_data.yml
  koku/api/query_handler.py
  koku/api/report/gcp/filter_collection.py
  koku/api/report/gcp/openshift/provider_map.py
  koku/api/report/gcp/provider_map.py
  koku/api/report/queries.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/processor/__init__.py
  koku/reporting/models.py
Labels: gcp-smoke-tests, smokes-required
