Repository project-koku/koku, pull requests merged in 2025-05, with the labels that each got.

#5590 [COST-6264] Handle multiple usage accounts in subs extractor
  koku/subs/subs_data_extractor.py
  koku/subs/test/test_subs_data_extractor.py
  koku/subs/trino_sql/aws/subs_row_count.sql
  koku/subs/trino_sql/aws/subs_summary.sql
  koku/subs/trino_sql/azure/subs_row_count.sql
  koku/subs/trino_sql/azure/subs_summary.sql
Labels: hot-fix-smoke-tests, smokes-required

#5584 Add debug logging command for Docker logs
  Makefile
Labels: ok-to-skip-smokes

#5588 [COST-6219] Remove OCI tables (model + migration)
  Pipfile.lock
  koku/api/migrations/0066_alter_provider_type_and_more.py
  koku/api/provider/models.py
  koku/cost_models/migrations/0008_alter_costmodel_source_type_and_more.py
  koku/reporting/migrations/0332_remove_ocicomputesummarybyaccountp_source_uuid_and_more.py
  koku/reporting/models.py
  koku/reporting/provider/oci/models.py
  koku/reporting_common/migrations/0043_alter_diskcapacity_provider_type.py
  koku/sources/test/test_kafka_message_processor.py
Labels: smoke-tests, smokes-required

#5597 [COST-3739] Remove unused GCP code path
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/reporting_ocpinfrastructure_provider_map.sql
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/util/gcp/test_common.py
  koku/masu/util/gcp/common.py
  koku/providers/gcp/provider.py
  koku/providers/test/gcp/test_provider.py
Labels: gcp-smoke-tests, smokes-required

#5600 [COST-6238] Add new fields to OCPCostSummaryByProjectP model
  koku/masu/database/sql/openshift/reporting_ocp_cost_summary_by_project_p.sql
  koku/reporting/migrations/0333_ocpcostsummarybyprojectp_infrastructure_markup_cost_and_more.py
  koku/reporting/provider/ocp/models.py
Labels: smoke-tests, smokes-required

#5608 [COST-6319] update nginx image
  deploy/clowdapp.yaml
  deploy/kustomize/patches/nginx.yaml
Labels: hot-fix-smoke-tests, smokes-required

#5592 [COST-6268] - Refactor Managed table tasks to run per cluster
  koku/masu/api/process_openshift_on_cloud.py
  koku/masu/api/report_data.py
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/0_prepare_daily_summary_tables.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/1_resource_matching_by_cluster.sql
  koku/masu/database/trino_sql/ocp_special_matched_tags.sql
  koku/masu/management/commands/migrate_trino_tables.py
  koku/masu/processor/__init__.py
  koku/masu/processor/orchestrator.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/parquet/summary_sql_metadata.py
  koku/masu/processor/tasks.py
  koku/masu/test/api/test_process_openshift_on_cloud.py
  koku/masu/test/api/test_report_data.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/test_tasks.py
Labels: full-run-smoke-tests, smokes-required

#5605 [COST-5905] fix trailing slash for `invalidate_cache` masu endpoint
  koku/masu/api/urls.py
Labels: hot-fix-smoke-tests, smokes-required

#5591 [COST-5281] OCP parquet cleanup
  Pipfile
  Pipfile.lock
  dev/scripts/load_test_customer_data.sh
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/external/test_ros_report_shipper.py
  koku/masu/test/util/ocp/test_common.py
  koku/masu/util/aws/common.py
  koku/masu/util/ocp/common.py
Labels: smoke-tests, smokes-required

#5611 [COST-6268] add in managed table log msgs
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
Labels: hot-fix-smoke-tests, smokes-required

#5604 [COST-6269] Migration to add latest_event_sent column
  .dockerignore
  koku/reporting/migrations/0334_subslastprocessed_event_sent.py
  koku/reporting/provider/models.py
Labels: smoke-tests, smokes-required

#5596 [COST-6269] Add a timestamp to indicate the event was sent
  koku/subs/subs_data_messenger.py
  koku/subs/test/test_subs_data_messenger.py
Labels: smoke-tests, smokes-required

#5613 [COST-6308] - handle new or unknown Operator reports
  koku/masu/processor/parquet/parquet_report_processor.py
  koku/masu/test/processor/parquet/test_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5614 Update README.md
  README.md
Labels: ok-to-skip-smokes

#5615 use `no_account` for account id if missing
  koku/masu/external/kafka_msg_handler.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/external/test_kafka_msg_handler.py
  koku/masu/test/external/test_ros_report_shipper.py
  koku/masu/util/ocp/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5609 [COST-5523] Update tag handler to account for tag mappings
  koku/api/tags/queries.py
  koku/api/tags/test/aws/test_aws_tag_query_handler.py
Labels: smoke-tests, smokes-required

#5619 remove logging statement
  koku/masu/processor/orchestrator.py
Labels: hot-fix-smoke-tests, smokes-required

#5620 handle null resource_optimization_files
  koku/masu/util/ocp/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5621 pre validator for `files` and `resource_optimization_files`
  koku/masu/util/ocp/common.py
Labels: hot-fix-smoke-tests, smokes-required

#5616 [COST-6333] update unleash client
  Pipfile
  Pipfile.lock
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/listener.yaml
  docker-compose.yml
  koku/koku/settings.py
  koku/masu/external/ros_report_shipper.py
  koku/masu/test/external/test_ros_report_shipper.py
Labels: smoke-tests, smokes-required

#5625 fix UnleashClient attribute error
  koku/koku/feature_flags.py
Labels: hot-fix-smoke-tests, smokes-required

#5617 [COST-6330] - Process new VM report
  koku/masu/processor/ocp/ocp_report_parquet_processor.py
  koku/masu/util/ocp/common.py
  koku/masu/util/ocp/ocp_post_processor.py
  koku/reporting/provider/ocp/models.py
Labels: hot-fix-smoke-tests, smokes-required

#5618 [COST-6335] - Add cost model VM metric supported flag to cluster info
  koku/api/provider/provider_manager.py
  koku/api/provider/test/test_provider_manager.py
Labels: smoke-tests, smokes-required
