Repository project-koku/koku, pull requests merged in 2025-04, with the labels that each got.

#5560 [COST-6083] Handle null requests during vm tag exclusion
  koku/api/report/ocp/provider_map.py
Labels: smoke-tests, smokes-required

#5553 [COST-6129] Remove unnecessary delete for cost per vm hour metric
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/openshift/cost_model/hourly_cost_virtual_machine.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: ocp-smoke-tests, smokes-required

#5559 [COST-6097] Add Cluster per hour cost metric
  dev/scripts/cost_models/openshift_on_prem_cost_model.json
  koku/api/metrics/constants.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/trino_sql/openshift/cost_model/hourly_cost_cluster.sql
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: ocp-smoke-tests, smokes-required

#5563 add managed tables unleash enabled log for QE
  koku/masu/processor/__init__.py
Labels: hot-fix-smoke-tests, smokes-required

#5571 add some more logging
  koku/masu/api/report_data.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/processor/tasks.py
Labels: hot-fix-smoke-tests, smokes-required

#5573 add message for github-action ImportError
  .github/scripts/check_migrations.sh
Labels: ok-to-skip-smokes

#5576 Bump timeout for full-run-smoke-tests
  ci/functions.sh
Labels: hot-fix-smoke-tests, smokes-required

#5578 [COST-6158] - Handle upfront/recurring fees for amortised costs
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_awscostentrylineitem_summary_by_ec2_compute_p.sql
Labels: aws-smoke-tests, smokes-required

#5574 [COST-6232] Handle node labels for vm hourly tag based rates
  koku/masu/database/trino_sql/openshift/cost_model/hourly_cost_vm_tag_based.sql
Labels: smoke-tests, smokes-required

#5570 [COST-6097] distribute cluster-hour by node size too
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/usage_costs.sql
  koku/masu/database/trino_sql/openshift/cost_model/hourly_cost_cluster.sql
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
  koku/masu/test/processor/ocp/test_ocp_cost_model_cost_updater.py
Labels: smoke-tests, smokes-required

#5569 [COST-6162] nise yamls for ROSA example
  dev/scripts/nise_ymls/ocp_on_aws/aws_static_data_rosa.yml
  dev/scripts/nise_ymls/ocp_on_aws/ocp_static_data_rosa.yml
Labels: ok-to-skip-smokes

#5581 [COST-3332] Remove redundant fields project_markup_cost and pod_cost from reporting queries
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_aws.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_azure.sql
  koku/masu/database/sql/openshift/all/reporting_ocpallcostlineitem_project_daily_summary_gcp.sql
  koku/masu/database/sql/reporting_ocpazure_ocp_infrastructure_back_populate.sql
  koku/masu/database/sql/reporting_ocpgcp_ocp_infrastructure_back_populate.sql
  koku/masu/database/trino_sql/aws/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/aws/openshift/reporting_ocpawscostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/azure/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/azure/openshift/reporting_ocpazurecostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/gcp/openshift/populate_daily_summary/2_summarize_data_by_cluster.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_project_daily_summary_p.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
  koku/reporting/provider/gcp/openshift/models.py
Labels: smoke-tests, smokes-required

#5585 [COST-6097] filter empty node name
  koku/masu/database/sql/openshift/cost_model/usage_costs.sql
Labels: hot-fix-smoke-tests, smokes-required

#5582 [COST-3332] Drop project_markup_cost, pod_cost and pod_credit fields from the database schema
  koku/reporting/migrations/0331_remove_costsummary_project_markup_cost_and_more.py
  koku/reporting/provider/all/openshift/models.py
  koku/reporting/provider/aws/openshift/models.py
  koku/reporting/provider/azure/openshift/models.py
  koku/reporting/provider/gcp/openshift/models.py
  koku/reporting/provider/ocp/costs/models.py
Labels: smoke-tests, smokes-required

#5577 [COST-5995] - Add new GCP table source validation
  koku/masu/external/downloader/gcp/gcp_report_downloader.py
  koku/masu/util/gcp/common.py
  koku/providers/gcp/provider.py
  koku/providers/test/gcp/test_provider.py
Labels: gcp-smoke-tests, smokes-required

#5579 [COST-6208] Update vm month for tag based rates
  koku/cost_models/sql_parameters.py
  koku/cost_models/test/test_sql_parameters.py
  koku/masu/database/ocp_report_db_accessor.py
  koku/masu/database/sql/openshift/cost_model/monthly_cost_virtual_machine.sql
  koku/masu/processor/ocp/ocp_cost_model_cost_updater.py
  koku/masu/test/database/test_ocp_report_db_accessor.py
Labels: ocp-smoke-tests, smokes-required
