Repository project-koku/koku, pull requests merged in 2025-10, with the labels that each got.

#5759 fix unit tests
  koku/masu/test/external/downloader/aws/test_aws_report_downloader.py
  koku/masu/test/external/downloader/azure/test_azure_report_downloader.py
  koku/masu/test/external/downloader/gcp/test_gcp_report_downloader.py
  koku/masu/test/external/downloader/gcp_local/test_gcp_local_report_downloader.py
Labels: ok-to-skip-smokes

#5763 dependency updates
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5762 Cost 6866 operator version check update
  koku/api/provider/provider_manager.py
Labels: smoke-tests, smokes-required

#5766 [COST-6651] remove old ci-ext files
  .github/workflows/ci.yml
  Jenkinsfile
  build_deploy.sh
  ci/functions.sh
  smoke_test.sh
Labels: ok-to-skip-smokes

#5767 [COST-6704] fix forecasts RBAC
  docker-compose.yml
  koku/api/query_handler.py
  koku/api/query_params.py
  koku/forecast/forecast.py
Labels: smoke-tests, smokes-required

#5750 [COST-6759] Fix the exact and partial filters combination bug
  koku/api/report/queries.py
  koku/api/report/serializers.py
  koku/api/report/test/test_queries.py
  koku/api/report/test/test_serializers.py
Labels: full-run-smoke-tests, smokes-required
