Repository project-koku/koku, pull requests merged in 2025-01, with the labels that each got.

#5433 [COST-5784] dependency update
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5435 [COST-5793] remove croniter dependency
  Pipfile
  Pipfile.lock
  koku/koku/celery.py
Labels: smoke-tests, smokes-required

#5436 Add unleash flag to skip trino tag matched get logic
  koku/masu/processor/__init__.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: hot-fix-smoke-tests, smokes-required

#5438 add dependabot config
  .github/dependabot.yml
Labels: ok-to-skip-smokes

#5442 missing where clause
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#5440 fix ephemeral bucket names
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
Labels: hot-fix-smoke-tests, smokes-required

#5441 add celery task id chain
  koku/koku/settings.py
Labels: hot-fix-smoke-tests, smokes-required

#5444 remove some unused env variables
  .github/workflows/ci.yml
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  deploy/kustomize/patches/koku-reads.yaml
  deploy/kustomize/patches/koku-writes.yaml
  deploy/kustomize/patches/listener.yaml
  deploy/kustomize/patches/masu.yaml
  deploy/kustomize/patches/scheduler.yaml
  deploy/kustomize/patches/worker-celery.yaml
  deploy/kustomize/patches/worker-cost-model-penalty.yaml
  deploy/kustomize/patches/worker-cost-model-xl.yaml
  deploy/kustomize/patches/worker-cost-model.yaml
  deploy/kustomize/patches/worker-download-penalty.yaml
  deploy/kustomize/patches/worker-download-xl.yaml
  deploy/kustomize/patches/worker-download.yaml
  deploy/kustomize/patches/worker-hcs.yaml
  deploy/kustomize/patches/worker-ocp-penalty.yaml
  deploy/kustomize/patches/worker-ocp-xl.yaml
  deploy/kustomize/patches/worker-ocp.yaml
  deploy/kustomize/patches/worker-priority-penalty.yaml
  deploy/kustomize/patches/worker-priority-xl.yaml
  deploy/kustomize/patches/worker-priority.yaml
  deploy/kustomize/patches/worker-refresh-penalty.yaml
  deploy/kustomize/patches/worker-refresh-xl.yaml
  deploy/kustomize/patches/worker-refresh.yaml
  deploy/kustomize/patches/worker-subs-extraction.yaml
  deploy/kustomize/patches/worker-subs-transmission.yaml
  deploy/kustomize/patches/worker-summary-penalty.yaml
  deploy/kustomize/patches/worker-summary-xl.yaml
  deploy/kustomize/patches/worker-summary.yaml
  dev/scripts/sync_s3_lifecycle.py
  docker-compose.yml
  docs/devtools.md
  koku/koku/settings.py
  koku/masu/test/util/test_upload.py
  koku/masu/util/aws/common.py
  koku/masu/util/upload.py
  tox.ini
Labels: smoke-tests, smokes-required

#5431 [COST-5796] handle Customer.DoesNotExist exception
  koku/koku/middleware.py
  koku/koku/test_middleware.py
  koku/masu/management/commands/migrate_trino_tables.py
Labels: smoke-tests, smokes-required

#5443 adding year month to disk join where clause
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#5451 use quay api to see if tag is available
  ci/functions.sh
Labels: hot-fix-smoke-tests

#5452 remove ephemeral secrets from clowdapp
  ci/functions.sh
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  smoke_test.sh
Labels: smoke-tests, smokes-required

#5453 Add missing where clause to temp table cte
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/gcp/openshift/reporting_ocpgcpcostlineitem_daily_summary_resource_id.sql
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#5447 Divide unattributed storage cost by # of clusters utilizing disk
  koku/masu/database/trino_sql/reporting_ocpawscostlineitem_daily_summary.sql
  koku/masu/database/trino_sql/reporting_ocpazurecostlineitem_daily_summary.sql
Labels: smoke-tests, smokes-required

#5456 dependency update
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5459 upgrade minio
  docker-compose.yml
Labels: ok-to-skip-smokes

#5457 pin boto to 1.35.90
  Pipfile
  Pipfile.lock
Labels: smoke-tests, smokes-required

#5462 undo POSTGRES_SQL_SERVICE_HOST/PORT in docker-compose
  .env.example
  docker-compose.yml
Labels: ok-to-skip-smokes

#5463 Add MINIO_ENDPOINT to env
  .env.example
  docker-compose.yml
Labels: ok-to-skip-smokes

#5448 [COST-5796] correctly log exception outside log_json function
  koku/koku/middleware.py
Labels: hot-fix-smoke-tests, smokes-required

#5437 add polling timestamp to masu sources endpoint
  koku/masu/api/sources/serializers.py
  koku/masu/api/sources/test/test_serializers.py
Labels: hot-fix-smoke-tests, smokes-required

#5464 [COST-5565] - Adding inserts for missed column entries
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
Labels: smoke-tests, smokes-required

#5427 [COST-5773] Handle multiple resource for OCP on GCP managed flow
  Makefile
  dev/scripts/load_test_customer_data.sh
  dev/scripts/nise_ymls/ocp_on_gcp/gcp_static_data.yml
  dev/scripts/nise_ymls/ocp_on_gcp/ocp_static_replicate_pvc.yml
  dev/scripts/test_customer.yaml
  koku/masu/database/aws_report_db_accessor.py
  koku/masu/database/azure_report_db_accessor.py
  koku/masu/database/gcp_report_db_accessor.py
  koku/masu/database/report_db_accessor_base.py
  koku/masu/database/trino_sql/aws/openshift/managed_aws_openshift_daily.sql
  koku/masu/database/trino_sql/azure/openshift/managed_azure_openshift_daily.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_flow/0_populate_uuid_tmp_table.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_flow/1_populate_managed_tmp_table.sql
  koku/masu/database/trino_sql/gcp/openshift/managed_flow/2_managed_gcp_openshift_daily.sql
  koku/masu/database/trino_sql/ocp_special_matched_tags.sql
  koku/masu/database/trino_sql/verify/gcp/managed_ocp_on_gcp_verification.sql
  koku/masu/database/trino_sql/verify/gcp/managed_resources.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_aws_verification.sql
  koku/masu/database/trino_sql/verify/managed_ocp_on_azure_verification.sql
  koku/masu/processor/parquet/managed_flow_params.py
  koku/masu/processor/parquet/ocp_cloud_parquet_report_processor.py
  koku/masu/test/database/test_aws_report_db_accessor.py
  koku/masu/test/database/test_azure_report_db_accessor.py
  koku/masu/test/database/test_gcp_report_db_accessor.py
  koku/masu/test/processor/parquet/test_ocp_cloud_parquet_report_processor.py
Labels: smoke-tests, smokes-required

#5465 more prep for glue
  .env.example
  .github/workflows/ci.yml
  deploy/clowdapp.yaml
  deploy/kustomize/base/base.yaml
  dev/scripts/load_test_customer_data.sh
  koku/koku/configurator.py
  koku/koku/settings.py
  koku/masu/test/api/test_db_performance.py
Labels: smoke-tests, smokes-required

#5466 update dev scripts
  dev/scripts/common/logging.sh
  dev/scripts/load_test_customer_data.sh
Labels: ok-to-skip-smokes

#5468 add defaults for load-test-customer-data script
  dev/scripts/load_test_customer_data.sh
Labels: ok-to-skip-smokes

#5432 [COST-5851] one expiration task per provider_type
  koku/api/report/test/util/baker_recipes.py
  koku/koku/koku_test_runner.py
  koku/masu/processor/ocp/ocp_report_db_cleaner.py
  koku/masu/processor/orchestrator.py
  koku/masu/test/api/test_expired_data.py
  koku/masu/test/processor/test_orchestrator.py
Labels: smoke-tests, smokes-required

#5461 [COST-5551] utilize AWS Glue Data Catalog for PR smoke tests
  .env.example
  Jenkinsfile
  ci/functions.sh
  docker-compose.yml
  smoke_test.sh
Labels: smoke-tests, smokes-required

#5472 fix daily main smokes job
  smoke_test.sh
Labels: ok-to-skip-smokes

#5476 reversions - disable Glue in PR checks
  .env.example
  Jenkinsfile
  ci/functions.sh
  docker-compose.yml
  koku/koku/configurator.py
  koku/koku/settings.py
  koku/masu/test/api/test_db_performance.py
  smoke_test.sh
Labels: smoke-tests, smokes-required

#5454 add secrets template
  dev/config.yaml.github-example
  dev/config.yaml.local-example
  dev/secrets-template.yaml
Labels: ok-to-skip-smokes
